sys_eventx.c File Reference
Simple event based operating system.
#include `..\includes\allheaders.h`
*
Data Structures
struct x_module_info_t
Task descrtiption data structure. More...
struct x_system_t
OS internal data strucutre. More...
struct x_system_volatile_t
OS volatile internal data strucutre. More...
Macros
#define X_MAX_MODULE
Max amount of tasks.
Functions
void __attribute__ ((__interrupt__, auto_psv))
OS timer tick function.
void x_init (void)
OS internal init.
void x_init_task (x_task_fn task_fn, x_notify_fn notify_fn, x_task_id *pHandle_id, const char *task_name)
OS task init function.
void x_start (void)
OS function which starts event scheduling.
void x_loop (void)
OS function which should be called in idle loop.
void x_send_event (x_event *event)
OS event scheduling function.
void x_send_notify (x_notify *notify)
OS notification processing request.
void x_schedule_timer (x_notify *timer, Uint16 ticks)
OS timer configuration request.
void x_delete_timer (x_notify *timer)
OS timer delete request.
void x_task_send_irq_sync (x_task_id task_id)
OS interrupt notification timer.
Uint16 x_tick (void)
OS time function.
Variables
x_system_t x_system
OS data.
x_system_volatile_t x_systemv
OS volatile data.
Detailed Description
Simple event based operating system.
Definition in file sys_eventx.c.
Data Structure Documentation
struct x_module_info_t
Task descrtiption data structure.
Definition at line 58 of file sys_eventx.c.
Data Fields
x_notify_fn
notify_fn
Task notification function.
x_task_fn
task_fn
Task fevent unction.
const char
task_name[10]
Task name.
struct x_system_t
OS internal data strucutre.
Definition at line 71 of file sys_eventx.c.
Data Fields
x_event *
event_queue
Event queue.
int
sys_tick
Last processed system tick.
x_notify
timer_queue
Timer queue.
Uint8
x_module_count
Total moduilkes count.
x_module_info_t
x_module_info[X_MAX_MODULE]
Modules info.
struct x_system_volatile_t
OS volatile internal data strucutre.
Definition at line 93 of file sys_eventx.c.
Data Fields
Uint16
irq_tick
System timer tick.
Uint16
x_irq_mask
Bitcoded module interrupt notifications.
Macro Definition Documentation
#define X_MAX_MODULE
Max amount of tasks.
Definition at line 52 of file sys_eventx.c.
Referenced by x_init_task(), and x_task_send_irq_sync().
Function Documentation
void __attribute__ ((__interrupt__, auto_psv))
OS timer tick function.
Serial port transmit interrupt. req REQ-8a: `Read the sensor inputs ` Sensors and inputs are read and filtered.
Definition at line 115 of file sys_eventx.c.
References logv_t::data_tx_on_progress, FALSE, x_system_volatile_t::irq_tick, logv, SET_CPU_IPL, TRANSMIT_BUFFER_SIZE, serial_data_t::tx_buff_head, serial_data_t::tx_buff_tail, serial_data_t::tx_buffer, and serial_data_t::tx_cnt.
{
    x_systemv.irq_tick++;
    IFS1bits.T5IF = 0;
    SET_CPU_IPL(6);
   
}
void x_delete_timer (x_notify * timer)
OS timer delete request.
Parameters
timer Pointer to timer object
If timer is running, it is taken away from active timer queue.
Definition at line 482 of file sys_eventx.c.
References x_notify::active, ASSERT, x_notify::link, and x_system_t::timer_queue.
Referenced by algorithm_taskx(), ir_sen_notifyx(), light_sen_notifyx(), mfield_x_sen_notifyx(), mfield_z_sen_notifyx(), and uv_sen_notifyx().
{
    x_notify * timer_curr;
    if(timer->active == 1)
    {
        timer_curr = &x_system.timer_queue;
        while(timer_curr->link!= NULL)
        {
            if(timer_curr->link == timer)
            {
                // Timer found
                timer_curr->link = (timer_curr->link)->link;
                timer->link = NULL;
                timer->active = 0;
                return;
            }
            timer_curr = timer_curr->link;
        }
        // Does not exist ??
        ASSERT(0);
    }
}
void x_init (void)
OS internal init.
Definition at line 135 of file sys_eventx.c.
References x_system_t::event_queue, FOSC_CPU, x_notify::link, x_system_t::timer_queue, x_system_volatile_t::x_irq_mask, x_system_t::x_module_count, and X_TIMER_TICK.
Referenced by main().
{
    x_system.x_module_count = 0;
    x_system.event_queue = NULL;
    x_system.timer_queue.link = NULL;
    x_systemv.x_irq_mask = 0;
    // Setup system - Timer 1
    
    T5CON = 0; // Clear the register
    T5CONbits.TCS = 0; // Internal clock Fosc/4
    T5CONbits.TCKPS = 1; // 1:8 prescaling
    PR5 = ((FOSC_CPU/2)/8)/X_TIMER_TICK;
    
    
    IPC7bits.T5IP = 0x06; // Set Timer5 Interrupt Priority Level
    IFS1bits.T5IF = 0; //Clear the Timer1 Interrupt Flag
    IEC1bits.T5IE = 1; //Enable Timer1 Interrupt Service Routine
    T5CONbits.TON = 1; //Start Timer 1
}
void x_init_task (x_task_fn task_fn, x_notify_fn notify_fn, x_task_id * pHandle_id, const char * task_name)
OS task init function.
Parameters
task_fn Module task event processing function
notify_fn Module task notification processing function
pHandle_id Pointer to module handle variable
task_name Task name (null terminated string)
Definition at line 173 of file sys_eventx.c.
References ASSERT, x_module_info_t::notify_fn, x_module_info_t::task_fn, x_module_info_t::task_name, X_MAX_MODULE, x_system_t::x_module_count, and x_system_t::x_module_info.
Referenced by main().
{
    if(x_system.x_module_count < X_MAX_MODULE)
    {
        x_system.x_module_info[x_system.
      x_module_count].task_fn = task_fn;
        x_system.x_module_info[x_system.
      x_module_count].notify_fn = notify_fn;
        strncpy((char*)x_system.x_module_info[x_system.
      x_module_count].task_name,task_name,sizeof(x_system.
      x_module_info[x_system.x_module_count].
      task_name)-1);
        *pHandle_id = x_system.x_module_count++;
    }
    else
    {
        ASSERT(0);
    }
}
void x_loop (void)
OS function which should be called in idle loop.
This function processes events and notifications. Watchdog kick - before executing notification function with interrupt notification
Watchdog kick - before executing notification function with timer notification
Watchdog kick - before executing task event function with event from system queue
Watchdog kick - needed for idle cases
Definition at line 231 of file sys_eventx.c.
References x_notify::active, D_E, D_T, x_system_t::event_queue, IRQ_CTX_T, IRQ_DISABLE, IRQ_ENABLE, x_system_volatile_t::irq_tick, x_event::link, x_notify::link, x_event::message, x_notify::message, x_module_info_t::notify_fn, srv_wdg_kick, x_system_t::sys_tick, x_module_info_t::task_fn, x_event::task_id, x_notify::task_id, x_module_info_t::task_name, x_notify::ticks, x_system_t::timer_queue, x_system_volatile_t::x_irq_mask, x_system_t::x_module_count, x_system_t::x_module_info, X_MSG_IRQ_SYNC, and X_TICK2MS.
Referenced by main().
{
    Uint16 tmp;
    Uint16 delta;
    int ii;
    x_event irq_event;
    x_notify * timer_prev;
    x_notify * timer_run;
    x_event * event;
    x_event * event_run;
    IRQ_CTX_T irq_ctx;
    // Service interrupt sync requests
    irq_event.task_id = -1;
    irq_event.message = X_MSG_IRQ_SYNC;
    do
    {
        IRQ_DISABLE(irq_ctx);
        tmp = x_systemv.x_irq_mask;
        x_systemv.x_irq_mask = 0;
        IRQ_ENABLE(irq_ctx);
        if(tmp != 0)
        {
            for(ii = 0; ii < x_system.x_module_count;ii++)
            {
                if(tmp & (1<<ii))
                {
                    // Kick watchdog
                    srv_wdg_kick();
                    // Execute notification function
                    x_system.x_module_info[ii].task_fn(&irq_event);
                }
            }
        }
    }while(tmp != 0);
    // Service timers
    if(x_systemv.irq_tick != x_system.sys_tick)
    {
        delta = x_systemv.irq_tick - x_system.sys_tick;
        x_system.sys_tick = x_systemv.irq_tick;
        timer_prev = &x_system.timer_queue;
        while(timer_prev != NULL)
        {
            //Scan through all timers
            timer_run = timer_prev->link;
            if(timer_run != NULL)
            {
                if(timer_run->ticks > delta)
                {
                    timer_run->ticks -= delta;
                }
                else
                {
                    timer_run->ticks = 0;
                }
                if(timer_run->ticks == 0)
                {
                    // Remove timer
                    timer_prev->link = timer_run->link;
                    // Launch timer
                    timer_run->link = NULL;
                    timer_run->active = 0;
                    D_T(fprintf(stdout,"Timer Notification time:%u Task name:%s msg:%x\n",
      X_TICK2MS(x_systemv.irq_tick),x_system.
      x_module_info[timer_run->task_id].task_name,timer_run->
      message);)
                    srv_wdg_kick();
                    x_system.x_module_info[timer_run->task_id].notify_fn(timer_run);
                 }
            }
            if(timer_prev->link == NULL)
            {
                break;
            }
            else
            {
                timer_prev = timer_prev->link;
            }
        }
    }
    // Service events
    event = x_system.event_queue;
    while(event != NULL)
    {
        // Send event
        event_run = event;
        // First remove event from queue
        x_system.event_queue = event->link;
        event = event->link;
        // Clean event link (which marks as executed)
        event_run->link = NULL;
        D_E(fprintf(stdout,"sending event time:%u task:%s msg:%x\n",X_TICK2MS(
      x_systemv.irq_tick),x_system.x_module_info[event_run->
      task_id].task_name,event_run->message);)
        srv_wdg_kick();
        x_system.x_module_info[event_run->task_id].task_fn(event_run);
    }
    srv_wdg_kick();
}
void x_schedule_timer (x_notify * timer, Uint16 ticks)
OS timer configuration request.
Parameters
timer Pointer to timer object
ticks Timer timeout in OS ticks
The user is expexted to fill: message,task_id and ticks fields. If the timer is running, the timer period will be updated.
Definition at line 456 of file sys_eventx.c.
References x_notify::active, x_notify::link, x_notify::ticks, and x_system_t::timer_queue.
Referenced by algorithm_taskx(), ir_sen_notifyx(), light_sen_notifyx(), mfield_x_sen_notifyx(), mfield_z_sen_notifyx(), and uv_sen_notifyx().
{
    if(ticks == 0)ticks = 1;
    timer->ticks = ticks;
    if(timer->active == 0)
    {
        // If not linked (already scheduled) - link it
        timer->link = x_system.timer_queue.link;
        x_system.timer_queue.link = timer;
        timer->active = 1;
    }
}
void x_send_event (x_event * event)
OS event scheduling function.
Parameters
in event The user is expexted to fill: message,task_id.
The event will be placed in FIFO queue and send (during OS loop exectuion) to target task event function
Definition at line 381 of file sys_eventx.c.
References D_E, D_P, x_system_t::event_queue, x_event::link, x_event::message, x_event::task_id, x_module_info_t::task_name, and x_system_t::x_module_info.
Referenced by algorithm_notifyx(), ir_sen_notifyx(), light_sen_notifyx(), mfield_x_sen_notifyx(), mfield_z_sen_notifyx(), and uv_sen_notifyx().
{
    x_event * event_next;
    if(x_system.event_queue == NULL)
    {
        x_system.event_queue = event;
        event->link = NULL;
    }
    else
    {
        event_next = x_system.event_queue;
        // Go through all linked events
        while(event_next != NULL)
        {
            if(event_next == event)
            {
                D_E(fprintf(stdout,"Scheduling event :%s msg:%x\n",x_system.
      x_module_info[event->task_id].task_name,event->
      message);)
                D_P(fprintf(stdout,"Event already in queue");)
                
                return;
            }
            if(event_next->link == NULL)
            {
                // No more events - link new one as last
                D_E(fprintf(stdout,"Scheduling new event:%s msg:%x\n",
      x_system.x_module_info[event->task_id].task_name,event->
      message);)
                event_next->link = event;
                event->link = NULL;
                break;
            }
            else
            {
                event_next = event_next->link;
            }
        }
    }
}
void x_send_notify (x_notify * notify)
OS notification processing request.
Parameters
in notify Pointer to OS notification object
The user is expexted to fill message and task_id fields
Definition at line 435 of file sys_eventx.c.
References D_N, x_system_volatile_t::irq_tick, x_notify::message, x_module_info_t::notify_fn, x_notify::task_id, x_module_info_t::task_name, x_system_t::x_module_info, and X_TICK2MS.
Referenced by algorithm_taskx(), ir_sen_taskx(), light_sen_taskx(), mfield_x_sen_taskx(), mfield_z_sen_taskx(), and uv_sen_taskx().
{
    D_N(fprintf(stdout,"Notification time:%u task:%s msg:%x\n",X_TICK2MS(
      x_systemv.irq_tick),x_system.x_module_info[notify->
      task_id].task_name,notify->message);)
    x_system.x_module_info[notify->task_id].notify_fn(notify);
}
void x_start (void)
OS function which starts event scheduling.
Watchdog kick - before each module start
Definition at line 196 of file sys_eventx.c.
References D_I, x_notify::message, x_module_info_t::notify_fn, srv_wdg_kick, x_notify::task_id, x_module_info_t::task_name, x_system_t::x_module_count, x_system_t::x_module_info, and X_NTF_INIT.
Referenced by main().
{
    int jj;
    x_notify ntf;
    ntf.task_id = -1;
    ntf.message = X_NTF_INIT;
    for(jj = 0; jj < x_system.x_module_count;jj++)
    {
        srv_wdg_kick();
        ntf.task_id = jj;
        D_I(fprintf(stdout,"Initalizing module:%s\n",x_system.
      x_module_info[jj].task_name);)
        x_system.x_module_info[jj].notify_fn(&ntf);
    }
}
void x_task_send_irq_sync (x_task_id task_id)
OS interrupt notification timer.
Parameters
task_id Task id to which timer notification should be sent
The receiver will get X_MSG_IRQ_SYNC notification
Definition at line 521 of file sys_eventx.c.
References ASSERT, IRQ_CTX_T, IRQ_DISABLE, IRQ_ENABLE, x_system_volatile_t::x_irq_mask, and X_MAX_MODULE.
Referenced by algorithm_message_arrived_ntf_isr().
{
    IRQ_CTX_T irq_ctx;
    if(task_id < X_MAX_MODULE)
    {
        IRQ_DISABLE(irq_ctx);
        x_systemv.x_irq_mask |= (1<< task_id);
        IRQ_ENABLE(irq_ctx);
    }
    else
    {
        ASSERT(0);
    }
}
Uint16 x_tick (void)
OS time function.
Return values
Returns current system tick counter
Definition at line 549 of file sys_eventx.c.
References x_system_volatile_t::irq_tick.
{
    return x_systemv.irq_tick;
}
Variable Documentation
x_system_t x_system
OS data.
Definition at line 104 of file sys_eventx.c.
x_system_volatile_t x_systemv
OS volatile data.
Definition at line 107 of file sys_eventx.c.