uv_sensor.h File Reference
Data Structures
struct analog_sample_uv_t
struct x_notify_uv_sen_configure
Notification containing module operation configuration details (from Algorithm module) More...
struct x_notify_uv_sen_sv_report
Notification structure from uv_sen module to Algorithm module about supervision result. More...
struct x_notify_uv_sen_configure.message
struct x_notify_uv_sen_sv_report.message
Macros
#define X_NTF_UV_SENSOR_CONFIG (X_NTF_FREE + 16)
Notification from Algorithm module to load data from nov.
#define UV_SEN_GAIN 1
#define UV_SEN_NOISE_DENSITY_LEVEL 0.05
Functions
event_report_t uv_sen_get_status (Uint16 adc_value, Bool save_event)
Supervise the status of the uv sensor.
void uv_sen_taskx (x_event *event)
uv sensor module task function.
void uv_sen_notifyx (x_notify *notify)
uv module notification function.
Variables
x_task_id uv_sen_id
mfield_x_sen module handle
Data Structure Documentation
struct analog_sample_uv_t
Definition at line 23 of file uv_sensor.h.
Data Fields
Uint16
adc_val
Float32
ana_val
struct x_notify_uv_sen_configure
Notification containing module operation configuration details (from Algorithm module)
Definition at line 31 of file uv_sensor.h.
Data Fields
struct x_notify_uv_sen_configure
message
x_notify
notify
struct x_notify_uv_sen_sv_report
Notification structure from uv_sen module to Algorithm module about supervision result.
Definition at line 49 of file uv_sensor.h.
Data Fields
struct x_notify_uv_sen_sv_report
message
x_notify
notify
struct x_notify_uv_sen_configure.message
Definition at line 35 of file uv_sensor.h.
Data Fields
configured_t
configured
module_disturbance_record_t *
disturbance_record
struct x_notify_uv_sen_sv_report.message
Definition at line 53 of file uv_sensor.h.
Data Fields
configured_t
config
sv_error_flags_ut
error_status_flags
Macro Definition Documentation
#define UV_SEN_GAIN 1
Definition at line 16 of file uv_sensor.h.
#define UV_SEN_NOISE_DENSITY_LEVEL 0.05
Definition at line 18 of file uv_sensor.h.
Referenced by uv_sen_get_status().
#define X_NTF_UV_SENSOR_CONFIG (X_NTF_FREE + 16)
Notification from Algorithm module to load data from nov.
Definition at line 12 of file uv_sensor.h.
Referenced by uv_sen_notifyx().
Function Documentation
event_report_t uv_sen_get_status (Uint16 adc_value, Bool save_event)
Supervise the status of the uv sensor.
REQ-1b: "A valid trip is issued, for few handres of microseconds after trip data will be saved at provided location.
Definition at line 302 of file uv_sensor.c.
References __1ST_ORDER_DERIVATIVE, __COMPARE_ZERO, __PROBABLITY, configured_t::amp_treshold, ASSERT, pre_act_record_buffer_t::buffer, state_data_light_t::change_per_time, uv_sen_data_t::configured, module_status_t::current, data_non_volatile, logv_t::data_tx_on_progress, configured_t::dfdt_treshold_impulse, configured_t::dfdt_treshold_max, configured_t::dfdt_treshold_min, uv_sen_data_t::disturbance_record, logv_t::disturbance_record, pre_act_record_buffer_t::elapsed, EMU_MODE_DATA_LENGTH, module_disturbance_record_t::event_data, module_disturbance_record_t::event_positive_cnt, FALSE, event_report_t::fields, pre_act_record_buffer_t::head, HOT, logv, configured_t::min_number_of_observation, uv_sen_data_t::module_status, module_disturbance_record_t::observation_cnt, module_disturbance_record_t::post_act_data, POST_ACT_RECORD_BUFF_SIZE, module_disturbance_record_t::pre_act_data, PRE_ACT_RECORD_BUFF_SIZE, module_status_t::previous, configured_t::probablity_treshold_max, configured_t::probablity_treshold_min, module_status_t::projected, state_data_light_t::signal_level, state_data_light_t::slop_polarity, state_data_light_t::state, STATE_0, STATE_1, STATE_2, STATE_3, pre_act_record_buffer_t::tail, logv_t::tick, TRUE, UV_SEN_NOISE_DENSITY_LEVEL, and logv_t::wr.
Referenced by __attribute__().
void uv_sen_notifyx (x_notify * notify)
uv module notification function.
Parameters
in notify - system distributed notification
Definition at line 141 of file uv_sensor.c.
References ASSERT, uv_sen_data_t::configured, uv_sen_data_t::disturbance_record, configured_t::element_status_sv_en, sv_error_flags_ut::flags_all, x_notify_uv_sen_configure::message, x_notify::message, uv_sen_data_t::module_status, module_status_t::projected, SCAN_FREQ, uv_sen_data_t::sv_errors_flags, uv_sen_data_t::sv_task_event, uv_sen_data_t::sv_timer_ntf, SV_TIMER_PERIOD, configured_t::sys_freq, x_delete_timer(), X_MS2TICK, X_NTF_CLR_ALARM_UV_SEN, X_NTF_INIT, X_NTF_UV_SENSOR_CONFIG, X_NTF_UV_SENSOR_SV_TIMER, x_schedule_timer(), and x_send_event().
Referenced by main().
{
    switch(notify->message)
    {
        case X_NTF_INIT:
        {
            uv_sen_init();
        }break;
        case X_NTF_UV_SENSOR_CONFIG:
        {
            // configuration details from algorithm module
            x_notify_uv_sen_configure * notify_configure = (
      x_notify_uv_sen_configure *)notify;
            uv_sen_data.configured = notify_configure->
      message.configured;
            uv_sen_data.disturbance_record = notify_configure->
      message.disturbance_record;
           uv_sen_data.module_status.projected.angular_freq =
      2*PI*uv_sen_data.configured.sys_freq;
           uv_sen_data.module_status.projected.samples_per_period =
      (Uint16)(SCAN_FREQ/(Float32)(uv_sen_data.
      configured.sys_freq));
           uv_sen_data.module_status.projected.samples_per_period_1_2 =
      uv_sen_data.module_status.projected.samples_per_period/2;
           uv_sen_data.module_status.projected.samples_per_period_1_4 =
      uv_sen_data.module_status.projected.samples_per_period/4;
           uv_sen_data.module_status.projected.samples_per_period_1_8 =
      uv_sen_data.module_status.projected.samples_per_period/8;
            // Clear supervison state (so errors will be reported if module have internal error)
          uv_sen_data.sv_errors_flags.flags_all = 0;
          x_delete_timer(&uv_sen_data.sv_timer_ntf);
          if(uv_sen_data.configured.element_status_sv_en)
          x_schedule_timer(&uv_sen_data.sv_timer_ntf,
      X_MS2TICK(SV_TIMER_PERIOD));
        }break;
        case X_NTF_CLR_ALARM_UV_SEN:
        {
           // Algorithm module alarm reset request
             //uv_sen_data.module_status.current.state = STATE_0;
             uv_sen_mark_false_postives();
             uv_sen_mark_false_postives();
             uv_sen_mark_false_postives();
        }break;
        case X_NTF_UV_SENSOR_SV_TIMER:
        {
           x_send_event(&uv_sen_data.sv_task_event);
        }break;
        default:
        {
            ASSERT(0);
        }
    }
}
void uv_sen_taskx (x_event * event)
uv sensor module task function.
Parameters
in event - system distributed event
Definition at line 69 of file uv_sensor.c.
References configured_t::amp_treshold, ASSERT, uv_sen_data_t::configured, uv_sen_data_t::diagonesis_records, sv_error_flags_ut::flags_all, x_event::message, x_notify_module_sv_status_report_t::message, x_notify_module_sv_status_report_t::notify, diagonesis_records_light_t::signal_history, srv_wdg_kick, uv_sen_data_t::sv_errors_flags, uv_sen_data_t::sv_status_ntf, X_MSG_UV_SENSOR_SV, and x_send_notify().
Referenced by main().
{
    switch(event->message)
    {
        case X_MSG_UV_SENSOR_SV:
        {
            srv_wdg_kick();
            uv_sen_sensor_element_sv_task();
            if(uv_sen_data.diagonesis_records.
      signal_history.amp.total_observation >0)
                uv_sen_data.diagonesis_records.
      signal_history.amp.avg =
                        (uv_sen_data.diagonesis_records.
      signal_history.amp.accumulated/
                        uv_sen_data.diagonesis_records.
      signal_history.amp.total_observation);
            if(uv_sen_data.diagonesis_records.
      signal_history.amp_exceded.total_observation >0){
                uv_sen_data.diagonesis_records.
      signal_history.amp_exceded.avg =
                        (uv_sen_data.diagonesis_records.
      signal_history.amp_exceded.accumulated/
                        uv_sen_data.diagonesis_records.
      signal_history.amp_exceded.total_observation);
                uv_sen_data.diagonesis_records.
      signal_history.th_gap.avg
                    = (uv_sen_data.diagonesis_records.
      signal_history.amp_exceded.avg - uv_sen_data.configured.
      amp_treshold.set_value);
            }
            else
            uv_sen_data.diagonesis_records.
      signal_history.th_gap.avg
                    = (uv_sen_data.diagonesis_records.
      signal_history.amp.avg - uv_sen_data.configured.
      amp_treshold.set_value);
              uv_sen_data.diagonesis_records.
      signal_history.amp.accumulated = 0;
              uv_sen_data.diagonesis_records.
      signal_history.amp.total_observation = 0;
              uv_sen_data.diagonesis_records.
      signal_history.amp_exceded.accumulated = 0;
              uv_sen_data.diagonesis_records.
      signal_history.amp_exceded.total_observation = 0;
             uv_sen_threshold_adjustment_task();
            if((uv_sen_data.sv_errors_flags.flags_all!=0) || (
      uv_sen_data.configured.amp_treshold.adjusted == 1)){
             uv_sen_data.sv_status_ntf.message.error_flags =
      uv_sen_data.sv_errors_flags;
             uv_sen_data.sv_status_ntf.message.config =
      uv_sen_data.configured;
             // Send notification to Algorithm module about detected error
             x_send_notify(&uv_sen_data.sv_status_ntf.
      notify);
             uv_sen_data.sv_errors_flags.flags_all =0;
             uv_sen_data.configured.amp_treshold.adjusted = 0;
            }
        }break;
        default:
        {
            ASSERT(0);
        }
    }
}
Variable Documentation
x_task_id uv_sen_id
mfield_x_sen module handle
Definition at line 23 of file uv_sensor.c.
Referenced by main().