.TH "_module1" 3 "Wed Oct 29 2014" "Version V0.0" "AQ0X" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_module1 \- Algorithm module 
This is main module which controls high level functionality of the sensor
.PP
Algorithm module is topmost module in the firmware\&. It coordinates all other module functions and validates alart reported by other sensor element monitoring modules 
