.TH "services Directory Reference" 3 "Wed Oct 29 2014" "Version V0.0" "AQ0X" \" -*- nroff -*-
.ad l
.nh
.SH NAME
services Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBsrv_hwio\&.c\fP"
.br
.ti -1c
.RI "file \fBsrv_nov\&.c\fP"
.br
.RI "\fILow level NOV support\&. \fP"
.ti -1c
.RI "file \fBsrv_serial\&.c\fP"
.br
.RI "\fISerial port driver\&. \fP"
.ti -1c
.RI "file \fBsrv_spi\&.c\fP"
.br
.RI "\fIspi port driver \fP"
.ti -1c
.RI "file \fBsrv_watchdog\&.c\fP"
.br
.in -1c
