.TH "aq0X Directory Reference" 3 "Wed Oct 29 2014" "Version V0.0" "AQ0X" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aq0X Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBalgorithm\&.c\fP"
.br
.ti -1c
.RI "file \fBanalog_sv_scan\&.c\fP"
.br
.ti -1c
.RI "file \fBir_sensor\&.c\fP"
.br
.RI "\fIModule responsible for ir sensor element supervision\&. \fP"
.ti -1c
.RI "file \fBlight_sensor\&.c\fP"
.br
.RI "\fIModule responsible for light sensor element supervision\&. \fP"
.ti -1c
.RI "file \fBmfield_x_sensor\&.c\fP"
.br
.RI "\fIModule responsible for mfield x axis sensor element supervision\&. \fP"
.ti -1c
.RI "file \fBmfield_y_sensor\&.c\fP"
.br
.ti -1c
.RI "file \fBmfield_z_sensor\&.c\fP"
.br
.RI "\fIModule responsible for mfield x axis sensor element supervision\&. \fP"
.ti -1c
.RI "file \fBuv_sensor\&.c\fP"
.br
.RI "\fIModule responsible for uv sensor element supervision\&. \fP"
.ti -1c
.RI "file \fBversion\&.c\fP"
.br
.RI "\fIPlaceholder for version info\&. \fP"
.in -1c
