.TH "modules Directory Reference" 3 "Wed Oct 29 2014" "Version V0.0" "AQ0X" \" -*- nroff -*-
.ad l
.nh
.SH NAME
modules Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBaq0X\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBgprintf\&.c\fP"
.br
.RI "\fI\fBtfp_vsprintf()\fP - vsnprintf replacement for standard library function ( which takes too much resources) \fP"
.ti -1c
.RI "file \fBmain\&.c\fP"
.br
.RI "\fILow-level startup , calls OS initalization\&. \fP"
.in -1c
