.TH "includes Directory Reference" 3 "Wed Oct 29 2014" "Version V0.0" "AQ0X" \" -*- nroff -*-
.ad l
.nh
.SH NAME
includes Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBaq0X\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBallheaders\&.h\fP"
.br
.RI "\fIAll project header files together so modules can include just this one\&. \fP"
.ti -1c
.RI "file \fBgprintf\&.h\fP"
.br
.RI "\fI\fBtfp_vsprintf()\fP - vsnprintf replacement for standard library function ( which takes too much resources) \fP"
.ti -1c
.RI "file \fBmain\&.h\fP"
.br
.RI "\fIFew useful generic macros\&. \fP"
.ti -1c
.RI "file \fBnov_data\&.h\fP"
.br
.RI "\fIHeader for low level NOV support\&. \fP"
.ti -1c
.RI "file \fBp33EP128MC202\&.h\fP"
.br
.ti -1c
.RI "file \fBp33EP32MC502\&.h\fP"
.br
.ti -1c
.RI "file \fBsrv_hwio\&.h\fP"
.br
.ti -1c
.RI "file \fBsrv_nov\&.h\fP"
.br
.RI "\fIHeader for low level NOV support\&. \fP"
.ti -1c
.RI "file \fBsrv_progmem\&.h\fP"
.br
.ti -1c
.RI "file \fBsrv_serial\&.h\fP"
.br
.RI "\fIHeader for serial port driver\&. \fP"
.ti -1c
.RI "file \fBsrv_spi\&.h\fP"
.br
.RI "\fIHeader for spi port driver\&. \fP"
.ti -1c
.RI "file \fBsrv_watchdog\&.h\fP"
.br
.RI "\fIFile with support for watchdog( for release version) and watchdog tunning (debug/release) \fP"
.ti -1c
.RI "file \fBsys_eventx\&.h\fP"
.br
.RI "\fIOS header file\&. \fP"
.ti -1c
.RI "file \fBSystem\&.h\fP"
.br
.RI "\fIGeneric project defines ( data types, basic hardware setting) \fP"
.in -1c
