.TH "1047744896 Directory Reference" 3 "Wed Oct 29 2014" "Version V0.0" "AQ0X" \" -*- nroff -*-
.ad l
.nh
.SH NAME
1047744896 Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBalgorithm\&.o\&.d\fP"
.br
.ti -1c
.RI "file \fBanalog_sv_scan\&.o\&.d\fP"
.br
.ti -1c
.RI "file \fBir_sensor\&.o\&.d\fP"
.br
.ti -1c
.RI "file \fBmfield_x_sensor\&.o\&.d\fP"
.br
.ti -1c
.RI "file \fBuv_sensor\&.o\&.d\fP"
.br
.in -1c
