.TH "aq0X Directory Reference" 3 "Wed Oct 29 2014" "Version V0.0" "AQ0X" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aq0X Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBalgorithm_prv\&.h\fP"
.br
.RI "\fIPrivate Algorithm module header file\&. \fP"
.ti -1c
.RI "file \fBir_sensor_prv\&.h\fP"
.br
.ti -1c
.RI "file \fBlight_sensor_prv\&.h\fP"
.br
.ti -1c
.RI "file \fBmfield_x_sensor_prv\&.h\fP"
.br
.ti -1c
.RI "file \fBmfield_y_sensor_prv\&.h\fP"
.br
.ti -1c
.RI "file \fBmfield_z_sensor_prv\&.h\fP"
.br
.ti -1c
.RI "file \fBsrv_hwio_prv\&.h\fP"
.br
.ti -1c
.RI "file \fBuv_sensor_prv\&.h\fP"
.br
.in -1c
