.TH "mfield_y_sensor_prv.h" 3 "Wed Oct 29 2014" "Version V0.0" "AQ0X" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mfield_y_sensor_prv.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBmfield_y_sen_data_t\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBX_MSG_MFIELD_SENSOR_SV\fP   (\fBX_MSG_FREE\fP)"
.br
.RI "\fIInternal event message, initiates periodic supervision\&. \fP"
.ti -1c
.RI "#define \fBX_NTF_MFIELD_SENSOR_SV_TIMER\fP   (\fBX_NTF_FREE\fP + 2)"
.br
.RI "\fIInternal supervison timer\&. \fP"
.ti -1c
.RI "#define \fBSV_TIMER_PERIOD\fP   1000"
.br
.RI "\fITimeout\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBFloat32\fP \fBmfield_y_sen_first_order_derivative\fP (\fBInt16\fP final_val, \fBInt16\fP init_val)"
.br
.ti -1c
.RI "\fBBool\fP \fBmfield_y_sen_calc_probablity\fP (\fBUint16\fP event, \fBUint16\fP obs, \fBUint16\fP threshold)"
.br
.ti -1c
.RI "\fBInt8\fP \fBmfield_y_compare\fP (\fBFloat32\fP num, \fBFloat32\fP given_num, \fBFloat32\fP tolerance)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBmfield_y_sen_data_t\fP \fBmfield_y_sen_data\fP"
.br
.in -1c
.SH "Data Structure Documentation"
.PP 
.SH "struct mfield_y_sen_data_t"
.PP 
Definition at line 29 of file mfield_y_sensor_prv\&.h\&.
.PP
\fBData Fields:\fP
.RS 4
\fBconfigured_t\fP \fIconfigured\fP stores user configuration details 
.br
.PP
\fBdiagonesis_records_mfield_t\fP \fIdiagonesis_records\fP holds diagonesis data on the module operation 
.br
.PP
\fBmodule_disturbance_record_t\fP * \fIdisturbance_record\fP disturbance record storage , details starting form the first event detection to the duration of observation record length 
.br
.PP
\fBmodule_status_mfield_t\fP \fImodule_status\fP holds details about the module current state 
.br
.PP
\fBsv_error_flags_ut\fP \fIsv_errors_flags\fP supervission error flags 
.br
.PP
\fBx_notify_mfield_sen_sv_report\fP \fIsv_status_ntf\fP 
.br
.PP
\fBx_event\fP \fIsv_task_event\fP Internal event for processing mfield module suppervission task\&. 
.br
.PP
\fBx_notify\fP \fIsv_timer_ntf\fP Timer notification to initiate mfield module suppervission task\&. 
.br
.PP
.RE
.PP
.SH "Macro Definition Documentation"
.PP 
.SS "#define SV_TIMER_PERIOD   1000"

.PP
Timeout\&. 
.PP
Definition at line 21 of file mfield_y_sensor_prv\&.h\&.
.SS "#define X_MSG_MFIELD_SENSOR_SV   (\fBX_MSG_FREE\fP)"

.PP
Internal event message, initiates periodic supervision\&. 
.PP
Definition at line 14 of file mfield_y_sensor_prv\&.h\&.
.SS "#define X_NTF_MFIELD_SENSOR_SV_TIMER   (\fBX_NTF_FREE\fP + 2)"

.PP
Internal supervison timer\&. 
.PP
Definition at line 17 of file mfield_y_sensor_prv\&.h\&.
.SH "Function Documentation"
.PP 
.SS "\fBInt8\fP mfield_y_compare (\fBFloat32\fPnum, \fBFloat32\fPgiven_num, \fBFloat32\fPtolerance)"

.SS "\fBBool\fP mfield_y_sen_calc_probablity (\fBUint16\fPevent, \fBUint16\fPobs, \fBUint16\fPthreshold)"

.SS "\fBFloat32\fP mfield_y_sen_first_order_derivative (\fBInt16\fPfinal_val, \fBInt16\fPinit_val)"

.SH "Variable Documentation"
.PP 
.SS "\fBmfield_y_sen_data_t\fP mfield_y_sen_data"

.SH "Author"
.PP 
Generated automatically by Doxygen for AQ0X from the source code\&.
