.TH "readme.h" 3 "Wed Oct 29 2014" "Version V0.0" "AQ0X" \" -*- nroff -*-
.ad l
.nh
.SH NAME
readme.h \- 
.PP
Documentation readme file\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Documentation readme file\&. 


.PP
Definition in file \fBreadme\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for AQ0X from the source code\&.
