.TH "srv_progmem.h" 3 "Wed Oct 29 2014" "Version V0.0" "AQ0X" \" -*- nroff -*-
.ad l
.nh
.SH NAME
srv_progmem.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBsrv_progmem_read\fP (char *dest, int size, unsigned int tbl_page, unsigned int tbl_offset)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void srv_progmem_read (char *dest, intsize, unsigned inttbl_page, unsigned inttbl_offset)"

.SH "Author"
.PP 
Generated automatically by Doxygen for AQ0X from the source code\&.
