.TH "version.c" 3 "Wed Oct 29 2014" "Version V0.0" "AQ0X" \" -*- nroff -*-
.ad l
.nh
.SH NAME
version.c \- 
.PP
Placeholder for version info\&.  

.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "const char \fBversion_string\fP [64] = ('PRODUCT=AQ0X-'__DATE__' '__TIME__'\\0')"
.br
.in -1c
.SH "Detailed Description"
.PP 
Placeholder for version info\&. 


.PP
Definition in file \fBversion\&.c\fP\&.
.SH "Variable Documentation"
.PP 
.SS "const char version_string[64] = ('PRODUCT=AQ0X-'__DATE__' '__TIME__'\\0')"

.PP
Definition at line 10 of file version\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for AQ0X from the source code\&.
