srv_nov.c File Reference
Low level NOV support.
#include `..\includes\allheaders.h`
*
#include `..\includes_prv\aq0X\algorithm_prv.h`
*
Functions
Uint16 crc16 (unsigned char *puchMsg, Uint16 usDataLen)
Standard CRC16 routine.
Uint8 nov_init (void)
Reads NOV storage from EEPROM.
Uint8 nov_destroy (Uint8 copy)
Function for NOV testing, destroys NOV CRC.
void nov_store (void)
Writes NOV storage to EEPROM.
void nov_store_device_id (Uint32 id, Uint8 type)
Stores in EEPROM serial number.
Uint32 nov_get_serial_number (void)
Reads from EEPROM device serial number.
Int8 nov_get_device_address (void)
Reads from EEPROM device serial number.
void nov_set_write_enable_latch (Uint8 cmd)
set or reset write enable latch, the proceedure is drived from the information provided in microchip 25XX640A series serial eeprom dataseet.
NOV_STATREG nov_get_status ()
reads status register from EEPROM.
void nov_write_status (Uint8 value)
write EEPROM status register.
Uint8 nov_byte_write (Uint8 data, Uint16 address)
writes a single byte to the specified eeprom address.
Uint8 nov_byte_read (Uint16 address)
reads single from the specified eeprom address.
Uint8 nov_page_cpy (Uint16 page_address, void *src, Uint16 length)
Function transfer data from RAM to EEPROM over spi port.
Uint8 nov_memcpy (Uint16 starting_address, void *dest, Uint16 length)
Standard library memcpy() replacement function to copy data from serial EEPROM to the specified RAM memory address via spi interface.
void nov_set_default (Uint8 overwrite)
Updates internal structures with default factory settings.
Variables
data_non_volatile_t data_non_volatile
EEPROM data storage copy 1.
Uint32 serial_number
Uint8 nov_wr_inprogress
Detailed Description
Low level NOV support.
Definition in file srv_nov.c.
Function Documentation
Uint16 crc16 (unsigned char * puchMsg, Uint16 usDataLen)
Standard CRC16 routine.
Parameters
in puchMsg character stream
in usDataLen stream length
Return values
CRC16 value of given stream
Definition at line 84 of file srv_nov.c.
Referenced by nov_init(), serial_get_command(), and serial_send_response().
{
    Uint8 crc_hi = 0xFF ; /* high byte of CRC initialized */
    Uint8 crc_lo = 0xFF ; /* low byte of CRC initialized */
    int table_index ; /* index into CRC lookup table */
    
    while (usDataLen--)
    {
        table_index = crc_hi ^ *puchMsg++ ; /* calculate the CRC */
        crc_hi = crc_lo ^ table_crc_hi[table_index] ;
        crc_lo = table_crc_lo[table_index] ;
    }
    return (crc_hi << 8 | crc_lo) ;
}
Uint8 nov_byte_read (Uint16 address)
reads single from the specified eeprom address.
Definition at line 633 of file srv_nov.c.
References NOV_CMD_READ, NOV_CMD_WREN, nov_set_write_enable_latch(), spi_put_data(), and SPI_SS_CTRL_LAT.
{
    Uint8 cc;
    nov_set_write_enable_latch(NOV_CMD_WREN);
    SPI_SS_CTRL_LAT = 0;
    cc = spi_put_data(NOV_CMD_READ);
    cc = spi_put_data((address>>8)&0x00ff);
    cc = spi_put_data(address&0x00ff);
    cc = spi_put_data(0);
    SPI_SS_CTRL_LAT = 1;
    return cc;
}
Uint8 nov_byte_write (Uint8 data, Uint16 address)
writes a single byte to the specified eeprom address.
Definition at line 608 of file srv_nov.c.
References NOV_CMD_WRDI, NOV_CMD_WREN, NOV_CMD_WRITE, nov_get_status(), nov_set_write_enable_latch(), spi_put_data(), and SPI_SS_CTRL_LAT.
{
    Uint8 cc;
    nov_set_write_enable_latch(NOV_CMD_WREN);
    SPI_SS_CTRL_LAT = 0;
    cc = spi_put_data(NOV_CMD_WRITE);
    cc = spi_put_data((address>>8)&0x00ff);
    cc = spi_put_data(address&0x00ff);
    cc = spi_put_data(data);
    SPI_SS_CTRL_LAT = 1;
    // wait for completion of previous write operation
    while(nov_get_status().bits.WIP);
    nov_set_write_enable_latch(NOV_CMD_WRDI);
    return 0;
}
Uint8 nov_destroy (Uint8 copy)
Function for NOV testing, destroys NOV CRC.
Parameters
in copy NOV copy index (0 or 1)
Return values
0 if the operation was succesfull
Definition at line 247 of file srv_nov.c.
{
    if(copy == 0)
    {
         nov_store_copy(0,0xDEAD);
    }
    else{
         nov_store_copy(1,0xDEAD);
    }
       
    return 0;
}
Int8 nov_get_device_address (void)
Reads from EEPROM device serial number.
Definition at line 508 of file srv_nov.c.
References NOV_DEVICE_ID_MEM_ADDRESS, and nov_memcpy().
{
    Uint8 tmp[4];
    nov_memcpy(NOV_DEVICE_ID_MEM_ADDRESS,&tmp,sizeof(tmp));
    if(tmp[0] == tmp[1])
    {
        if(tmp[0] != 0xFF || tmp[0] != 0)
        {
            return tmp[0];
        }
    }
    if(tmp[2] == tmp[3])
    {
        if(tmp[2] != 0xFF || tmp[2] != 0)
        {
            return tmp[2];
        }
    }
    return -1;
}
Uint32 nov_get_serial_number (void)
Reads from EEPROM device serial number.
Definition at line 464 of file srv_nov.c.
References nov_memcpy(), and NOV_SERIAL_NUMBER_MEM_ADDRESS.
Referenced by main().
{
    union
    {
        Uint32 tmp32[4];
        Uint8 tmp8[4*sizeof(Uint32)];
    }tmp;
    nov_memcpy(NOV_SERIAL_NUMBER_MEM_ADDRESS,&tmp,sizeof(tmp));
    if(tmp.tmp32[0] == tmp.tmp32[1])
    {
        if(tmp.tmp32[0] != 0xFFFFFFFF || tmp.tmp32[0] != 0)
        {
            return tmp.tmp32[0];
        }
    }
    if(tmp.tmp32[2] == tmp.tmp32[3])
    {
        if(tmp.tmp32[2] != 0xFFFFFFFF || tmp.tmp32[2] != 0)
        {
            return tmp.tmp32[2];
        }
    }
    // backup plan
    return 0;
        
}
NOV_STATREG nov_get_status ()
reads status register from EEPROM.
Definition at line 567 of file srv_nov.c.
References NOV_CMD_RDSR, spi_put_data(), and SPI_SS_CTRL_LAT.
Referenced by nov_byte_write(), nov_page_cpy(), and nov_write_status().
{
    Uint8 cc;
    SPI_SS_CTRL_LAT = 0;
    cc = spi_put_data(NOV_CMD_RDSR);
    cc = spi_put_data(0);
    SPI_SS_CTRL_LAT = 1;
    return (NOV_STATREG)cc;
}
Uint8 nov_init (void)
Reads NOV storage from EEPROM.
Return values
0 if succesfull NOV retrival was performed
Note: emulation mode data may be mode preserved across resets on production verssion. REQ-nov_2a: `CRC checksum protection` CRC16 used.
first NOV copy is invalid
second NOV copy is invalid
Definition at line 159 of file srv_nov.c.
References crc16(), data_non_volatile, data_non_volatile_t, device_data_t, NOV_FIRST_DATA_SET_ADDRESS, nov_memcpy(), and NOV_SECOND_DATA_SET_ADDRESS.
{
    Uint8 result = 1;
    Uint16 crc;
    device_data_t tmp_data;
    Uint16 state = 0;
    memset(&data_non_volatile,0,sizeof(data_non_volatile));
    // Try first copy
    nov_memcpy(NOV_FIRST_DATA_SET_ADDRESS,&
      data_non_volatile,sizeof(data_non_volatile));
    crc = crc16((unsigned char*)&data_non_volatile,offsetof(
      data_non_volatile_t,device_data.configured_data_crc));
    if(crc == data_non_volatile.device_data.configured_data_crc)
    {
     
        // Copy valid
        result = 0;
        state |= 0x01;
    }
    else
    {
        state |= 0x02;
    }
   // Try backup copy
      nov_memcpy(NOV_SECOND_DATA_SET_ADDRESS,&tmp_data,sizeof(tmp_data
      ));
      crc = crc16((unsigned char*)&tmp_data,offsetof(device_data_t,configured_data_crc));
    if(crc == tmp_data.configured_data_crc)
    {
        state |= 0x04;
        if(result != 0)
        {
            state |= 0x08;
            // Only second copy valid - restore first copy configuration data
             memcpy(&data_non_volatile.device_data,&tmp_data,sizeof(
      data_non_volatile.device_data));
             nov_store_copy(0,0);
             result = 0;
        }
    }
    else
    {
        state |= 0x10;
        if(result == 0)
        {
            state |= 0x20;
            // First was valid, second corrupted. Restore second.
             nov_store_copy(1,0);
        }
    }
    return result;
}
Uint8 nov_memcpy (Uint16 starting_address, void * dest, Uint16 length)
Standard library memcpy() replacement function to copy data from serial EEPROM to the specified RAM memory address via spi interface.
Parameters
in starting address of eeprom memory , i.e. to read from
in pointer to the destination object which is in RAM
in length of the data to copy
Definition at line 723 of file srv_nov.c.
References NOV_CHIP_SIZE, NOV_CMD_READ, spi_put_data(), and SPI_SS_CTRL_LAT.
Referenced by nov_get_device_address(), nov_get_serial_number(), and nov_init().
{
    if((NOV_CHIP_SIZE-starting_address) < length)
        return 1;
    Uint8* dst8 = (Uint8*)dest;
    Uint8 cc;
    // Launch transmission
    SPI_SS_CTRL_LAT = 0;
    cc = spi_put_data(NOV_CMD_READ);
    cc = spi_put_data((starting_address>>8)&0x00ff);
    cc = spi_put_data(starting_address&0x00ff);
    while (length > 0)
    {
           *(dst8++) = spi_put_data(0);
           length--;
    }
    SPI_SS_CTRL_LAT =1;
    IFS0bits.SPI1IF = 0; //no need but it's good to clear it
    return 0;
}
Uint8 nov_page_cpy (Uint16 page_address, void * src, Uint16 length)
Function transfer data from RAM to EEPROM over spi port.
Parameters
in pointer to RAM memory address, i.e. to read from
in length of the data (should be less than page size)
in eeprom page address
data can only be written until the end of the eeprom page. the page is either 64 bytes max (refer to datasheet).
Definition at line 663 of file srv_nov.c.
References ASSERT, NOV_CMD_WRDI, NOV_CMD_WREN, NOV_CMD_WRITE, nov_get_status(), NOV_PAGE_SIZE, nov_set_write_enable_latch(), nov_wr_inprogress, spi_put_data(), and SPI_SS_CTRL_LAT.
Referenced by nov_store_device_id().
{
    volatile Uint16 ii =1 ;
    
    while(page_address > ii*NOV_PAGE_SIZE)ii++;
    
    if((ii*NOV_PAGE_SIZE - page_address -1) < length)ASSERT(0); /*page write operations attempts to
       cross page boundary.*/
          
    if(length > ii*NOV_PAGE_SIZE)return 1;
    Uint8* src8 = (Uint8*)src;
    nov_wr_inprogress = 1;
    // Launch transmission
    Uint8 cc;
    nov_set_write_enable_latch(NOV_CMD_WREN);
    SPI_SS_CTRL_LAT = 0;
    cc = spi_put_data(NOV_CMD_WRITE);
    cc = spi_put_data((page_address>>8)&0x00ff);
    cc = spi_put_data(page_address&0x00ff);
    while (length > 0)
    {
           cc = spi_put_data(*(src8++));
           length--;
    }
   
    SPI_SS_CTRL_LAT = 1;
    // wait for completion of previous write operation
    while(nov_get_status().bits.WIP);
    
    nov_set_write_enable_latch(NOV_CMD_WRDI);
    nov_wr_inprogress = 0;
    IFS0bits.SPI1IF = 0; //no need but good to clear
    return 0;
}
void nov_set_default (Uint8 overwrite)
Updates internal structures with default factory settings.
Parameters
set_default_calibration If set to non-zero value, then also analog calibration is overwritten
Note:
Definition at line 760 of file srv_nov.c.
References ADC_RESOLUTION, algorithm_data, algorithm_get_std_deviation(), CONFIG_DEFAULT_FREQ, CONFIG_DEFAULT_IR_LEVEL_MAX, CONFIG_DEFAULT_LUX_LEVEL_MAX, CONFIG_DEFAULT_MIN_INSTALLATION_DISTANCE, CONFIG_DEFAULT_NO_OF_OBSERVATION, CONFIG_DEFAULT_PROBABLITY_MAX, CONFIG_DEFAULT_PROBABLITY_MIN, CONFIG_DEFAULT_RATED_CURRENT, CONFIG_DEFAULT_SHORT_CKT_CURRENT, CONFIG_DEFAULT_UV_LEVEL_MAX, data_non_volatile, DEFAULT_TRIP_CRITERION, algorithm_data_t::diagnosis, FALSE, FAST_TIMER_SAMPLING_RATE, MAX_EVENT_OBSERVATION_LENGTH, NOV_OVERWRITE_ALL, and TRUE.
{
        data_non_volatile.device_data.installation.system_info.freq =
      CONFIG_DEFAULT_FREQ;
        data_non_volatile.device_data.installation.system_info.rated_current =
      CONFIG_DEFAULT_RATED_CURRENT;
        data_non_volatile.device_data.installation.system_info.sh_current =
      CONFIG_DEFAULT_SHORT_CKT_CURRENT;
        data_non_volatile.device_data.installation.system_info.min_distance =
      CONFIG_DEFAULT_MIN_INSTALLATION_DISTANCE;
        data_non_volatile.device_data.installation.options.bits.ir_element_sv_en =
      TRUE;
        data_non_volatile.device_data.installation.options.bits.uv_element_sv_en =
      TRUE;
        data_non_volatile.device_data.installation.options.bits.mfield_element_sv_en =
      TRUE;
        data_non_volatile.device_data.installation.options.bits.threshold_adjust_manual =
      TRUE;
        data_non_volatile.device_data.installation.thresholds.ir_level_max =
      CONFIG_DEFAULT_IR_LEVEL_MAX;
        data_non_volatile.device_data.installation.thresholds.uv_level_max =
      CONFIG_DEFAULT_UV_LEVEL_MAX;
        
        data_non_volatile.device_data.installation.thresholds.lux_level_max =
      CONFIG_DEFAULT_LUX_LEVEL_MAX;
        data_non_volatile.device_data.installation.thresholds.probablity_max =
      CONFIG_DEFAULT_PROBABLITY_MAX;
        data_non_volatile.device_data.installation.thresholds.probablity_min =
      CONFIG_DEFAULT_PROBABLITY_MIN;
        data_non_volatile.device_data.installation.thresholds.min_number_of_observation =
      CONFIG_DEFAULT_NO_OF_OBSERVATION;
        data_non_volatile.device_data.installation.trip_criteria.criterion.all =
      DEFAULT_TRIP_CRITERION;
        
#if(DEVICE == AQ0X_V0)
        data_non_volatile.device_data.installation.trip_criteria.active_modules.bits.ir
              = TRUE;
        data_non_volatile.device_data.installation.trip_criteria.active_modules.bits.uv
              = TRUE;
        data_non_volatile.device_data.installation.trip_criteria.active_modules.bits.
      mfield_x = TRUE;
        #ifdef MFIELD_Y
        data_non_volatile.device_data.installation.trip_criteria.active_modules.bits.
      mfield_y = TRUE;
        #endif
#else
        data_non_volatile.device_data.installation.trip_criteria.active_modules.bits.ir
              = TRUE;
        data_non_volatile.device_data.installation.trip_criteria.active_modules.bits.uv
              = TRUE;
        data_non_volatile.device_data.installation.trip_criteria.active_modules.bits.light
              = FALSE;
        data_non_volatile.device_data.installation.trip_criteria.active_modules.bits.
      mfield_x = TRUE;
        data_non_volatile.device_data.installation.trip_criteria.active_modules.bits.
      mfield_y = TRUE;
#endif
    {
        Uint16 cc;
        Uint16 zero_point_start = (algorithm_data.diagnosis.samples_per_period
      /4);
        Uint16 zero_point_end = zero_point_start + 25;
        memset(&data_non_volatile.device_data.ref_signal,0,sizeof(
      data_non_volatile.device_data.ref_signal));
        for(cc = 0; cc < MAX_EVENT_OBSERVATION_LENGTH;cc++){
        if(!((cc > zero_point_end)&&(cc < zero_point_end)))
        data_non_volatile.device_data.ref_signal.buffer[cc] = abs(cos(2*PI*
      CONFIG_DEFAULT_FREQ*FAST_TIMER_SAMPLING_RATE*cc)*
      ADC_RESOLUTION);
        data_non_volatile.device_data.ref_signal.mean_value +=
      data_non_volatile.device_data.ref_signal.buffer[cc];
        }
          data_non_volatile.device_data.ref_signal.mean_value /=
      MAX_EVENT_OBSERVATION_LENGTH;
          data_non_volatile.device_data.ref_signal.std_deviation =
      algorithm_get_std_deviation(data_non_volatile.device_data.
      ref_signal.buffer
                                                                                               ,
      data_non_volatile.device_data.ref_signal.mean_value
                                                                                               ,
      MAX_EVENT_OBSERVATION_LENGTH);
          data_non_volatile.device_data.ref_signal.valid = 0x0000;
    }
        if(overwrite == NOV_OVERWRITE_ALL)
        {
            //TODO: Calibration data
        }
}
void nov_set_write_enable_latch (Uint8 cmd)
set or reset write enable latch, the proceedure is drived from the information provided in microchip 25XX640A series serial eeprom dataseet.
the function must be called prior to any attempt to write data to the 25XX640A with write enable command. and it's a recommended practice to reset this latch after the wright operation completed.
Definition at line 553 of file srv_nov.c.
References spi_put_data(), and SPI_SS_CTRL_LAT.
Referenced by nov_byte_read(), nov_byte_write(), nov_page_cpy(), and nov_write_status().
{
    Uint8 cc;
    SPI_SS_CTRL_LAT = 0;
    cc = spi_put_data(cmd);
    SPI_SS_CTRL_LAT = 1;
}
void nov_store (void)
Writes NOV storage to EEPROM.
Note: Updates both copies - one after another
Definition at line 397 of file srv_nov.c.
Referenced by algorithm_taskx(), and algorithm_wake().
{
     nov_store_copy(1,0);
     nov_store_copy(0,0);
}
void nov_store_device_id (Uint32 id, Uint8 type)
Stores in EEPROM serial number.
Definition at line 411 of file srv_nov.c.
References DEVICE_ADDRESS, NOV_DEVICE_ID_MEM_ADDRESS, nov_page_cpy(), NOV_SERIAL_NUMBER_MEM_ADDRESS, and SERIAL_NUMBER.
{
    Uint16 nov_address = NOV_DEVICE_ID_MEM_ADDRESS;
    void* data = NULL;
    Uint8 size = 0;
    if(type == SERIAL_NUMBER){
    nov_address = NOV_SERIAL_NUMBER_MEM_ADDRESS;
    union
    {
        Uint32 tmp32[4];
        Uint8 tmp8[4*sizeof(Uint32)];
    }tmp;
    tmp.tmp32[0] = id;
    tmp.tmp32[1] = id;
    tmp.tmp32[2] = id;
    tmp.tmp32[3] = id;
    
    data = &tmp;
    size = sizeof(tmp);
    }else if(type == DEVICE_ADDRESS){
       Uint8 tmp[4];
        tmp[0] = id;
        tmp[1] = id;
        tmp[2] = id;
        tmp[3] = id;
        data = &tmp;
        size = sizeof(tmp);
    }
 
    nov_page_cpy(nov_address,data,size);
    
}
void nov_write_status (Uint8 value)
write EEPROM status register.
Definition at line 586 of file srv_nov.c.
References NOV_CMD_WRDI, NOV_CMD_WREN, NOV_CMD_WRSR, nov_get_status(), nov_set_write_enable_latch(), spi_put_data(), and SPI_SS_CTRL_LAT.
{
    Uint8 cc;
    nov_set_write_enable_latch(NOV_CMD_WREN);
    SPI_SS_CTRL_LAT = 0;
    cc = spi_put_data(NOV_CMD_WRSR);
    cc = spi_put_data(value);
    SPI_SS_CTRL_LAT = 1;
    // wait for completion of previous write operation
    while(nov_get_status().bits.WIP);
    nov_set_write_enable_latch(NOV_CMD_WRDI);
}
Variable Documentation
data_non_volatile_t data_non_volatile
EEPROM data storage copy 1.
Definition at line 16 of file srv_nov.c.
Referenced by __attribute__(), algorithm_notifyx(), algorithm_taskx(), algorithm_wake(), hwio_configure_init(), ir_sen_get_status(), light_sen_get_status(), main(), mfield_x_sen_get_status(), nov_init(), nov_set_default(), and uv_sen_get_status().
Uint8 nov_wr_inprogress
Definition at line 19 of file srv_nov.c.
Referenced by __attribute__(), nov_page_cpy(), and spi_init().
Uint32 serial_number
Definition at line 18 of file srv_nov.c.