ir_sensor.c File Reference
Module responsible for ir sensor element supervision.
#include `..\..\includes\allheaders.h`
*
#include `..\..\includes_prv\aq0X\ir_sensor_prv.h`
*
Functions
void ir_sen_taskx (x_event *event)
ir sensor module task function.
void ir_sen_notifyx (x_notify *notify)
ir module notification function.
Int8 ir_compare (Float32 num1, Float32 num2, Float32 tolerance)
Float32 ir_sen_first_order_derivative (Uint16 final_val, Uint16 init_val)
Claculate first order derivative.
Float32 ir_sen_calc_probablity (Uint16 event, Uint16 obs)
Claculates the event probablity.
event_report_t ir_sen_get_status (Uint16 adc_value, Bool save_event)
Supervise the status of the ir sensor.
Uint8 ir_sen_hif_check (void)
void ir_record_reset (Uint8 type)
Variables
ir_sen_data_t ir_sen_data
Internal ir_sen module data.
x_task_id ir_sen_id
ir_sen module handle
Uint32 ir_event_trigger_timestamp
Detailed Description
Module responsible for ir sensor element supervision.
Definition in file ir_sensor.c.
Function Documentation
Int8 ir_compare (Float32 num1, Float32 num2, Float32 tolerance)
Parameters
Definition at line 215 of file ir_sensor.c.
                                                               {
   Float32 difference = num1 - num2;
     
   if(abs(difference) <= tolerance)
    return 0;
   if(difference > 0/*num1 > num2*/)
    return 1;
  
   if(difference < 0/*num1 < num2*/)
    return -1;
    
   return -2;
}
void ir_record_reset (Uint8 type)
Definition at line 1152 of file ir_sensor.c.
References ir_sen_data_t::configured, ir_sen_data_t::diagonesis_records, HIF, configured_t::hif_diagonesis_records, and diagonesis_records_light_t::signal_history.
Referenced by algorithm_wake().
                                {
    if(type == HIF){
            ir_sen_data.diagonesis_records.
      signal_history.time.itoi_counter.positive_event = 0;
            ir_sen_data.diagonesis_records.
      signal_history.time.itoi_counter.total_observation = 0;
            ir_sen_data.diagonesis_records.
      signal_history.time.ptop_counter.positive_event = 0;
            ir_sen_data.diagonesis_records.
      signal_history.time.ptop_counter.total_observation = 0;
            ir_sen_data.configured.hif_diagonesis_records->head
      = 0;
       }
}
Float32 ir_sen_calc_probablity (Uint16 event, Uint16 obs)
Claculates the event probablity.
Parameters
in event,positive event count value
in obs,total number of observation
Definition at line 251 of file ir_sensor.c.
                                                       {
   
    return (100L*((Float32)event/(Float32)obs));
}
Float32 ir_sen_first_order_derivative (Uint16 final_val, Uint16 init_val)
Claculate first order derivative.
Definition at line 238 of file ir_sensor.c.
                                                                        {
    return ((Float32)final_val-(Float32)init_val);
}
event_report_t ir_sen_get_status (Uint16 adc_value, Bool save_event)
Supervise the status of the ir sensor.
REQ-1b: "A valid trip is issued, for few handres of microseconds, i.e. after trip data will be saved at provided location.
Definition at line 302 of file ir_sensor.c.
References __1ST_ORDER_DERIVATIVE, __COMPARE_ZERO, __PROBABLITY, event_report_t::all, configured_t::amp_treshold, ASSERT, pre_act_record_buffer_t::buffer, state_data_light_t::change_per_time, ir_sen_data_t::configured, module_status_t::current, data_non_volatile, logv_t::data_tx_on_progress, configured_t::dfdt_treshold_impulse, configured_t::dfdt_treshold_max, configured_t::dfdt_treshold_min, ir_sen_data_t::disturbance_record, logv_t::disturbance_record, pre_act_record_buffer_t::elapsed, EMU_MODE_DATA_LENGTH, module_disturbance_record_t::event_data, module_disturbance_record_t::event_positive_cnt, FALSE, event_report_t::fields, pre_act_record_buffer_t::head, HOT, IR_SEN_NOISE_DENSITY_LEVEL, logv, configured_t::min_number_of_observation, ir_sen_data_t::module_status, module_disturbance_record_t::observation_cnt, module_disturbance_record_t::post_act_data, POST_ACT_RECORD_BUFF_SIZE, module_disturbance_record_t::pre_act_data, PRE_ACT_RECORD_BUFF_SIZE, module_status_t::previous, configured_t::probablity_treshold_max, configured_t::probablity_treshold_min, module_status_t::projected, state_data_light_t::signal_level, state_data_light_t::slop_polarity, state_data_light_t::state, STATE_0, STATE_1, STATE_2, STATE_3, pre_act_record_buffer_t::tail, logv_t::tick, TRUE, and logv_t::wr.
Referenced by __attribute__().
Uint8 ir_sen_hif_check (void)
Definition at line 1100 of file ir_sensor.c.
References __COMPARE_U, hif_checklist_t::all, hif_checklist_t::bits, ir_sen_data_t::configured, ir_sen_data_t::diagonesis_records, configured_t::hif_diagonesis_records, PRE_ACT_RECORD_BUFF_SIZE, and diagonesis_records_light_t::signal_history.
Referenced by algorithm_wake().
                            {
    hif_checklist_t result;
    result.all = 0;
    if(ir_sen_data.configured.hif_diagonesis_records->head <
      PRE_ACT_RECORD_BUFF_SIZE)
        return result.all;
    ir_sen_data.configured.hif_diagonesis_records->mean_value /=
      PRE_ACT_RECORD_BUFF_SIZE;
    if(ir_sen_data.diagonesis_records.
      signal_history.time.itoi_counter.total_observation > 0)
    if(__COMPARE_U(
            (
            ir_sen_data.diagonesis_records.
      signal_history.time.itoi_counter.total_observation
            -
            ir_sen_data.diagonesis_records.
      signal_history.time.itoi_counter.positive_event
            )
            ,2
            )==0
           )
        result.bits.itoi = 1;
    if(ir_sen_data.diagonesis_records.
      signal_history.time.ptop_counter.total_observation > 0)
    if(__COMPARE_U(
          (
           ir_sen_data.diagonesis_records.
      signal_history.time.ptop_counter.total_observation
          -
           ir_sen_data.diagonesis_records.
      signal_history.time.ptop_counter.positive_event
          )
         ,0
          )==0
       )
        result.bits.ptop = 1;
    ir_sen_data.diagonesis_records.signal_history.time.
      itoi_counter.positive_event = 0;
    ir_sen_data.diagonesis_records.signal_history.time.
      itoi_counter.total_observation = 0;
    ir_sen_data.diagonesis_records.signal_history.time.
      ptop_counter.positive_event = 0;
    ir_sen_data.diagonesis_records.signal_history.time.
      ptop_counter.total_observation = 0;
    return result.all;
}
void ir_sen_notifyx (x_notify * notify)
ir module notification function.
Parameters
in notify - system distributed notification
Definition at line 141 of file ir_sensor.c.
References ASSERT, ir_sen_data_t::configured, ir_sen_data_t::disturbance_record, configured_t::element_status_sv_en, sv_error_flags_ut::flags_all, x_notify_ir_sen_configure::message, x_notify::message, ir_sen_data_t::module_status, module_status_t::projected, SCAN_FREQ, ir_sen_data_t::sv_errors_flags, ir_sen_data_t::sv_task_event, ir_sen_data_t::sv_timer_ntf, SV_TIMER_PERIOD, configured_t::sys_freq, x_delete_timer(), X_MS2TICK, X_NTF_CLR_ALARM_IR_SEN, X_NTF_INIT, X_NTF_IR_SENSOR_CONFIG, X_NTF_IR_SENSOR_SV_TIMER, x_schedule_timer(), and x_send_event().
Referenced by main().
{
    switch(notify->message)
    {
        case X_NTF_INIT:
        {
            ir_sen_init();
        }break;
        case X_NTF_IR_SENSOR_CONFIG:
        {
            // configuration details from algorithm module
            x_notify_ir_sen_configure * notify_configure = (
      x_notify_ir_sen_configure *)notify;
            ir_sen_data.configured = notify_configure->
      message.configured;
            ir_sen_data.disturbance_record = notify_configure->
      message.disturbance_record;
           ir_sen_data.module_status.projected.angular_freq =
      2*PI*ir_sen_data.configured.sys_freq;
           ir_sen_data.module_status.projected.samples_per_period =
      (Uint16)(SCAN_FREQ/(Float32)(ir_sen_data.
      configured.sys_freq));
           ir_sen_data.module_status.projected.samples_per_period_1_2 =
      ir_sen_data.module_status.projected.samples_per_period/2;
           ir_sen_data.module_status.projected.samples_per_period_1_4 =
      ir_sen_data.module_status.projected.samples_per_period/4;
           ir_sen_data.module_status.projected.samples_per_period_1_8 =
      ir_sen_data.module_status.projected.samples_per_period/8;
            // Clear supervison state (so errors will be reported if module have internal error)
          ir_sen_data.sv_errors_flags.flags_all = 0;
          x_delete_timer(&ir_sen_data.sv_timer_ntf);
          if(ir_sen_data.configured.element_status_sv_en)
          x_schedule_timer(&ir_sen_data.sv_timer_ntf,
      X_MS2TICK(SV_TIMER_PERIOD));
        }break;
         case X_NTF_CLR_ALARM_IR_SEN:
        {
           // Algorithm module alarm reset request
            // ir_sen_data.module_status.current.state = STATE_0;
             ir_sen_mark_false_postives();
             ir_sen_mark_false_postives();
             ir_sen_mark_false_postives();
        }break;
        case X_NTF_IR_SENSOR_SV_TIMER:
        {
           x_send_event(&ir_sen_data.sv_task_event);
        }break;
        default:
        {
            ASSERT(0);
        }
    }
}
void ir_sen_taskx (x_event * event)
ir sensor module task function.
Parameters
in event - system distributed event
Definition at line 69 of file ir_sensor.c.
References configured_t::amp_treshold, ASSERT, ir_sen_data_t::configured, ir_sen_data_t::diagonesis_records, sv_error_flags_ut::flags_all, x_event::message, x_notify_module_sv_status_report_t::message, x_notify_module_sv_status_report_t::notify, diagonesis_records_light_t::signal_history, srv_wdg_kick, ir_sen_data_t::sv_errors_flags, ir_sen_data_t::sv_status_ntf, X_MSG_IR_SENSOR_SV, and x_send_notify().
Referenced by main().
{
    switch(event->message)
    {
        case X_MSG_IR_SENSOR_SV:
        {
            srv_wdg_kick();
            ir_sen_sensor_element_sv_task();
            if(ir_sen_data.diagonesis_records.
      signal_history.amp.total_observation >0)
                ir_sen_data.diagonesis_records.
      signal_history.amp.avg =
                        (ir_sen_data.diagonesis_records.
      signal_history.amp.accumulated/
                        ir_sen_data.diagonesis_records.
      signal_history.amp.total_observation);
            if(ir_sen_data.diagonesis_records.
      signal_history.amp_exceded.total_observation >0){
                ir_sen_data.diagonesis_records.
      signal_history.amp_exceded.avg =
                        (ir_sen_data.diagonesis_records.
      signal_history.amp_exceded.accumulated/
                        ir_sen_data.diagonesis_records.
      signal_history.amp_exceded.total_observation);
                 
                ir_sen_data.diagonesis_records.
      signal_history.th_gap.avg
                    = (ir_sen_data.diagonesis_records.
      signal_history.amp_exceded.avg - ir_sen_data.configured.
      amp_treshold.set_value);
            }
            else
            ir_sen_data.diagonesis_records.
      signal_history.th_gap.avg
                    = (ir_sen_data.diagonesis_records.
      signal_history.amp.avg - ir_sen_data.configured.
      amp_treshold.set_value);
              ir_sen_data.diagonesis_records.
      signal_history.amp.accumulated = 0;
              ir_sen_data.diagonesis_records.
      signal_history.amp.total_observation = 0;
              ir_sen_data.diagonesis_records.
      signal_history.amp_exceded.accumulated = 0;
              ir_sen_data.diagonesis_records.
      signal_history.amp_exceded.total_observation = 0;
           
             ir_sen_threshold_adjustment_task();
            if((ir_sen_data.sv_errors_flags.flags_all!=0) || (
      ir_sen_data.configured.amp_treshold.adjusted == 1)){
             ir_sen_data.sv_status_ntf.message.error_flags =
      ir_sen_data.sv_errors_flags;
             ir_sen_data.sv_status_ntf.message.config =
      ir_sen_data.configured;
             // Send notification to Algorithm module about detected error or about change in threshold
       values
             x_send_notify(&ir_sen_data.sv_status_ntf.
      notify);
             ir_sen_data.sv_errors_flags.flags_all =0;
             ir_sen_data.configured.amp_treshold.adjusted = 0;
            }
        }break;
        default:
        {
            ASSERT(0);
        }
    }
}
Variable Documentation
Uint32 ir_event_trigger_timestamp
Definition at line 26 of file ir_sensor.c.
ir_sen_data_t ir_sen_data
Internal ir_sen module data.
Definition at line 22 of file ir_sensor.c.
x_task_id ir_sen_id
ir_sen module handle
Definition at line 23 of file ir_sensor.c.
Referenced by main().