light_sensor.h File Reference
Data Structures
struct analog_sample_light_t
struct x_notify_light_sen_configure
Notification containing module operation configuration details (from Algorithm module) More...
struct x_notify_light_sen_sv_report
Notification structure from light_sen module to Algorithm module about supervision result. More...
struct x_notify_light_sen_configure.message
struct x_notify_light_sen_sv_report.message
Macros
#define X_NTF_LIGHT_SENSOR_CONFIG (X_NTF_FREE + 13)
Notification from Algorithm module.
#define LIGHT_SEN_GAIN 1
Functions
void light_sen_taskx (x_event *event)
light sensor module task function.
void light_sen_notifyx (x_notify *notify)
light module notification function.
Variables
x_task_id light_sen_id
ir_sen module handle
Data Structure Documentation
struct analog_sample_light_t
Definition at line 20 of file light_sensor.h.
Data Fields
Uint16
adc_val
Float32
ana_val
struct x_notify_light_sen_configure
Notification containing module operation configuration details (from Algorithm module)
Definition at line 31 of file light_sensor.h.
Data Fields
struct x_notify_light_sen_configure
message
x_notify
notify
struct x_notify_light_sen_sv_report
Notification structure from light_sen module to Algorithm module about supervision result.
Definition at line 46 of file light_sensor.h.
Data Fields
struct x_notify_light_sen_sv_report
message
x_notify
notify
struct x_notify_light_sen_configure.message
Definition at line 35 of file light_sensor.h.
Data Fields
configured_t
configured
module_disturbance_record_t *
disturbance_record
struct x_notify_light_sen_sv_report.message
Definition at line 50 of file light_sensor.h.
Data Fields
configured_t
config
sv_error_flags_ut
error_status_flags
Macro Definition Documentation
#define LIGHT_SEN_GAIN 1
Definition at line 18 of file light_sensor.h.
#define X_NTF_LIGHT_SENSOR_CONFIG (X_NTF_FREE + 13)
Notification from Algorithm module.
Definition at line 13 of file light_sensor.h.
Referenced by light_sen_notifyx().
Function Documentation
void light_sen_notifyx (x_notify * notify)
light module notification function.
Parameters
in notify - system distributed notification
Definition at line 106 of file light_sensor.c.
References ASSERT, light_sen_data_t::configured, module_status_t::current, light_sen_data_t::disturbance_record, configured_t::element_status_sv_en, sv_error_flags_ut::flags_all, light_sen_mark_false_postives(), x_notify_light_sen_configure::message, x_notify::message, light_sen_data_t::module_status, state_data_light_t::state, STATE_0, light_sen_data_t::sv_errors_flags, light_sen_data_t::sv_task_event, light_sen_data_t::sv_timer_ntf, SV_TIMER_PERIOD, x_delete_timer(), X_MS2TICK, X_NTF_INIT, X_NTF_LIGHT_SENSOR_CONFIG, X_NTF_LIGHT_SENSOR_SV_TIMER, x_schedule_timer(), and x_send_event().
Referenced by main().
{
    
    switch(notify->message)
    {
        case X_NTF_INIT:
        {
            light_sen_init();
        }break;
        case X_NTF_LIGHT_SENSOR_CONFIG:
        {
            // configuration details from algorithm module
            x_notify_light_sen_configure * notify_configure = (
      x_notify_light_sen_configure *)notify;
           
            light_sen_data.configured = notify_configure->
      message.configured;
            light_sen_data.disturbance_record = notify_configure->
      message.disturbance_record;
            // Clear supervison state (so errors will be reported if module have internal error)
             light_sen_data.sv_errors_flags.
      flags_all = 0;
          x_delete_timer(&light_sen_data.
      sv_timer_ntf);
          if(light_sen_data.configured.
      element_status_sv_en)
          x_schedule_timer(&light_sen_data.
      sv_timer_ntf,X_MS2TICK(SV_TIMER_PERIOD));
        }break;
         case X_NTF_CLR_ALARM:
        {
           // Algorithm module alarm reset request
             light_sen_data.module_status.current.
      state = STATE_0;
             light_sen_mark_false_postives();
        }break;
        
        case X_NTF_LIGHT_SENSOR_SV_TIMER:
        {
           x_send_event(&light_sen_data.sv_task_event);
        }break;
        
       
        default:
        {
            ASSERT(0);
        }
    }
}
void light_sen_taskx (x_event * event)
light sensor module task function.
Parameters
in event - system distributed event
Definition at line 65 of file light_sensor.c.
References ASSERT, sv_error_flags_ut::flags_all, light_sen_false_positive_adjustment_task(), light_sen_sensor_element_sv_task(), x_notify_light_sen_sv_report::message, x_event::message, x_notify_light_sen_sv_report::notify, light_sen_data_t::sv_errors_flags, light_sen_data_t::sv_status_ntf, X_MSG_LIGHT_SENSOR_SV, and x_send_notify().
Referenced by main().
{
    switch(event->message)
    {
    
        case X_MSG_LIGHT_SENSOR_SV:
        {
            light_sen_sensor_element_sv_task();
            light_sen_false_positive_adjustment_task();
            if(light_sen_data.sv_errors_flags.
      flags_all!=0){
             light_sen_data.sv_status_ntf.message.error_status_flags.
      flags_all = light_sen_data.sv_errors_flags.flags_all;
             // Send notification to Algorithm module about detected error
             x_send_notify(&light_sen_data.
      sv_status_ntf.notify);
             light_sen_data.sv_errors_flags.
      flags_all =0;
            }
            
        }break;
      
        
        default:
        {
            ASSERT(0);
        }
    }
}
Variable Documentation
x_task_id light_sen_id
ir_sen module handle
Definition at line 15 of file light_sensor.c.
Referenced by main().