analog_sv_scan.c File Reference
#include `..\..\includes\allheaders.h`
*
#include `..\..\includes_prv\aq0X\algorithm_prv.h`
*
Functions
void __attribute__ ((__interrupt__, auto_psv))
Fast timer interrupt to scan sensor element analog values.
Function Documentation
void __attribute__ ((__interrupt__, auto_psv))
Fast timer interrupt to scan sensor element analog values.
Serial port transmit interrupt.
Processe also delay blocks from concerned modules req REQ-8a: `Read the sensor inputs ` Sensors and inputs are read and filtered.
Definition at line 25 of file analog_sv_scan.c.
References algorithm_data, algorithm_wake(), ANA_INDEX_IR, ANA_INDEX_MFIELD_X, ANA_INDEX_MFIELD_Y, ANA_INDEX_UV, data_non_volatile, algorithm_data_t::diagnosis, DIG_TEST_LED_LAT, EVENT_CLEARED, EVENT_SV_ALARM, HOT, hwio_get_analog(), ir_sen_get_status(), IRQ_CTX_T, IRQ_DISABLE, IRQ_ENABLE, logv, mfield_x_sen_get_status(), mfield_y_sen_get_status(), algorithm_data_t::modules_state_sv, NOV_HOLD_CTRL_LAT, nov_wr_inprogress, SET_CPU_IPL, logv_t::sv_delay, logv_t::tick, logv_t::trip_active, TRUE, and uv_sen_get_status().
{
        
  IRQ_CTX_T irq_ctx;
  IRQ_DISABLE(irq_ctx);
    if(nov_wr_inprogress==TRUE)
        //If nov operation is on progress suspend for a moment
        NOV_HOLD_CTRL_LAT = 0;
  // Increment tick - used as fast timestamp
    logv.tick++;
#if(TEST_MODE)
    //For timing measurements only - prolog
    DIG_TEST_LED_LAT =1;
#endif
    if(data_non_volatile.device_data.installation.trip_criteria.active_modules.bits.ir)
         algorithm_data.modules_state_sv.ir_sen =
      ir_sen_get_status(hwio_get_analog(ANA_INDEX_IR),0);
    if(data_non_volatile.device_data.installation.trip_criteria.active_modules.bits.uv)
          algorithm_data.modules_state_sv.uv_sen =
      uv_sen_get_status(hwio_get_analog(ANA_INDEX_UV),0);
    if(data_non_volatile.device_data.installation.trip_criteria.active_modules.bits.
      mfield_x)
          algorithm_data.modules_state_sv.mfield_x_sen =
      mfield_x_sen_get_status(hwio_get_analog(
      ANA_INDEX_MFIELD_X),0);
  #if(DEVICE == AQ0X_V1)
    if(data_non_volatile.device_data.installation.trip_criteria.active_modules.bits.
      mfield_y)
         algorithm_data.modules_state_sv.mfield_y_sen =
      mfield_y_sen_get_status(hwio_get_analog(
      ANA_INDEX_MFIELD_Y),0);
  #endif
     if(
        (algorithm_data.modules_state_sv.ir_sen.fields.state ==
      HOT)
       || (algorithm_data.modules_state_sv.uv_sen.fields.state ==
      HOT)
       )
       algorithm_wake(EVENT_SV_ALARM);
     else if(logv.trip_active == TRUE)
          algorithm_wake(EVENT_CLEARED);
    
     if(logv.sv_delay.cnt > 0)
         if((--logv.sv_delay.cnt) == 0)
             algorithm_wake(logv.sv_delay.type);
     if(algorithm_data.diagnosis.false_alarm.ir.delay > 0)
        algorithm_data.diagnosis.false_alarm.ir.delay--;
     if(algorithm_data.diagnosis.false_alarm.uv.delay > 0)
        algorithm_data.diagnosis.false_alarm.uv.delay--;
    
     
#if(TEST_MODE)
    //For timing measurements only - prolog
    DIG_TEST_LED_LAT =0;
#endif
     
  
    if((nov_wr_inprogress==1) && (NOV_HOLD_CTRL_LAT == 0))
        //Restart suspended nov operation
    NOV_HOLD_CTRL_LAT = 1;
    IFS0bits.T1IF = 0; // Clear Timer1 Interrupt Flag
    
   IRQ_ENABLE(irq_ctx);
   SET_CPU_IPL(6); // Fix for core interrupt in-interupt issue
}