mfield_y_sensor.c File Reference
#include `..\..\includes\allheaders.h`
*
#include `..\..\includes_prv\aq0X\mfield_x_sensor_prv.h`
*
Functions
void mfield_x_sen_taskx (x_event *event)
mfield_x sensor module task function.
void mfield_x_sen_notifyx (x_notify *notify)
mfield_x module notification function.
Int8 mfield_x_compare (Float32 num1, Float32 num2, Float32 tolerance)
Float32 mfield_x_sen_first_order_derivative (Uint16 final_val, Uint16 init_val)
Claculate first order derivative.
Bool mfield_x_sen_calc_probablity (Uint16 event, Uint16 obs, Uint16 threshold)
Claculates the event probablity.
event_report_t mfield_x_sen_get_status (Uint16 adc_value, Bool save_event)
Supervise the status of the mfield_x sensor.
Uint8 mfield_x_sen_hif_check (void)
Variables
mfield_x_sen_data_t mfield_x_sen_data
Internal mfield_x_sen module data.
x_task_id mfield_x_sen_id
mfield_x_sen module handle
Uint32 mfield_x_event_trigger_timestamp
Function Documentation
Int8 mfield_x_compare (Float32 num1, Float32 num2, Float32 tolerance)
Parameters
Definition at line 209 of file mfield_y_sensor.c.
Referenced by mfield_x_sen_get_status(), and mfield_x_sen_hif_check().
                                                                     {
   Int8 result = -2;
   Float32 difference = num1 - num2;
   if(abs(difference) <= tolerance)
    result = 0;
   if(difference > 0/*num1 > num2*/)
    result = 1;
   if(difference < 0/*num1 < num2*/)
    result = -1;
   return result;
}
Bool mfield_x_sen_calc_probablity (Uint16 event, Uint16 obs, Uint16 threshold)
Claculates the event probablity.
Parameters
in event,positive event count value
in obs,total number of observation
Definition at line 242 of file mfield_y_sensor.c.
References FALSE, and TRUE.
Referenced by mfield_x_sen_get_status().
                                                                           {
    return ((100L*((Float32)event/(Float32)obs)) > threshold)?TRUE:
      FALSE;
}
Float32 mfield_x_sen_first_order_derivative (Uint16 final_val, Uint16 init_val)
Claculate first order derivative.
Definition at line 229 of file mfield_y_sensor.c.
Referenced by mfield_x_sen_get_status().
                                                                              {
    return ((Float32)final_val-(Float32)init_val);
}
event_report_t mfield_x_sen_get_status (Uint16 adc_value, Bool save_event)
Supervise the status of the mfield_x sensor.
function used to identify the measured signal waveformREQ-1b: "A valid trip is issued, for few handres of microseconds after trip data will be saved at provided location.
Definition at line 293 of file mfield_y_sensor.c.
References configured_t::amp_treshold, ASSERT, pre_act_record_buffer_t::buffer, state_data_mfield_t::change_per_time, mfield_x_sen_data_t::configured, module_status_mfield_t::current, data_non_volatile, logv_t::data_tx_on_progress, configured_t::dfdt_treshold_impulse, configured_t::dfdt_treshold_max, mfield_x_sen_data_t::disturbance_record, pre_act_record_buffer_t::elapsed, EMU_MODE_DATA_LENGTH, module_disturbance_record_t::event_data, module_disturbance_record_t::event_positive_cnt, FALSE, event_report_t::fields, pre_act_record_buffer_t::head, HOT, logv, mfield_x_compare(), mfield_x_sen_calc_probablity(), mfield_x_sen_first_order_derivative(), configured_t::min_number_of_observation, mfield_x_sen_data_t::module_status, module_disturbance_record_t::observation_cnt, module_disturbance_record_t::post_act_data, POST_ACT_RECORD_BUFF_SIZE, module_disturbance_record_t::pre_act_data, PRE_ACT_RECORD_BUFF_SIZE, module_status_mfield_t::previous, configured_t::probablity_treshold_max, module_status_mfield_t::projected, state_data_mfield_t::signal_level, state_data_mfield_t::state, STATE_0, STATE_1, STATE_2, STATE_3, pre_act_record_buffer_t::tail, logv_t::tick, logv_t::trip_active, and TRUE.
Referenced by __attribute__().
Uint8 mfield_x_sen_hif_check (void)
Definition at line 984 of file mfield_y_sensor.c.
References mfield_x_sen_data_t::configured, mfield_x_sen_data_t::diagonesis_records, configured_t::hif_diagonesis_records, mfield_x_compare(), PRE_ACT_RECORD_BUFF_SIZE, and diagonesis_records_mfield_t::signal_history.
                                  {
    Uint8 result = 0;
return result;
    if(mfield_x_sen_data.configured.
      hif_diagonesis_records->head < PRE_ACT_RECORD_BUFF_SIZE)
        return result;
    mfield_x_sen_data.configured.
      hif_diagonesis_records->mean_value/=
      PRE_ACT_RECORD_BUFF_SIZE;
    if(mfield_x_sen_data.diagonesis_records.
      signal_history.time.itoi_counter.total_observation > 0)
    if(mfield_x_compare(
            mfield_x_sen_data.diagonesis_records.
      signal_history.time.itoi_counter.positive_event
           ,mfield_x_sen_data.diagonesis_records.
      signal_history.time.itoi_counter.total_observation
           ,1
            )
           )
        result++;
    if(mfield_x_sen_data.diagonesis_records.
      signal_history.time.ptop_counter.total_observation > 0)
    if(mfield_x_compare(
          mfield_x_sen_data.diagonesis_records.
      signal_history.time.ptop_counter.positive_event
         ,mfield_x_sen_data.diagonesis_records.
      signal_history.time.ptop_counter.total_observation
         ,1
          )
       )
        result++;
    mfield_x_sen_data.diagonesis_records.
      signal_history.time.itoi_counter.positive_event = 0;
    mfield_x_sen_data.diagonesis_records.
      signal_history.time.itoi_counter.total_observation = 0;
    mfield_x_sen_data.diagonesis_records.
      signal_history.time.ptop_counter.positive_event = 0;
    mfield_x_sen_data.diagonesis_records.
      signal_history.time.ptop_counter.total_observation = 0;
    return result;
}
void mfield_x_sen_notifyx (x_notify * notify)
mfield_x module notification function.
module notification function.
Parameters
in notify - system distributed notification
Definition at line 138 of file mfield_y_sensor.c.
References ASSERT, mfield_x_sen_data_t::configured, module_status_mfield_t::current, mfield_x_sen_data_t::disturbance_record, configured_t::element_status_sv_en, sv_error_flags_ut::flags_all, x_notify::message, mfield_x_sen_data_t::module_status, module_status_mfield_t::projected, SCAN_FREQ, state_data_mfield_t::state, STATE_0, mfield_x_sen_data_t::sv_errors_flags, mfield_x_sen_data_t::sv_task_event, mfield_x_sen_data_t::sv_timer_ntf, SV_TIMER_PERIOD, configured_t::sys_freq, x_delete_timer(), X_MS2TICK, X_NTF_INIT, X_NTF_MFIELD_X_SENSOR_CONFIG, x_schedule_timer(), and x_send_event().
Referenced by main().
{
    switch(notify->message)
    {
        case X_NTF_INIT:
        {
            mfield_x_sen_init();
        }break;
        case X_NTF_MFIELD_X_SENSOR_CONFIG:
        {
            // configuration details from algorithm module
            x_notify_mfield_x_sen_configure * notify_configure = (x_notify_mfield_x_sen_configure *)notify;
            mfield_x_sen_data.configured = notify_configure->message.configured;
            mfield_x_sen_data.disturbance_record = notify_configure->
      message.disturbance_record;
           mfield_x_sen_data.module_status.
      projected.angular_freq = 2*PI*mfield_x_sen_data.
      configured.sys_freq;
           mfield_x_sen_data.module_status.
      projected.samples_per_one_forth_period = (Uint16)(SCAN_FREQ/(
      Float32)(mfield_x_sen_data.configured.sys_freq));
           mfield_x_sen_data.module_status.
      projected.samples_per_half_period = mfield_x_sen_data.
      module_status.projected.samples_per_one_forth_period/2;
           mfield_x_sen_data.module_status.
      projected.samples_per_period_1_4 = mfield_x_sen_data.
      module_status.projected.samples_per_one_forth_period/4;
            // Clear supervison state (so errors will be reported if module have internal error)
          mfield_x_sen_data.sv_errors_flags.
      flags_all = 0;
          x_delete_timer(&mfield_x_sen_data.
      sv_timer_ntf);
          if(mfield_x_sen_data.configured.
      element_status_sv_en)
          x_schedule_timer(&mfield_x_sen_data.
      sv_timer_ntf,X_MS2TICK(SV_TIMER_PERIOD));
        }break;
         case X_NTF_CLR_ALARM:
        {
           // Algorithm module alarm reset request
             mfield_x_sen_data.module_status.
      current.state = STATE_0;
             mfield_x_sen_mark_false_postives();
        }break;
        case X_NTF_MFIELD_X_SENSOR_SV_TIMER:
        {
           x_send_event(&mfield_x_sen_data.
      sv_task_event);
        }break;
        default:
        {
            ASSERT(0);
        }
    }
}
void mfield_x_sen_taskx (x_event * event)
mfield_x sensor module task function.
module task function.
Parameters
in event - system distributed event
Definition at line 69 of file mfield_y_sensor.c.
References configured_t::amp_treshold, ASSERT, mfield_x_sen_data_t::configured, mfield_x_sen_data_t::diagonesis_records, sv_error_flags_ut::flags_all, x_event::message, x_notify_mfield_sen_sv_report::message, x_notify_mfield_sen_sv_report::notify, diagonesis_records_mfield_t::signal_history, mfield_x_sen_data_t::sv_errors_flags, mfield_x_sen_data_t::sv_status_ntf, X_MSG_MFIELD_SENSOR_SV, and x_send_notify().
Referenced by main().
{
    switch(event->message)
    {
        case X_MSG_MFIELD_SENSOR_SV:
        {
            mfield_x_sen_sensor_element_sv_task();
            if(mfield_x_sen_data.diagonesis_records.
      signal_history.amp.total_observation >0)
                mfield_x_sen_data.diagonesis_records.
      signal_history.amp.avg =
                        mfield_x_sen_data.diagonesis_records.
      signal_history.amp.accumulated/
                        mfield_x_sen_data.diagonesis_records.
      signal_history.amp.total_observation;
            if(mfield_x_sen_data.diagonesis_records.
      signal_history.amp_exceded.total_observation >0){
                mfield_x_sen_data.diagonesis_records.
      signal_history.amp_exceded.avg =
                        mfield_x_sen_data.diagonesis_records.
      signal_history.amp_exceded.accumulated/
                        mfield_x_sen_data.diagonesis_records.
      signal_history.amp_exceded.total_observation;
                mfield_x_sen_data.diagonesis_records.
      signal_history.th_gap.avg
                    = (mfield_x_sen_data.diagonesis_records.
      signal_history.amp_exceded.avg - mfield_x_sen_data.
      configured.amp_treshold.set_value);
            }
            else
            mfield_x_sen_data.diagonesis_records.
      signal_history.th_gap.avg
                    = (mfield_x_sen_data.diagonesis_records.
      signal_history.amp.avg - mfield_x_sen_data.
      configured.amp_treshold.set_value);
              mfield_x_sen_data.diagonesis_records.
      signal_history.amp.accumulated = 0;
              mfield_x_sen_data.diagonesis_records.
      signal_history.amp.total_observation = 0;
              mfield_x_sen_data.diagonesis_records.
      signal_history.amp_exceded.accumulated = 0;
              mfield_x_sen_data.diagonesis_records.
      signal_history.amp_exceded.total_observation = 0;
             mfield_x_sen_threshold_adjustment_task();
            if(mfield_x_sen_data.sv_errors_flags.
      flags_all!=0){
             mfield_x_sen_data.sv_status_ntf.
      message.error_flags = mfield_x_sen_data.sv_errors_flags;
             mfield_x_sen_data.sv_status_ntf.
      message.config = mfield_x_sen_data.configured;
             // Send notification to Algorithm module about detected error
             x_send_notify(&mfield_x_sen_data.
      sv_status_ntf.notify);
             mfield_x_sen_data.sv_errors_flags.
      flags_all =0;
            }
        }break;
        default:
        {
            ASSERT(0);
        }
    }
}
Variable Documentation
Uint32 mfield_x_event_trigger_timestamp
Definition at line 26 of file mfield_y_sensor.c.
mfield_x_sen_data_t mfield_x_sen_data
Internal mfield_x_sen module data.
Definition at line 22 of file mfield_y_sensor.c.
x_task_id mfield_x_sen_id
mfield_x_sen module handle
Definition at line 23 of file mfield_y_sensor.c.
Referenced by main().