gprintf.c File Reference
tfp_vsprintf() - vsnprintf replacement for standard library function (which takes too much resources)
#include `..\includes\gprintf.h`
*
Macros
#define PRINTF_LONG_SUPPORT
#define STATIC
Typedefs
typedef void(* putcf)(void *, char)
Functions
STATIC void uli2a (unsigned long int num, unsigned int base, int uc, char *bf)
STATIC void li2a (long num, char *bf)
STATIC void ui2a (unsigned int num, unsigned int base, int uc, char *bf)
STATIC void i2a (int num, char *bf)
STATIC int a2d (char ch)
STATIC char a2i (char ch, const char **src, int base, int *nump)
STATIC void putchw (void *putp, putcf putf, int n, char z, char *bf)
void tfp_format (void *putp, putcf putf, const char *fmt, va_list va)
STATIC void putcp (void *p, char c)
void tfp_vsprintf (char *s, const char *fmt, va_list va)
Detailed Description
tfp_vsprintf() - vsnprintf replacement for standard library function (which takes too much resources)
Note: LGPL license. Source: http://www.sparetimelabs.com/tinyprintf/index.html
Copyright (C) 2004 Kustaa Nyholm
This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with this library; if not, write to the Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
Definition in file gprintf.c.
Macro Definition Documentation
#define PRINTF_LONG_SUPPORT
Definition at line 38 of file gprintf.c.
#define STATIC
Definition at line 42 of file gprintf.c.
Typedef Documentation
typedef void(* putcf)(void *, char)
Definition at line 34 of file gprintf.c.
Function Documentation
STATIC int a2d (char ch)
Definition at line 104 of file gprintf.c.
Referenced by a2i().
    {
    if (ch>='0' && ch<='9')
        return ch-'0';
    else if (ch>='a' && ch<='f')
        return ch-'a'+10;
    else if (ch>='A' && ch<='F')
        return ch-'A'+10;
    else return -1;
    }
STATIC char a2i (char ch, const char ** src, int base, int * nump)
Definition at line 115 of file gprintf.c.
References a2d().
Referenced by tfp_format().
    {
    const char * p= *src;
    int num=0;
    int digit;
    while ((digit=a2d(ch))>=0) {
        if (digit>base) break;
        num=num*base+digit;
        ch=*p++;
        }
    *src=p;
    *nump=num;
    return ch;
    }
STATIC void i2a (int num, char * bf)
Definition at line 95 of file gprintf.c.
References ui2a().
Referenced by tfp_format().
    {
    if (num<0) {
        num=-num;
        *bf++ = '-';
        }
    ui2a(num,10,0,bf);
    }
STATIC void li2a (long num, char * bf)
Definition at line 66 of file gprintf.c.
References uli2a().
Referenced by tfp_format().
    {
    if (num<0) {
        num=-num;
        *bf++ = '-';
        }
    uli2a(num,10,0,bf);
    }
STATIC void putchw (void * putp, putcf putf, int n, char z, char * bf)
Definition at line 130 of file gprintf.c.
Referenced by tfp_format().
    {
    char fc=z? '0' : ' ';
    char ch;
    char* p=bf;
    while (*p++ && n > 0)
        n--;
    while (n-- > 0)
        putf(putp,fc);
    while ((ch= *bf++))
        putf(putp,ch);
    }
STATIC void putcp (void * p, char c)
Definition at line 223 of file gprintf.c.
Referenced by tfp_vsprintf().
    {
    *(*((char**)p))++ = c;
    }
void tfp_format (void * putp, putcf putf, const char * fmt, va_list va)
Definition at line 143 of file gprintf.c.
References a2i(), i2a(), li2a(), putchw(), ui2a(), and uli2a().
Referenced by tfp_vsprintf().
    {
    char bf[12];
    
    char ch;
    while ((ch=*(fmt++))) {
        if (ch!='%')
            putf(putp,ch);
        else {
            char lz=0;
#ifdef PRINTF_LONG_SUPPORT
            char lng=0;
#endif
            int w=0;
            ch=*(fmt++);
            if (ch=='0') {
                ch=*(fmt++);
                lz=1;
                }
            if (ch>='0' && ch<='9') {
                ch=a2i(ch,&fmt,10,&w);
                }
#ifdef PRINTF_LONG_SUPPORT
            if (ch=='l') {
                ch=*(fmt++);
                lng=1;
            }
#endif
            switch (ch) {
                case 0:
                    goto abort;
                case 'u' : {
#ifdef PRINTF_LONG_SUPPORT
                    if (lng)
                        uli2a(va_arg(va, unsigned long int),10,0,bf);
                    else
#endif
                    ui2a(va_arg(va, unsigned int),10,0,bf);
                    putchw(putp,putf,w,lz,bf);
                    break;
                    }
                case 'd' : {
#ifdef PRINTF_LONG_SUPPORT
                    if (lng)
                        li2a(va_arg(va, unsigned long int),bf);
                    else
#endif
                    i2a(va_arg(va, int),bf);
                    putchw(putp,putf,w,lz,bf);
                    break;
                    }
                case 'x': case 'X' :
#ifdef PRINTF_LONG_SUPPORT
                    if (lng)
                        uli2a(va_arg(va, unsigned long int),16,(ch=='X'),bf);
                    else
#endif
                    ui2a(va_arg(va, unsigned int),16,(ch=='X'),bf);
                    putchw(putp,putf,w,lz,bf);
                    break;
                case 'c' :
                    putf(putp,(char)(va_arg(va, int)));
                    break;
                case 's' :
                    putchw(putp,putf,w,0,va_arg(va, char*));
                    break;
                case '%' :
                    putf(putp,ch);
                default:
                    break;
                }
            }
        }
    abort:;
    }
void tfp_vsprintf (char * s, const char * fmt, va_list va)
Definition at line 230 of file gprintf.c.
References putcp(), and tfp_format().
    {
    tfp_format(&s,putcp,fmt,va);
    putcp(&s,0);
    }
STATIC void ui2a (unsigned int num, unsigned int base, int uc, char * bf)
Definition at line 77 of file gprintf.c.
Referenced by i2a(), and tfp_format().
    {
    int n=0;
    unsigned int d=1;
    while (num/d >= base)
        d*=base;
    while (d!=0) {
        int dgt = num / d;
        num%= d;
        d/=base;
        if (n || dgt>0 || d==0) {
            *bf++ = dgt+(dgt<10 ? '0' : (uc ? 'A' : 'a')-10);
            ++n;
            }
        }
    *bf=0;
    }
STATIC void uli2a (unsigned long int num, unsigned int base, int uc, char * bf)
Definition at line 48 of file gprintf.c.
Referenced by li2a(), and tfp_format().
    {
    int n=0;
    unsigned long int d=1;
    while (num/d >= base)
        d*=base;
    while (d!=0) {
        int dgt = num / d;
        num%=d;
        d/=base;
        if (n || dgt>0|| d==0) {
            *bf++ = dgt+(dgt<10 ? '0' : (uc ? 'A' : 'a')-10);
            ++n;
            }
        }
    *bf=0;
    }