algorithm_prv.h File Reference
Private Algorithm module header file.
Data Structures
struct algorithm_data_t
Algorithm module variables. More...
struct algorithm_data_t.modules_state_sv
module status collected evey 100us interval More...
struct algorithm_data_t.diagnosis
union algorithm_data_t.diagnosis.hif
struct algorithm_data_t.diagnosis.hif.flags
struct algorithm_data_t.diagnosis.false_alarm
struct algorithm_data_t.diagnosis.false_alarm.ir
struct algorithm_data_t.diagnosis.false_alarm.uv
struct algorithm_data_t.diagnosis.false_alarm.mfield_x
union algorithm_data_t.irq_src
struct algorithm_data_t.irq_src.fields
Macros
#define X_NTF_SUPERVISION_TIMER (X_NTF_LAST)
Notification id for supervson timer.
#define X_NTF_INSTALLATION_TIMER (X_NTF_LAST-1)
Notification id for installation timer.
#define X_MSG_WAKE_EVENT (X_MSG_FREE)
Event id for wakeing main task.
#define X_MSG_CONFIGURE_EVENT (X_MSG_FREE+1)
Event id for configuration request.
#define SUPERVISION_TIMER_PERIOD 2000
Supervison timeout - after the timeout SF state is cleared (if all errors disappeared)
#define INSTALLATION_TIMER_PERIOD 3000
Installation timeout -.
#define TYPE_IR_MF 1
#define TYPE_IR_MF_UV 2
#define TEST_MF 3
#define TEST_UV 4
Functions
Float32 algorithm_get_std_deviation (Uint16 *vector, Float32 mean_val, Uint16 SIZE)
Bool algorithm_signal_proportionality (Uint16 *vector1, Uint16 *vector2, Uint16 SIZE)
The function calculate the relation between the given vectors and standard deviation of the resulting vector to determine the similarity between the two signals.
void algorithm_wake (Uint8 event)
Main processing loop for algorithm module.
void algorithm_sv_scan_timer_init (void)
Low level analog.
Variables
algorithm_data_t algorithm_data
Detailed Description
Private Algorithm module header file.
Definition in file algorithm_prv.h.
Data Structure Documentation
struct algorithm_data_t
Algorithm module variables.
Definition at line 42 of file algorithm_prv.h.
Data Fields
x_notify
clear_alarm_ir
Notification message to clear alarm recognized as false positive.
x_notify
clear_alarm_mfield_x
Notification message to clear alarm recognized as false positive.
x_notify
clear_alarm_uv
Notification message to clear alarm recognized as false positive.
x_event
config_event
Event used to wake main task in case configuration request.
struct algorithm_data_t
diagnosis
x_notify_light_sen_configure
ir_sensor_configure
Notification to be sent for uv sensor modules configuration.
union algorithm_data_t
irq_src
x_notify_light_sen_configure
light_sensor_configure
Notification to be sent for light sensor modules configuration.
x_notify_mfield_sen_configure
mfield_sensor_x_configure
Notification to be sent for mfield_x modules configuration.
struct algorithm_data_t
modules_state_sv
module status collected evey 100us interval
serial_msg_t
serial_msg
x_notify
supervision_timer
Private notification object- supervison timer.
x_notify_light_sen_configure
uv_sensor_configure
Notification to be sent for ir sensor modules configuration.
x_event
wake_event
Event used in notifications for wakeing main task.
struct algorithm_data_t.modules_state_sv
module status collected evey 100us interval
Definition at line 88 of file algorithm_prv.h.
Data Fields
event_report_t
ir_sen
event_report_t
light_sen
event_report_t
mfield_x_sen
event_report_t
mfield_y_sen
event_report_t
uv_sen
struct algorithm_data_t.diagnosis
Definition at line 103 of file algorithm_prv.h.
Data Fields
diagnosis
false_alarm
diagnosis
hif
hif_checklist_t
hif_checklist
Uint16
samples_per_period
union algorithm_data_t.diagnosis.hif
Definition at line 105 of file algorithm_prv.h.
Data Fields
Uint8
all
hif
flags
struct algorithm_data_t.diagnosis.hif.flags
Definition at line 107 of file algorithm_prv.h.
Data Fields
Uint8
processing:1
Uint8
ready:1
Uint8
result:1
struct algorithm_data_t.diagnosis.false_alarm
Definition at line 115 of file algorithm_prv.h.
Data Fields
false_alarm
ir
false_alarm
mfield_x
false_alarm
uv
struct algorithm_data_t.diagnosis.false_alarm.ir
Definition at line 118 of file algorithm_prv.h.
Data Fields
Uint16
armed
Uint16
cnt
Uint16
delay
struct algorithm_data_t.diagnosis.false_alarm.uv
Definition at line 124 of file algorithm_prv.h.
Data Fields
Uint16
armed
Uint16
cnt
Uint16
delay
struct algorithm_data_t.diagnosis.false_alarm.mfield_x
Definition at line 130 of file algorithm_prv.h.
Data Fields
Uint16
armed
Uint16
cnt
Uint16
delay
union algorithm_data_t.irq_src
Definition at line 146 of file algorithm_prv.h.
Data Fields
Uint16
all
irq_src
fields
struct algorithm_data_t.irq_src.fields
Definition at line 148 of file algorithm_prv.h.
Data Fields
Uint16
external:8
Uint16
internal:8
Macro Definition Documentation
#define INSTALLATION_TIMER_PERIOD 3000
Installation timeout -.
Definition at line 29 of file algorithm_prv.h.
#define SUPERVISION_TIMER_PERIOD 2000
Supervison timeout - after the timeout SF state is cleared (if all errors disappeared)
Definition at line 26 of file algorithm_prv.h.
#define TEST_MF 3
Definition at line 35 of file algorithm_prv.h.
#define TEST_UV 4
Definition at line 36 of file algorithm_prv.h.
#define TYPE_IR_MF 1
Definition at line 32 of file algorithm_prv.h.
Referenced by algorithm_wake().
#define TYPE_IR_MF_UV 2
Definition at line 33 of file algorithm_prv.h.
Referenced by algorithm_wake().
#define X_MSG_CONFIGURE_EVENT (X_MSG_FREE+1)
Event id for configuration request.
Definition at line 23 of file algorithm_prv.h.
Referenced by algorithm_taskx().
#define X_MSG_WAKE_EVENT (X_MSG_FREE)
Event id for wakeing main task.
Definition at line 20 of file algorithm_prv.h.
Referenced by algorithm_taskx().
#define X_NTF_INSTALLATION_TIMER (X_NTF_LAST-1)
Notification id for installation timer.
Definition at line 16 of file algorithm_prv.h.
#define X_NTF_SUPERVISION_TIMER (X_NTF_LAST)
Notification id for supervson timer.
Definition at line 13 of file algorithm_prv.h.
Referenced by algorithm_notifyx().
Function Documentation
Float32 algorithm_get_std_deviation (Uint16 * vector, Float32 mean_val, Uint16 SIZE)
Definition at line 96 of file algorithm.c.
Referenced by nov_set_default().
{
    Uint16 cc;
    fractional *vect = (fractional *)vector;
    fractional uval = (fractional)(mean_val);
    Int16 tmp = 0;
    Int32 variance = 0;
  
    for(cc = 0;cc < SIZE ; cc++){
          tmp = ((*(vect+cc)) - uval);
          variance += __builtin_mulss(tmp,tmp);
    }
    Float32 result = sqrt(((Float32)variance)/((Float32)SIZE));
  
    return result;
}
Bool algorithm_signal_proportionality (Uint16 * vector1, Uint16 * vector2, Uint16 SIZE)
The function calculate the relation between the given vectors and standard deviation of the resulting vector to determine the similarity between the two signals.
Definition at line 242 of file algorithm.c.
References FALSE, MAX_EVENT_OBSERVATION_LENGTH, and TRUE.
{
    Float32 vector[MAX_EVENT_OBSERVATION_LENGTH];
    long double sum=0;
    Uint8 cc = 0;
  
    for(cc = 0;cc < SIZE;cc++){
        vector[cc] = (Float32)*(vector1 + cc)/(Float32)*(vector2 + cc);
        sum += vector[cc];
    }
    Float32 mean = sum/SIZE;
    sum = 0;
    for(cc = 0;cc<SIZE;cc++)
        sum += pow((vector[cc]-mean),2);
    Float32 deviation = sum/SIZE;
    if(deviation < 0.1 /*less than 10% deviation*/)
        return TRUE;
    else
        return FALSE;
}
void algorithm_sv_scan_timer_init (void)
Low level analog.
Definition at line 543 of file algorithm.c.
References FOSC_CPU, and SCAN_FREQ.
{
    // Setup fast timer for analog level polling
    T1CONbits.TON = 0; // Disable Timer
    T1CON = 0; // Clear the register
    T1CONbits.TCS = 0; // Internal clock Fosc/4
    T1CONbits.TGATE = 0; // Disable Gated Timer mode
    T1CONbits.TCKPS = 0; // 1:1 prescaling
    TMR1 = 0x00; // Clear timer register
    PR1 = (FOSC_CPU/2)/SCAN_FREQ;
    IPC0bits.T1IP = 0x06; // Set Timer1 Interrupt Priority Level
    IFS0bits.T1IF = 0; // Clear the Timer1 Interrupt Flag
    IEC0bits.T1IE = 1; // Enable Timer1 Interrupt Service Routine
    T1CONbits.TON = 1; //Start Timer 1
}
void algorithm_wake (Uint8 event)
Main processing loop for algorithm module.
Processes events by examining bitfields for various notification reasons. more than 80% correlation is considered as strong similarity
After a valid trip, disturbance recorder data will be will be saved to the memory address allocated for this purpose. The process will take some time depending on the size of the data. Hence, delay counter will be armed so as to transfer the data to non volatile memory when ready.
disturbance record data ready, low priority function will be used, to transfer the data to non volatile memory.
reset emulation trip for comunication purpose
Definition at line 670 of file algorithm.c.
References algorithm_message_arrived_ntf_isr(), ASSERT, data_non_volatile, algorithm_data_t::diagnosis, logv_t::disturbance_record, DR_RECHECK, DR_RECHECK_TIME, srv_hwio_data_t::emulation_mode, EVENT_CLEARED, EVENT_SV_ALARM, FALSE, HIF, HOT, HWIO_ALARM_OFF, HWIO_ALARM_ON, hwio_execute_gpio_task(), ir_record_reset(), ir_sen_hif_check(), IRQ_CTX_T, IRQ_DISABLE, IRQ_DR_READY, IRQ_ENABLE, IRQ_SOURCE_HIF_EVENT, algorithm_data_t::modules_state_sv, nov_store(), srv_hwio_data, STATE_0, logv_t::sv_delay, logv_t::tick, logv_t::trip_active, TRUE, TYPE_IR_MF, TYPE_IR_MF_UV, and logv_t::wr.
Referenced by __attribute__(), and algorithm_notifyx().
{
    Bool result = FALSE;
    if((event == EVENT_SV_ALARM)&&(logv.trip_active ==
      FALSE)){
        if(algorithm_data.modules_state_sv.ir_sen.fields.state ==
      HOT){
        switch(data_non_volatile.device_data.installation.trip_criteria.criterion.all)
        {
                 case TYPE_IR_MF:
                {
                      if(
                          
                           (algorithm_data.modules_state_sv.mfield_x_sen.
      fields.state == HOT)
                            &&
                           (algorithm_data.modules_state_sv.uv_sen.fields.
      state > STATE_0)
                           )
                                result = TRUE;
                       else
                       if(ir_sen_hif_check() > 2)
                        result = TRUE;
                }break;
                 case TYPE_IR_MF_UV:
                {
                   if(
                        (algorithm_data.modules_state_sv.mfield_x_sen.fields.
      state == HOT)
                        &&
                        (algorithm_data.modules_state_sv.uv_sen.fields.state
      == HOT)
                        )
                            result = TRUE;
                       else if((algorithm_data.modules_state_sv.uv_sen.fields
      .state == HOT))
                       {
                                       if(algorithm_data.diagnosis.hif.flags.
      processing == 1){
                                           if(algorithm_data.
      diagnosis.hif.flags.ready == TRUE){
                                                if(algorithm_data.
      diagnosis.hif.flags.result == TRUE)
                                                {
                                                        algorithm_data.
      diagnosis.hif.flags.processing = 0;
                                                        ir_record_reset(
      HIF);
                                                        if((algorithm_data.
      modules_state_sv.uv_sen.fields.state == HOT))
                                                        result = TRUE;
                                                }
                                              else
                                                {
                                                    algorithm_data.
      diagnosis.hif.flags.processing = 0;
                                                    ir_record_reset(
      HIF);
                                                    algorithm_data_mark_false_postives();
                                                }
                                          }
                                     }
                                     else
                                     {
                                               if((ir_sen_hif_check() > 0))
                                               {
                                                   algorithm_data.
      diagnosis.hif.all = 0;
                                                   algorithm_data.
      diagnosis.hif.flags.processing = 1;
                                                       //linear correlation function requires about 200us
       to return,
                                                       //therefore,low priority function will be used to
       execute this procedure
                                                        
      algorithm_message_arrived_ntf_isr(
      IRQ_SOURCE_HIF_EVENT);
                                                        //TODO:clear all timers
                                               }
                                    }
                      }else
                          algorithm_data_mark_false_postives();
                }break;
                 default:
                {
                      if(
                        (algorithm_data.modules_state_sv.mfield_x_sen.fields.
      state == HOT)
                        &&
                        (algorithm_data.modules_state_sv.uv_sen.fields.state
      == HOT)
                        )
                            result = TRUE;
                       else if((algorithm_data.modules_state_sv.uv_sen.fields
      .state == HOT))
                       {
                           algorithm_data.diagnosis.hif_checklist.all =
      ir_sen_hif_check();
                           if((algorithm_data.diagnosis.hif_checklist.all > 0))
                           {
                               IRQ_CTX_T irq_ctx;
                               IRQ_DISABLE(irq_ctx);
                                 Float32 correlation_result = algorithm_liner_correlation(&
      data_non_volatile.disturbance_record.hif_diagonesis_records,
      MAX_EVENT_OBSERVATION_LENGTH);
                               IRQ_ENABLE(irq_ctx);
                               
                               //linear correlation function requires about 236us to return,with 60MIP
                               //therefore,we update global tick by 2 sample time
                               logv.tick +=2;
                                 if(correlation_result >= 80){
                                     result = TRUE;
                                 }
                                 else
                                 if
                                 (
                                 (correlation_result > 50)
                                 &&
                                 algorithm_data.diagnosis.hif_checklist.bits.itoi
                                 &&
                                 algorithm_data.diagnosis.hif_checklist.bits.ptop
                                 )
                                {
                                  result = TRUE;
                                }
                                 else
                                algorithm_data_mark_false_postives();
                               data_non_volatile.disturbance_record.hif_diagonesis_records
      .head = 0;
                               data_non_volatile.disturbance_record.hif_diagonesis_records
      .mean_value = 0;
                           }
                                    
                      }else if(algorithm_data.modules_state_sv.mfield_x_sen.
      fields.state == STATE_0){
                            algorithm_data_mark_false_postives();
                      }
                       
                }break;
        }
        }else if(algorithm_data.modules_state_sv.mfield_x_sen.fields.state ==
       STATE_0){
            if(algorithm_data.modules_state_sv.uv_sen.fields.state ==
      HOT)
            algorithm_data_mark_false_postives();
        }
        
        
        
        if(result == TRUE){
            hwio_execute_gpio_task(HWIO_ALARM_ON);
            logv.trip_active = TRUE;
             logv.disturbance_record.bits.wr = TRUE;
            memset(&algorithm_data.diagnosis.false_alarm,0,sizeof(
      algorithm_data.diagnosis.false_alarm));
            logv.sv_delay.set = TRUE;
            logv.sv_delay.cnt = DR_RECHECK_TIME;
            logv.sv_delay.type = DR_RECHECK;
        }
        
    }else if(event == EVENT_CLEARED){
          hwio_execute_gpio_task(HWIO_ALARM_OFF);
          logv.trip_active = FALSE;
          
    }else if(event == DR_RECHECK){
                    
            if(
              (algorithm_data.modules_state_sv.ir_sen.fields.
      post_act_data_ready == TRUE)
             ){
           data_non_volatile.disturbance_record.new_dr = TRUE;
           logv.disturbance_record.bits.wr = FALSE;
       algorithm_message_arrived_ntf_isr(
      IRQ_DR_READY);
           if(srv_hwio_data.emulation_mode.enabled.all != 0)
               srv_hwio_data.emulation_mode.enabled.all = 0;
       }
       else
          ASSERT(0);
            logv.sv_delay.set = FALSE;
            logv.sv_delay.cnt = 0;
            logv.sv_delay.type = 0;
       
    }else if(event == 0/*internal event*/){
#if(DEVICE == AQ0X_V1)
    if(data_non_volatile.device_data.sv_record.system_error_flags.bits.power_supply ==
      TRUE)
       nov_store();
#endif
      
    }
}
Variable Documentation
algorithm_data_t algorithm_data
Definition at line 33 of file algorithm.c.
Referenced by __attribute__(), and nov_set_default().