mfield_sensor.h File Reference
Data Structures
struct analog_sample_mfield_t
struct calc_tresholds_mfield_t
struct x_notify_mfield_sen_configure
Notification containing module operation configuration details (from Algorithm module) More...
struct x_notify_mfield_sen_sv_report
Notification structure from mfield_sen module to Algorithm module about supervision error. More...
struct state_data_mfield_t
struct module_status_mfield_t
struct diagonesis_records_mfield_t
struct x_notify_mfield_sen_configure.message
struct x_notify_mfield_sen_sv_report.message
struct module_status_mfield_t.projected
struct diagonesis_records_mfield_t.signal_history
struct diagonesis_records_mfield_t.signal_history.amp
struct diagonesis_records_mfield_t.signal_history.amp_exceded
struct diagonesis_records_mfield_t.false_alarm
Counts and stores false positive details, the module uses the information to adjust the threshold values in order to reduce false positive occurrence (i.e. More...
struct diagonesis_records_mfield_t.false_alarm.dfdt_exceded
struct diagonesis_records_mfield_t.false_alarm.amp_exceded
Macros
#define X_NTF_MFIELD_X_SENSOR_CONFIG (X_NTF_FREE + 13)
Notification from Algorithm module configuration data update.
#define MFIELD_SEN_GAIN 0.274
Sensor Sensitivity = 1mV/V/gauss => S(3.3V) = 3.3mV/gauss With gain of 83.3 for full dynamic range +/- 6 gauss produces about a 0.274V/gauss transfer characteristic centered at half supply (1.65 volts).
#define MFIELD_ADC_QUIESCENT_LEVEL 512
amplifier output at zero magnetic field
#define MFIELD_SEN_NOISE_DENSITY_LEVEL 0
#define REDUCTION_FACTOR 100
#define EXCEDED_AMP_TH 0x00
#define EXCEDED_DFDT_IMPULS 0x02
#define EXCEDED_DFDT_MAX 0x04
#define EXCEDED_DFDT_MIN 0x08
#define SINUSOID 0
#define MIN_ACCEPTABLE_CORRELATION 0.90
#define PRE_ACTIVATION_RECORD_LENGTH_MFIELD 100
#define OBSERVATION_TIME_WINDOW (1/2*FAST_TIMER_SAMPLING_RATE_XU + 100)
Functions
event_report_t mfield_x_sen_get_status (Uint16 adc_value, Bool save_event)
function used to identify the measured signal waveform
event_report_t mfield_y_sen_get_status (Uint16 adc_value, Bool save_event)
void mfield_x_sen_taskx (x_event *event)
module task function.
void mfield_x_sen_notifyx (x_notify *notify)
module notification function.
void mfield_y_sen_taskx (x_event *event)
void mfield_y_sen_notifyx (x_notify *notify)
Variables
x_task_id mfield_x_sen_id
mfield_x_sen module handle
x_task_id mfield_y_sen_id
mfield_y_sen module handle
Data Structure Documentation
struct analog_sample_mfield_t
Definition at line 49 of file mfield_sensor.h.
Data Fields
Int16
adc_val
Float32
calculated_pick
Int8
polarity
struct calc_tresholds_mfield_t
Definition at line 59 of file mfield_sensor.h.
Data Fields
analog_sample_mfield_t
amp_treshold_max
Float32
dl_impulse
Float32
dl_treshold_max
Float32
dl_treshold_min
struct x_notify_mfield_sen_configure
Notification containing module operation configuration details (from Algorithm module)
Definition at line 72 of file mfield_sensor.h.
Data Fields
struct x_notify_mfield_sen_configure
message
x_notify
notify
struct x_notify_mfield_sen_sv_report
Notification structure from mfield_sen module to Algorithm module about supervision error.
Definition at line 88 of file mfield_sensor.h.
Data Fields
struct x_notify_mfield_sen_sv_report
message
x_notify
notify
struct state_data_mfield_t
Definition at line 100 of file mfield_sensor.h.
Data Fields
Float32
change_per_time
Int8
polarity
Int16
signal_level
Uint8
state
struct module_status_mfield_t
Definition at line 106 of file mfield_sensor.h.
Data Fields
state_data_mfield_t
current
state_data_mfield_t
previous
struct module_status_mfield_t
projected
Uint16
time
struct diagonesis_records_mfield_t
Definition at line 128 of file mfield_sensor.h.
Data Fields
struct diagonesis_records_mfield_t
false_alarm
Counts and stores false positive details, the module uses the information to adjust the threshold values in order to reduce false positive occurrence (i.e. if the module is running in automatic adjust mode)
struct diagonesis_records_mfield_t
signal_history
struct x_notify_mfield_sen_configure.message
Definition at line 76 of file mfield_sensor.h.
Data Fields
configured_t
configured
module_disturbance_record_t *
disturbance_record
struct x_notify_mfield_sen_sv_report.message
Definition at line 92 of file mfield_sensor.h.
Data Fields
sv_error_flags_ut
error_status_flags
struct module_status_mfield_t.projected
Definition at line 112 of file mfield_sensor.h.
Data Fields
Float32
amplitude
Float32
angular_freq
Uint16
samples_per_period
Uint16
samples_per_period_1_2
Uint16
samples_per_period_1_4
Uint16
samples_per_period_1_8
Float32
waveform
struct diagonesis_records_mfield_t.signal_history
Definition at line 130 of file mfield_sensor.h.
Data Fields
signal_history
amp
signal_history
amp_exceded
struct diagonesis_records_mfield_t.signal_history.amp
Definition at line 132 of file mfield_sensor.h.
Data Fields
Float32
accumulated
Float32
avg
Uint16
max
Uint16
min
Uint16
total_observation
struct diagonesis_records_mfield_t.signal_history.amp_exceded
Definition at line 143 of file mfield_sensor.h.
Data Fields
Uint32
accumulated
Float32
avg
Uint8
total_observation
struct diagonesis_records_mfield_t.false_alarm
Counts and stores false positive details, the module uses the information to adjust the threshold values in order to reduce false positive occurrence (i.e.
if the module is running in automatic adjust mode)
Definition at line 156 of file mfield_sensor.h.
Data Fields
false_alarm
amp_exceded
false_alarm
dfdt_exceded
struct diagonesis_records_mfield_t.false_alarm.dfdt_exceded
Definition at line 157 of file mfield_sensor.h.
Data Fields
Float32
avg
Uint16
cnt
struct diagonesis_records_mfield_t.false_alarm.amp_exceded
Definition at line 163 of file mfield_sensor.h.
Data Fields
Float32
avg
Uint16
cnt
Macro Definition Documentation
#define EXCEDED_AMP_TH 0x00
Definition at line 36 of file mfield_sensor.h.
Referenced by light_sen_mark_false_postives(), and mfield_z_sen_mark_false_postives().
#define EXCEDED_DFDT_IMPULS 0x02
Definition at line 37 of file mfield_sensor.h.
#define EXCEDED_DFDT_MAX 0x04
Definition at line 38 of file mfield_sensor.h.
#define EXCEDED_DFDT_MIN 0x08
Definition at line 39 of file mfield_sensor.h.
#define MFIELD_ADC_QUIESCENT_LEVEL 512
amplifier output at zero magnetic field
Definition at line 29 of file mfield_sensor.h.
Referenced by mfield_x_sen_get_status().
#define MFIELD_SEN_GAIN 0.274
Sensor Sensitivity = 1mV/V/gauss => S(3.3V) = 3.3mV/gauss With gain of 83.3 for full dynamic range +/- 6 gauss produces about a 0.274V/gauss transfer characteristic centered at half supply (1.65 volts).
Definition at line 24 of file mfield_sensor.h.
#define MFIELD_SEN_NOISE_DENSITY_LEVEL 0
Definition at line 31 of file mfield_sensor.h.
Referenced by mfield_x_sen_get_status().
#define MIN_ACCEPTABLE_CORRELATION 0.90
Definition at line 44 of file mfield_sensor.h.
#define OBSERVATION_TIME_WINDOW (1/2*FAST_TIMER_SAMPLING_RATE_XU + 100)
Definition at line 46 of file mfield_sensor.h.
Referenced by mfield_z_observation_time_window_expired().
#define PRE_ACTIVATION_RECORD_LENGTH_MFIELD 100
Definition at line 45 of file mfield_sensor.h.
#define REDUCTION_FACTOR 100
Definition at line 34 of file mfield_sensor.h.
#define SINUSOID 0
Definition at line 43 of file mfield_sensor.h.
#define X_NTF_MFIELD_X_SENSOR_CONFIG (X_NTF_FREE + 13)
Notification from Algorithm module configuration data update.
Definition at line 11 of file mfield_sensor.h.
Referenced by mfield_x_sen_notifyx().
Function Documentation
event_report_t mfield_x_sen_get_status (Uint16 adc_value, Bool save_event)
function used to identify the measured signal waveform
function supervise the status of the mfield sensor
function used to identify the measured signal waveform req REQ-1b: "when a valid trip is issued,for few handres of microseconds after trip data will be to the provided location.
REQ-1b: "A valid trip is issued, for few handres of microseconds after trip data will be saved at provided location.
Definition at line 276 of file mfield_x_sensor.c.
References __1ST_ORDER_DERIVATIVE, __COMPARE_ZERO, __PROBABLITY, configured_t::amp_treshold, ASSERT, pre_act_record_buffer_t::buffer, state_data_mfield_t::change_per_time, mfield_x_sen_data_t::configured, module_status_mfield_t::current, data_non_volatile, logv_t::data_tx_on_progress, configured_t::dfdt_treshold_impulse, configured_t::dfdt_treshold_max, configured_t::dfdt_treshold_min, mfield_x_sen_data_t::disturbance_record, logv_t::disturbance_record, pre_act_record_buffer_t::elapsed, EMU_MODE_DATA_LENGTH, module_disturbance_record_t::event_data, module_disturbance_record_t::event_positive_cnt, FALSE, event_report_t::fields, pre_act_record_buffer_t::head, HOT, logv, MFIELD_ADC_QUIESCENT_LEVEL, MFIELD_SEN_NOISE_DENSITY_LEVEL, mfield_x_compare(), mfield_x_sen_calc_probablity(), mfield_x_sen_first_order_derivative(), configured_t::min_number_of_observation, mfield_x_sen_data_t::module_status, module_disturbance_record_t::observation_cnt, state_data_mfield_t::polarity, module_disturbance_record_t::post_act_data, POST_ACT_RECORD_BUFF_SIZE, module_disturbance_record_t::pre_act_data, PRE_ACT_RECORD_BUFF_SIZE, module_status_mfield_t::previous, configured_t::probablity_treshold_max, configured_t::probablity_treshold_min, module_status_mfield_t::projected, state_data_mfield_t::signal_level, state_data_mfield_t::state, STATE_0, STATE_1, STATE_2, STATE_3, pre_act_record_buffer_t::tail, logv_t::tick, logv_t::trip_active, TRUE, and logv_t::wr.
Referenced by __attribute__().
void mfield_x_sen_notifyx (x_notify * notify)
module notification function.
Parameters
in notify - system distributed notification
module notification function.
Parameters
in notify - system distributed notification
Definition at line 107 of file mfield_x_sensor.c.
References ASSERT, mfield_x_sen_data_t::configured, module_status_mfield_t::current, mfield_x_sen_data_t::disturbance_record, configured_t::element_status_sv_en, sv_error_flags_ut::flags_all, x_notify::message, x_notify_mfield_sen_configure::message, mfield_x_sen_data_t::module_status, module_status_mfield_t::projected, SCAN_FREQ, state_data_mfield_t::state, STATE_0, mfield_x_sen_data_t::sv_errors_flags, mfield_x_sen_data_t::sv_task_event, mfield_x_sen_data_t::sv_timer_ntf, SV_TIMER_PERIOD, configured_t::sys_freq, x_delete_timer(), X_MS2TICK, X_NTF_CLR_ALARM_MFIELD_SEN, X_NTF_INIT, X_NTF_MFIELD_SENSOR_SV_TIMER, X_NTF_MFIELD_X_SENSOR_CONFIG, x_schedule_timer(), and x_send_event().
Referenced by main().
{
    switch(notify->message)
    {
        case X_NTF_INIT:
        {
            mfield_x_sen_init();
        }break;
        case X_NTF_MFIELD_X_SENSOR_CONFIG:
        {
              // Algorithm module configuration reading
              x_notify_mfield_sen_configure * notify_configure = (
      x_notify_mfield_sen_configure *)notify;
              // Module configuration
              mfield_x_sen_data.configured = notify_configure->
      message.configured;
              mfield_x_sen_data.disturbance_record = notify_configure->
      message.disturbance_record;
              mfield_x_sen_data.module_status.
      projected.angular_freq = 2*PI*mfield_x_sen_data.
      configured.sys_freq;
              mfield_x_sen_data.module_status.
      projected.samples_per_period = (Uint16)(SCAN_FREQ/(
      Float32)(mfield_x_sen_data.configured.sys_freq));
              mfield_x_sen_data.module_status.
      projected.samples_per_period_1_2 = mfield_x_sen_data.
      module_status.projected.samples_per_period/2;
              mfield_x_sen_data.module_status.
      projected.samples_per_period_1_4 = mfield_x_sen_data.
      module_status.projected.samples_per_period/4;
              mfield_x_sen_data.module_status.
      projected.samples_per_period_1_8 = mfield_x_sen_data.
      module_status.projected.samples_per_period/8;
              // Clear supervison state (so errors will be reported if module have internal error)
              mfield_x_sen_data.sv_errors_flags.
      flags_all = 0;
              x_delete_timer(&mfield_x_sen_data.
      sv_timer_ntf);
              if(mfield_x_sen_data.configured.
      element_status_sv_en)
              x_schedule_timer(&mfield_x_sen_data.
      sv_timer_ntf,X_MS2TICK(SV_TIMER_PERIOD));
        }break;
         case X_NTF_CLR_ALARM_MFIELD_SEN:
        {
           // Algorithm module alarm reset request
           // mfield_x_sen_data.module_status.current.state = STATE_0;
             mfield_x_sen_mark_false_postives();
        }break;
        case X_NTF_MFIELD_SENSOR_SV_TIMER:
        {
           x_send_event(&mfield_x_sen_data.
      sv_task_event);
        }break;
        default:
        {
            ASSERT(0);
        }
    }
}
void mfield_x_sen_taskx (x_event * event)
module task function.
Parameters
in event - system distributed event
module task function.
Parameters
in event - system distributed event
Definition at line 71 of file mfield_x_sensor.c.
References configured_t::amp_treshold, ASSERT, mfield_x_sen_data_t::configured, mfield_x_sen_data_t::diagonesis_records, sv_error_flags_ut::flags_all, x_event::message, x_notify_mfield_sen_sv_report::message, x_notify_mfield_sen_sv_report::notify, diagonesis_records_mfield_t::signal_history, srv_wdg_kick, mfield_x_sen_data_t::sv_errors_flags, mfield_x_sen_data_t::sv_status_ntf, X_MSG_MFIELD_SENSOR_SV, and x_send_notify().
Referenced by main().
{
    switch(event->message)
    {
        case X_MSG_MFIELD_SENSOR_SV:
        {
            srv_wdg_kick();
            mfield_x_sen_sensor_element_sv_task();
            if(mfield_x_sen_data.sv_errors_flags.
      flags_all!=0){
             mfield_x_sen_data.sv_status_ntf.
      message.error_status_flags = mfield_x_sen_data.
      sv_errors_flags;
             // Send notification to Algorithm module about error
             x_send_notify(&mfield_x_sen_data.
      sv_status_ntf.notify);
             mfield_x_sen_data.sv_errors_flags.
      flags_all =0;
            }
        }break;
        default:
        {
            ASSERT(0);
        }
    }
}
event_report_t mfield_y_sen_get_status (Uint16 adc_value, Bool save_event)
Referenced by __attribute__().
void mfield_y_sen_notifyx (x_notify * notify)
Referenced by main().
void mfield_y_sen_taskx (x_event * event)
Referenced by main().
Variable Documentation
x_task_id mfield_x_sen_id
mfield_x_sen module handle
Definition at line 24 of file mfield_x_sensor.c.
Referenced by main().
x_task_id mfield_y_sen_id
mfield_y_sen module handle
Referenced by main().