srv_spi.h File Reference
Header for spi port driver.
Data Structures
struct STATREG
union _EEPROMStatus_
Macros
#define POST_SCALER 57600
spi module clk rate post scaler value
#define PRE_SCALER 57600
spi module clk rate pre scaler value
#define SPI_SS_CTRL_LAT LATBbits.LATB12
#define SPI_SS_TRIS TRISBbits.TRISB12
#define SPI_SCK_TRIS TRISBbits.TRISB7
#define SPI_SDO_TRIS TRISBbits.TRISB8
#define SPI_SDO_ANSEL ANSELBbits.ANSB8
#define SPI_SDI_TRIS TRISBbits.TRISB9
Functions
Uint8 spi_put_data (Uint8 data)
send one byte of data and receive one back at the same time
void spi_init (void)
Init function for srv_spi service.
void EEPROMInit (void)
union _EEPROMStatus_ EEPROMReadStatus (void)
void EEPROMWriteByte (unsigned char, unsigned int)
unsigned char EEPROMReadByte (unsigned int)
void EEPROMWriteEnable (void)
void EEPROMWriteDisable (void)
Detailed Description
Header for spi port driver.
Definition in file srv_spi.h.
Data Structure Documentation
struct STATREG
Definition at line 137 of file srv_spi.h.
Data Fields
unsigned
BP0:1
unsigned
BP1:1
unsigned
RESERVED:3
unsigned
WEL:1
unsigned
WIP:1
unsigned
WPEN:1
union _EEPROMStatus_
Definition at line 146 of file srv_spi.h.
Data Fields
struct STATREG
Bits
unsigned char
Char
Macro Definition Documentation
#define POST_SCALER 57600
spi module clk rate post scaler value
Definition at line 14 of file srv_spi.h.
#define PRE_SCALER 57600
spi module clk rate pre scaler value
Definition at line 18 of file srv_spi.h.
#define SPI_SCK_TRIS TRISBbits.TRISB7
Definition at line 113 of file srv_spi.h.
Referenced by spi_init().
#define SPI_SDI_TRIS TRISBbits.TRISB9
Definition at line 118 of file srv_spi.h.
Referenced by spi_init().
#define SPI_SDO_ANSEL ANSELBbits.ANSB8
Definition at line 116 of file srv_spi.h.
Referenced by spi_init().
#define SPI_SDO_TRIS TRISBbits.TRISB8
Definition at line 115 of file srv_spi.h.
Referenced by spi_init().
#define SPI_SS_CTRL_LAT LATBbits.LATB12
Definition at line 110 of file srv_spi.h.
Referenced by nov_byte_read(), nov_byte_write(), nov_get_status(), nov_memcpy(), nov_page_cpy(), nov_set_write_enable_latch(), nov_write_status(), and spi_init().
#define SPI_SS_TRIS TRISBbits.TRISB12
Definition at line 111 of file srv_spi.h.
Referenced by spi_init().
Function Documentation
void EEPROMInit (void)
unsigned char EEPROMReadByte (unsigned int)
union _EEPROMStatus_ EEPROMReadStatus (void)
void EEPROMWriteByte (unsigned char, unsigned int)
void EEPROMWriteDisable (void)
void EEPROMWriteEnable (void)
void spi_init (void)
Init function for srv_spi service.
Definition at line 30 of file srv_spi.c.
References NOV_HOLD_CTRL_LAT, NOV_HOLD_CTRL_TRIS, nov_wr_inprogress, SPI_SCK_TRIS, SPI_SDI_TRIS, SPI_SDO_ANSEL, SPI_SDO_TRIS, SPI_SS_CTRL_LAT, and SPI_SS_TRIS.
Referenced by main().
{
    // setup the SPI1 port
    
            SPI_SCK_TRIS = 0;
            SPI_SDO_TRIS = 0;
            SPI_SDI_TRIS = 1;
            SPI_SS_TRIS = 0;
            SPI_SS_CTRL_LAT = 1;
            SPI_SDO_ANSEL = 0;
            
           NOV_HOLD_CTRL_TRIS = 0;
           NOV_HOLD_CTRL_LAT = 1;
           nov_wr_inprogress = 0;
      //disable SPI module
       SPI1STATbits.SPIEN = 0;
       SPI1STATbits.SPISIDL = 0;
    
// Configure SPI1CON register
    
        IFS0bits.SPI1IF = 0; // Clear the Interrupt flag
        IEC0bits.SPI1IE = 0; // Disable the interrupt
        SPI1CON1bits.MSTEN = 1; //Enable Master mode
        SPI1CON1bits.MODE16 = 0; //Communication is byte-wide
        SPI1CON1bits.CKP = 0; //Idle state for clock is a high level
        SPI1CON1bits.CKE = 1; //Data out on Active to Idle Edge
        SPI1CON1bits.SMP = 0; /*Master mode => Input data is sampled at
                                        the middle of data output time */
        //TODO: Fsck = Fp/(Primary Prescaler * Secondary Prescaler)
        SPI1CON1bits.SPRE = 6; //Set Primary Pre-scalar for 4:1 ratio
        SPI1CON1bits.PPRE = 2; //Set Secondary Pre-scalar for 2:1 ratio
        SPI1CON1bits.DISSDO = 0; //Internal SPI clock is enabled
        SPI1CON1bits.DISSCK = 0; //SDOx pin is controlled by the module
        SPI1CON1bits.SSEN = 0; //SSx pin is not used by the module.
                                         //Pin is controlled by port function
        SPI1CON2 = 0; //Framed SPI modes not used
        SPI1STATbits.SPIROV = 0;
        // Enable SPI module
        SPI1STATbits.SPIEN = 1;
}
Uint8 spi_put_data (Uint8 data)
send one byte of data and receive one back at the same time
Definition at line 97 of file srv_spi.c.
Referenced by nov_byte_read(), nov_byte_write(), nov_get_status(), nov_memcpy(), nov_page_cpy(), nov_set_write_enable_latch(), and nov_write_status().
{
    SPI1BUF = data; // write to buffer for TX
    while(!SPI1STATbits.SPIRBF); // wait for transfer to complete
    return SPI1BUF; // read the received value
}