srv_serial.c File Reference
Serial port driver.
#include `..\includes\allheaders.h`
*
Data Structures
struct serial_data_t
Serial port internal data. More...
Macros
#define BRGVAL ((FCY_CPU/BAUDRATE)/16)-1
Formula for U1BRG register (baudrate control)
#define HEX2VAL(cc) (((cc >= '0') && (cc <= '9')) ? (cc - '0') : (cc - 'A' + 10))
Charcter to hex value conversion.
#define CMD_RESPONSE_MSG_HEADER_SIZE 10
#define DATA_TX_MSG_HEADER_SIZE 21
#define TX_MSG_HEADER_FRAME_CHAR '{'
#define RC_MSG_HEADER_FRAME_CHAR '['
#define ACK_CHAR `06`
Functions
void serial_init (void)
Init function for srv_serial service.
void serial_enable_blocking (int enable)
Init function for srv_serial service.
Uint8 serial_get_command (Uint16 *cmd, Uint8 **argStrPtr, Uint16 *argLength)
Function for retriving serial message.
void serial_get_command_ack (void)
Function which marks serial buffer as processed, so new command can be taken.
Uint8 serial_make8 (Uint8 *buf, Uint16 idx)
Function converting characters to 8 bit value.
Uint16 serial_make16 (Uint8 *buf, Uint16 idx)
Function converting characters to 16 bit value.
void serial_send_response (serial_msg_t msg)
Function sending command responses on serial line.
void serial_send (void *msg, Uint16 length)
Function sending buffers over serial port.
void __attribute__ ((__interrupt__, auto_psv))
Serial port receive interrupt.
Variables
pre_act_record_buffer_t pre_data
volatile serial_data_t serial_data
srv_serial service internal data
Detailed Description
Serial port driver.
Definition in file srv_serial.c.
Data Structure Documentation
struct serial_data_t
Serial port internal data.
Definition at line 28 of file srv_serial.c.
Data Fields
int
blocking_mode
If set, then serial sending is blocking (no data lost) Otherwise, characters which do not fit into buffer are ignored.
Uint16
irq_cnt
Uint8
msg_ready
If set, received message was collected.
Uint8
rc_buffer[RECEIVE_BUFFER_SIZE]
Receive buffer.
Uint16
rc_cnt
Diagnostic counter - received message count.
Uint16
rc_data_length
Recevied message length.
Uint16
tx_buff_head
Transmit buffer head.
Uint16
tx_buff_tail
Transmit buffer tail.
Uint8
tx_buffer[TRANSMIT_BUFFER_SIZE]
Transmit buffer (circular)
Uint16
tx_cnt
Diagnostic counter - transmit message count.
Macro Definition Documentation
#define ACK_CHAR `06`
Definition at line 22 of file srv_serial.c.
#define BRGVAL ((FCY_CPU/BAUDRATE)/16)-1
Formula for U1BRG register (baudrate control)
Definition at line 13 of file srv_serial.c.
Referenced by serial_init().
#define CMD_RESPONSE_MSG_HEADER_SIZE 10
Definition at line 18 of file srv_serial.c.
#define DATA_TX_MSG_HEADER_SIZE 21
Definition at line 19 of file srv_serial.c.
#define HEX2VAL(cc) (((cc >= '0') && (cc <= '9')) ? (cc - '0') : (cc - 'A' + 10))
Charcter to hex value conversion.
Definition at line 16 of file srv_serial.c.
Referenced by serial_make16(), and serial_make8().
#define RC_MSG_HEADER_FRAME_CHAR '['
Definition at line 21 of file srv_serial.c.
#define TX_MSG_HEADER_FRAME_CHAR '{'
Definition at line 20 of file srv_serial.c.
Function Documentation
void __attribute__ ((__interrupt__, auto_psv))
Serial port receive interrupt.
Serial port transmit interrupt.req REQ-8a: `Read the sensor inputs ` Sensors and inputs are read and filtered.
Definition at line 658 of file srv_serial.c.
References algorithm_message_arrived_ntf_isr(), serial_data_t::irq_cnt, IRQ_SOURCE_SERIAL, serial_data_t::msg_ready, serial_data_t::rc_buffer, serial_data_t::rc_data_length, SET_CPU_IPL, and srv_wdg_kick.
{
     
     
    Uint8 cc;
    
    
   srv_wdg_kick();
   
   
  while (U1STAbits.URXDA != 0)
    {
        
        if((U1STAbits.FERR)||(U1STAbits.PERR))
        {
            cc = U1RXREG;
            continue;
        }
     
        cc = U1RXREG;
    
      
        if(serial_data.msg_ready != 0)
        {
            // Ignore messages until the old one is processed
            continue;
        }
        if(serial_data.rc_data_length >= sizeof(
      serial_data.rc_buffer))
        {
            serial_data.rc_data_length = 0;
        }
   
        if(cc == '[')
        {
            serial_data.rc_data_length = 0;
            serial_data.rc_buffer[serial_data.
      rc_data_length++] = cc;
        }
        else if (cc == ']')
        {
            serial_data.rc_buffer[serial_data.
      rc_data_length++] = cc;
            // Full message arrived
            serial_data.msg_ready = 1;
            serial_data.irq_cnt++;
        }
        else
        {
            if (((cc >= '0')&&(cc <= '9')) || ((cc >= 'A')&&(cc <= 'F')) || (cc == ':'))
            {
                serial_data.rc_buffer[serial_data.
      rc_data_length++] = cc;
            }
            else
            {
                serial_data.rc_data_length = 0;
            }
        }
    
    }
    
    // Clear errors
    if(U1STAbits.OERR)
    {
        U1STAbits.OERR = 0;
    }
         
    if((serial_data.msg_ready == 1)&&(serial_data.
      rc_buffer[0]=='['))
         algorithm_message_arrived_ntf_isr(
      IRQ_SOURCE_SERIAL);
           
  
 
    
    IFS0bits.U1RXIF = 0;
    SET_CPU_IPL(7);
}
void serial_enable_blocking (int enable)
Init function for srv_serial service.
Definition at line 219 of file srv_serial.c.
References serial_data_t::blocking_mode.
Referenced by serial_init().
{
        serial_data.blocking_mode = enable;
}
Uint8 serial_get_command (Uint16 * cmd, Uint8 ** argStrPtr, Uint16 * argLength)
Function for retriving serial message.
Parameters
in cmd response command
in,out argStrPtr pointer to be updated with argument buffer
in,out argLength pointer for argument buffer length
Definition at line 263 of file srv_serial.c.
References crc16(), serial_data_t::msg_ready, serial_data_t::rc_buffer, serial_data_t::rc_data_length, serial_get_command_ack(), and serial_make16().
{
    Uint8 result = 1;
    Uint16 crc,calc_crc = 0;
   
    
    if(serial_data.msg_ready != 0)
    {
        // Minimal message - 16 characters
        // [0000:000000:00]
        // 01234567890123
        // 00000000001111
        // Longer messages look like
        // [0000:000000000000000 ... 00000000000:00]
        if(serial_data.rc_data_length >= 14)
        {
            *cmd = serial_make16((Uint8*)serial_data.
      rc_buffer,1);
            if((serial_data.rc_buffer[serial_data.
      rc_data_length-5]=='C') && (serial_data.rc_buffer[
      serial_data.rc_data_length-4]=='C'))
            {
                // Manual mode, "CCCC" charaters instead of checksum
                result = 0;
            }
            else
            {
                
                crc = serial_make16((Uint8*)serial_data.
      rc_buffer,serial_data.rc_data_length-5);
                
           
                calc_crc = crc16((unsigned char*)serial_data.
      rc_buffer,serial_data.rc_data_length-6);
              /*
                for(ii = 0; ii < 11;ii++)
                {
                    calc_crc = calc_crc ^serial_data.rc_buffer[ii];
                }
              */
                if(crc == calc_crc)
                {
                    result = 0;
                }
            }
            *argStrPtr = ((Uint8*)&serial_data.rc_buffer[6]);
            *argLength = serial_data.rc_data_length - 12;
       }
       if(result != 0)
       {
            // Faulty message, internmal ack
            serial_get_command_ack();
       }
    }
    IEC0bits.U1RXIE = 1;
    return result;
}
void serial_get_command_ack (void)
Function which marks serial buffer as processed, so new command can be taken.
Definition at line 343 of file srv_serial.c.
References serial_data_t::msg_ready, and serial_data_t::rc_data_length.
Referenced by serial_get_command(), and serial_init().
{
    IEC0bits.U1RXIE = 0;
    serial_data.rc_data_length = 0;
    serial_data.msg_ready = 0;
    IEC0bits.U1RXIE = 1;
}
void serial_init (void)
Init function for srv_serial service.
Definition at line 159 of file srv_serial.c.
References BRGVAL, FALSE, serial_data_t::rc_data_length, serial_enable_blocking(), serial_get_command_ack(), TRUE, serial_data_t::tx_buff_head, and serial_data_t::tx_buff_tail.
Referenced by main().
{
    //gpio configuration and peripheral mapping procedure
         __builtin_write_OSCCONL(OSCCON & 0xbf);
             TRISBbits.TRISB10 = 1;
             ODCBbits.ODCB11 = 0;
             TRISBbits.TRISB11 = 0;
      
        
             RPOR4bits.RP43R = 1; //TX1
             RPINR18bits.U1RXR = 0x2A;
         __builtin_write_OSCCONL(OSCCON | 0x40);
    U1MODE = 0x0000; //Clear UART1 registers
    U1STA = 0x0000;
    U1MODEbits.UARTEN = 1; //Enable UART1 module
    U1MODEbits.PDSEL = 0; // 8 bits, no parity
    U1MODEbits.STSEL = 0; // 1 stop bit
    U1BRG = BRGVAL; //Load UART1 Baud Rate Generator
    IFS0bits.U1RXIF = 0; //Clear UART1 Receiver Interrupt Flag
    IFS0bits.U1TXIF = 0; //Clear UART1 Transmitter Interrupt Flag
    IEC0bits.U1RXIE = 1; //Enable UART1 Receiver Interrupt
    IEC0bits.U1TXIE = 1; //Enable UART1 Transmitter Interrupt
    U1STAbits.UTXISEL0 = 0; // Interrupt after one TX character is transmitted
    U1STAbits.UTXISEL1 = 0;
    U1STAbits.UTXINV = 0; // U1TX Idle state high
    U1STAbits.URXISEL = 1; //Setup UART1 receiver to interrupt after character received
    IPC2bits.U1RXIP = 0x07;
    
    U1MODEbits.UARTEN = 1; // Enable UART
    serial_enable_transmitter(FALSE);
    
    serial_data.rc_data_length = 0;
    serial_data.tx_buff_head = serial_data.
      tx_buff_tail = 0;
    serial_enable_blocking(TRUE);
    serial_get_command_ack();
}
Uint16 serial_make16 (Uint8 * buf, Uint16 idx)
Function converting characters to 16 bit value.
Parameters
in buf buffer with characters
in idx index to first character of 16 bit hex number string (four charaters used)
Definition at line 381 of file srv_serial.c.
References HEX2VAL.
Referenced by msg_to_mem(), and serial_get_command().
{
    return ((HEX2VAL(buf[idx+0])<<12)|(HEX2VAL(buf[idx+1])<<8)|(
      HEX2VAL(buf[idx+2])<<4)|(HEX2VAL(buf[idx+3])<<0));
}
Uint8 serial_make8 (Uint8 * buf, Uint16 idx)
Function converting characters to 8 bit value.
Parameters
in buf buffer with characters
in idx index to first character of 8 bit hex number string (two characters used)
Definition at line 367 of file srv_serial.c.
References HEX2VAL.
Referenced by msg_to_mem().
{
    return ((HEX2VAL(buf[idx+0])<<4)|(HEX2VAL(buf[idx+1]))<<0);
}
void serial_send (void * msg, Uint16 length)
Function sending buffers over serial port.
Parameters
in buffer character buffer to be sent
in length buffer length
Definition at line 577 of file srv_serial.c.
References serial_data_t::blocking_mode, Delay5us(), FALSE, TRANSMIT_BUFFER_SIZE, TRUE, serial_data_t::tx_buff_head, serial_data_t::tx_buff_tail, and serial_data_t::tx_buffer.
Referenced by serial_send_response().
{
  
    Uint16 TrNewHead;
    Uint8 dummy;
    CChar * buffer = (CChar *)msg;
    IEC0bits.U1TXIE = 0;
    serial_enable_transmitter(TRUE);
    Delay5us(100);
    
    while((U1STAbits.URXDA != 0))dummy = U1RXREG;
    
    if(length > 0)
    {
        if(serial_data.tx_buff_tail == serial_data.
      tx_buff_head)
        {
            // Launch transmission (if not already in progress)
            while(U1STAbits.UTXBF!=0)continue; // wait unitl FIFO is available
            U1TXREG = *buffer;
            buffer++;
            length--;
        }
    }
    while (length > 0)
    {
        TrNewHead = (serial_data.tx_buff_head + 1)%
      TRANSMIT_BUFFER_SIZE;
        if(TrNewHead != serial_data.tx_buff_tail)
        {
            serial_data.tx_buffer[serial_data.
      tx_buff_head] = *buffer;
            buffer++;
            length--;
            serial_data.tx_buff_head = TrNewHead;
        }
        else
        {
            if(serial_data.blocking_mode == 0)
            {
                // Cut the message - does not fit into buffer :-(
                length = 0;
            }
            else
            {
                IEC0bits.U1TXIE = 1;
                serial_wait_sent();
                IEC0bits.U1TXIE = 0;
                serial_enable_transmitter(FALSE);
                while((U1STAbits.URXDA != 0))dummy = U1RXREG;
                IEC0bits.U1RXIE = 1;
                length = 0;
            }
        }
    }
    IEC0bits.U1TXIE = 1;
}
void serial_send_response (serial_msg_t msg)
Function sending command responses on serial line.
Parameters
in cmd response command
in arg response argument
Function sending command responses on serial line.
Parameters
in cmd response command
in arg response argument
Definition at line 412 of file srv_serial.c.
References serial_msg_t::arg, serial_msg_t::arg_cnt, ASSERT, serial_msg_t::attachment, serial_msg_t::cmd, crc16(), serial_data_t::rc_buffer, and serial_send().
{
  
    // {CMD:CHSN00000000....:crc}
    // 0123456789012345
    // 0000000000111111
   //during this time i.e. while processing command, all incoming messages are ignored
   //hence, the receive buffer will be used temporarily while preparing response msg
   char *message = (char *)(serial_data.rc_buffer);
   Uint16 length = 0;
  Uint16 type = (((msg.cmd&0x00F0)>>4)== 0xE)?0xE:
                 ((((msg.cmd&0x0F00)>>8)==6)?6:3);
 if(msg.attachment.length > 0)type = 0xE; else type = msg.arg_cnt;
 switch(type)
   {
       case 3/*3 arg msg*/:
       {
       sprintf(message,"{%04X:%02X%02X%04X:",msg.cmd,msg.arg[0],msg.arg[1],msg.
      arg[2]);
       sprintf(message+15,"%04X}",crc16((Uint8*)message,14));
       length = 20;
       }break;
       case 4/*4 arg msg*/:
       { sprintf(message,"{%04X:%02X%02X%04X%04X:",msg.cmd,msg.arg[0],msg.
      arg[1],msg.arg[2],msg.arg[3]);
       sprintf(message+19,"%04X}",crc16((Uint8*)message,18));
       length = 24;
       }break;
       case 0xE /*data transfer*/:
       {
       const char cnv[] = "0123456789ABCDEF";
       memset(message,0,sizeof(message));
       sprintf(message,"{%04X:%02X%02X%04X%04X",msg.cmd,
                                            msg.arg[0],msg.arg[1],
                                            msg.arg[2],msg.arg[3]);
       //if(msg.attachment.offset == 0)
       // memcpy((void *)((void *)&pre_data + msg.attachment.offset),(void *)(msg.attachment.location +
       msg.attachment.offset),sizeof(pre_act_record_buffer_t));
       Uint16 var;
       Uint16 cc = 0;
/*
       for (var = 18; cc < msg.attachment.length;) {
                   message[var] =
                    cnv[(*((((Uint8 *)&pre_data + msg.attachment.offset))+(cc))>>4)&0x0F];
                   message[var+1] =
                    cnv[(*((((Uint8 *)&pre_data + msg.attachment.offset))+(cc++))>>0)&0x0F];
                   var+=2;
       }
*/
   
       for (var = 18; cc < msg.attachment.length;) {
                   message[var] =
                    cnv[(*((((Uint8 *)msg.attachment.location + msg.
      attachment.offset))+(cc))>>4)&0x0F];
                   message[var+1] =
                    cnv[(*((((Uint8 *)msg.attachment.location + msg.
      attachment.offset))+(cc++))>>0)&0x0F];
                   var+=2;
       }
  
     
       message[var++]=':';
       sprintf(message+var,"%04X}",crc16((Uint8*)message,var-1));
       length = var+5;
       
       }break;
        default:
        {
            ASSERT(0);
        }
 }
    serial_send(message,length);
}
Variable Documentation
pre_act_record_buffer_t pre_data
Definition at line 25 of file srv_serial.c.
volatile serial_data_t serial_data
srv_serial service internal data
Definition at line 78 of file srv_serial.c.