mfield_z_sensor.c File Reference
Module responsible for mfield x axis sensor element supervision.
#include `..\..\includes\allheaders.h`
*
#include `..\..\includes_prv\aq0X\mfield_z_sensor_prv.h`
*
Functions
void mfield_z_sen_taskx (x_event *event)
mfield sensor module task function.
void mfield_z_sen_notifyx (x_notify *notify)
mfield module notification function.
Float32 mfield_z_sen_first_order_derivative (Int16 final_val, Int16 init_val, Float32 period)
Claculate first order derivative.
Float32 mfield_z_sen_calc_probablity (Uint16 event, Uint16 obs)
Claculates the event probablity.
Bool mfield_z_zero_cross (void)
Claculate.
Int8 mfield_z_compare (Float32 num, Float32 given_num, Float32 tolerance)
Claculate.
Bool mfield_z_observation_time_window_expired (void)
Claculate.
Float32 mfield_z_input_signal (void)
Claculate.
void mfield_z_sen_sensor_element_sv_task (void)
Supervise the status of the mfield sensor.
void mfield_z_sen_false_positive_correction_task (void)
checks the number of false positives within supervision time window
void mfield_z_sen_mark_false_postives (void)
checks the number of false positives within supervision (100ms | 5 cycle) time window
Variables
mfield_z_sen_data_t mfield_z_sen_data
Internal mfield_z_sen module data.
x_task_id mfield_z_sen_id
Detailed Description
Module responsible for mfield x axis sensor element supervision.
Definition in file mfield_z_sensor.c.
Function Documentation
Int8 mfield_z_compare (Float32 num, Float32 given_num, Float32 tolerance)
Claculate.
Parameters
ad_value
Definition at line 223 of file mfield_z_sensor.c.
Referenced by mfield_z_input_signal().
                                                                        {
   if(((given_num-given_num*tolerance) <= num) && (num <= (given_num + given_num*tolerance)))
       return 0;
   if(num < (given_num-given_num*tolerance))
       return -1;
   if(num > (given_num+given_num*tolerance))
       return 1;
   return -2;
}
Float32 mfield_z_input_signal (void)
Claculate.
Parameters
ad_value
TODO: determine the frquency type and
Definition at line 255 of file mfield_z_sensor.c.
References state_data_mfield_t::change_per_time, module_status_mfield_t::current, mfield_z_compare(), mfield_z_sen_data_t::module_status, module_status_mfield_t::projected, and state_data_mfield_t::signal_level.
                                   {
    Float32 result;
    Float32 current_signal_level = 0;
              mfield_z_sen_data.module_status.
      projected.amplitude
              = mfield_z_sen_data.module_status.
      current.change_per_time/
                     (mfield_z_sen_data.module_status.
      projected.angular_freq
                      *cos(mfield_z_sen_data.module_status.
      projected.angular_freq*mfield_z_sen_data.module_status.
      current.time)
                      );
             current_signal_level = mfield_z_sen_data.
      module_status.projected.amplitude
               *sin(mfield_z_sen_data.module_status.
      projected.angular_freq*mfield_z_sen_data.module_status.
      current.time);
          result = mfield_z_compare((Float32)(
      mfield_z_sen_data.module_status.current.
      signal_level)
                  ,current_signal_level,0.05/*TODO: user configurable*/);
          if(result == 0)
              mfield_z_sen_data.module_status.
      projected.positive_cnt++;
          return result;
}
Bool mfield_z_observation_time_window_expired (void)
Claculate.
Parameters
ad_value
Definition at line 241 of file mfield_z_sensor.c.
References module_status_mfield_t::current, FALSE, mfield_z_sen_data_t::module_status, OBSERVATION_TIME_WINDOW, and TRUE.
                                                   {
    return (mfield_z_sen_data.module_status.
      current.time <= OBSERVATION_TIME_WINDOW)?FALSE:
      TRUE;
}
Float32 mfield_z_sen_calc_probablity (Uint16 event, Uint16 obs)
Claculates the event probablity.
Parameters
ad_value
Definition at line 191 of file mfield_z_sensor.c.
                                                             {
    return (Float32)event/(Float32)obs;
}
void mfield_z_sen_false_positive_correction_task (void)
checks the number of false positives within supervision time window
Definition at line 733 of file mfield_z_sensor.c.
Referenced by mfield_z_sen_taskx().
                                                      {
}
Float32 mfield_z_sen_first_order_derivative (Int16 final_val, Int16 init_val, Float32 period)
Claculate first order derivative.
Parameters
ad_value
Definition at line 179 of file mfield_z_sensor.c.
                                                                                          {
    return (Float32)(final_val-init_val)/period;
}
void mfield_z_sen_mark_false_postives (void)
checks the number of false positives within supervision (100ms | 5 cycle) time window
Definition at line 747 of file mfield_z_sensor.c.
References mfield_z_sen_data_t::configured, configured_t::dfdt_treshold_max, mfield_z_sen_data_t::diagonesis_records, mfield_z_sen_data_t::disturbance_record, module_disturbance_record_t::event_data, EXCEDED_AMP_TH, diagonesis_records_mfield_t::false_alarm, RANGE_MAX_32BIT, and RANGE_MAX_8BIT.
Referenced by mfield_z_sen_notifyx().
                                           {
        if(mfield_z_sen_data.disturbance_record->
      event_data.event_history == EXCEDED_AMP_TH){
               if(
                (mfield_z_sen_data.diagonesis_records.
      false_alarm.amp_max_exceded.cnt < RANGE_MAX_8BIT)
                &
                (mfield_z_sen_data.diagonesis_records.
      false_alarm.amp_max_exceded.accumulated_value < RANGE_MAX_32BIT)
               )
               {
                     mfield_z_sen_data.diagonesis_records.
      false_alarm.amp_max_exceded.cnt++;
                     mfield_z_sen_data.diagonesis_records.
      false_alarm.amp_max_exceded.accumulated_value
                     +=(mfield_z_sen_data.disturbance_record->
      event_data.buffer.signal_level[0]-mfield_z_sen_data.
      configured.amp_treshold_max);
                     mfield_z_sen_data.diagonesis_records.
      false_alarm.amp_max_exceded.recorded_avg
                     = mfield_z_sen_data.diagonesis_records.
      false_alarm.amp_max_exceded.accumulated_value/
                             (Float32)mfield_z_sen_data.
      diagonesis_records.false_alarm.amp_max_exceded.cnt;
              }
             }else if(mfield_z_sen_data.disturbance_record->
      event_data.event_history > EXCEDED_AMP_TH){
             if(
                (mfield_z_sen_data.diagonesis_records.
      false_alarm.dfdt_max_exceded.cnt < RANGE_MAX_8BIT)
                &
                (mfield_z_sen_data.diagonesis_records.
      false_alarm.dfdt_max_exceded.accumulated_value < RANGE_MAX_32BIT)
               )
             {
                 mfield_z_sen_data.diagonesis_records.
      false_alarm.dfdt_max_exceded.cnt++;
                 mfield_z_sen_data.diagonesis_records.
      false_alarm.dfdt_max_exceded.accumulated_value
                 +=(mfield_z_sen_data.disturbance_record->
      event_data.buffer.change_per_time[0]-mfield_z_sen_data.
      configured.dfdt_treshold_max);
                 mfield_z_sen_data.diagonesis_records.
      false_alarm.dfdt_max_exceded.recorded_avg
                 = mfield_z_sen_data.diagonesis_records.
      false_alarm.dfdt_max_exceded.accumulated_value/
                    (Float32)mfield_z_sen_data.
      diagonesis_records.false_alarm.dfdt_max_exceded.cnt;
             }
             }
}
void mfield_z_sen_notifyx (x_notify * notify)
mfield module notification function.
Parameters
in notify - system distributed notification
Definition at line 114 of file mfield_z_sensor.c.
References ASSERT, mfield_z_sen_data_t::configured, module_status_mfield_t::current, mfield_z_sen_data_t::disturbance_record, configured_t::element_status_sv_en, sv_error_flags_ut::flags_all, x_notify::message, x_notify_mfield_sen_configure::message, mfield_z_sen_mark_false_postives(), mfield_z_sen_data_t::module_status, state_data_mfield_t::state, STATE_0, mfield_z_sen_data_t::sv_errors_flags, mfield_z_sen_data_t::sv_task_event, mfield_z_sen_data_t::sv_timer_ntf, SV_TIMER_PERIOD, x_delete_timer(), X_MS2TICK, X_NTF_INIT, X_NTF_MFIELD_SENSOR_SV_TIMER, x_schedule_timer(), and x_send_event().
{
    switch(notify->message)
    {
        case X_NTF_INIT:
        {
            mfield_z_sen_init();
        }break;
        case X_NTF_MFIELD_Z_SENSOR_CONFIG:
        {
              // Algorithm module configuration reading
              x_notify_mfield_sen_configure * notify_configure = (
      x_notify_mfield_sen_configure *)notify;
              // Module configuration
              mfield_z_sen_data.configured = notify_configure->
      message.configured;
              mfield_z_sen_data.disturbance_record = notify_configure->
      message.disturbance_record;
              // Clear supervison state (so errors will be reported if module have internal error)
              mfield_z_sen_data.sv_errors_flags.
      flags_all = 0;
              x_delete_timer(&mfield_z_sen_data.
      sv_timer_ntf);
              if(mfield_z_sen_data.configured.
      element_status_sv_en)
              x_schedule_timer(&mfield_z_sen_data.
      sv_timer_ntf,X_MS2TICK(SV_TIMER_PERIOD));
        }break;
         case X_NTF_CLR_ALARM:
        {
           // Algorithm module alarm reset request
             mfield_z_sen_data.module_status.
      current.state = STATE_0;
             mfield_z_sen_mark_false_postives();
        }break;
        case X_NTF_MFIELD_SENSOR_SV_TIMER:
        {
           x_send_event(&mfield_z_sen_data.
      sv_task_event);
        }break;
        default:
        {
            ASSERT(0);
        }
    }
}
void mfield_z_sen_sensor_element_sv_task (void)
Supervise the status of the mfield sensor.
Parameters
ad_value
Supervises mfield sensors element by measuring sensor respond for different illumination level
Definition at line 721 of file mfield_z_sensor.c.
Referenced by mfield_z_sen_taskx().
{
}
void mfield_z_sen_taskx (x_event * event)
mfield sensor module task function.
Parameters
in event - system distributed event
Definition at line 73 of file mfield_z_sensor.c.
References ASSERT, sv_error_flags_ut::flags_all, x_event::message, x_notify_mfield_sen_sv_report::message, mfield_z_sen_false_positive_correction_task(), mfield_z_sen_sensor_element_sv_task(), x_notify_mfield_sen_sv_report::notify, mfield_z_sen_data_t::sv_errors_flags, mfield_z_sen_data_t::sv_status_ntf, X_MSG_MFIELD_SENSOR_SV, and x_send_notify().
{
    switch(event->message)
    {
        case X_MSG_MFIELD_SENSOR_SV:
        {
            mfield_z_sen_sensor_element_sv_task();
            mfield_z_sen_false_positive_correction_task();
            if(mfield_z_sen_data.sv_errors_flags.
      flags_all!=0){
             mfield_z_sen_data.sv_status_ntf.
      message.error_status_flags = mfield_z_sen_data.
      sv_errors_flags;
             // Send notification to Algorithm module about error
             x_send_notify(&mfield_z_sen_data.
      sv_status_ntf.notify);
             mfield_z_sen_data.sv_errors_flags.
      flags_all =0;
            }
        }break;
        default:
        {
            ASSERT(0);
        }
    }
}
Bool mfield_z_zero_cross (void)
Claculate.
Parameters
TODO: angular freq = 2*PI/(this_time - last_cross_time)
Definition at line 203 of file mfield_z_sensor.c.
References module_status_mfield_t::current, FALSE, mfield_z_sen_data_t::module_status, state_data_mfield_t::polarity, module_status_mfield_t::previous, and TRUE.
                              {
    if((mfield_z_sen_data.module_status.previous.
      polarity*mfield_z_sen_data.module_status.
      current.polarity)<=0)
    return TRUE;
    else
    return FALSE;
}
Variable Documentation
mfield_z_sen_data_t mfield_z_sen_data
Internal mfield_z_sen module data.
Definition at line 22 of file mfield_z_sensor.c.
x_task_id mfield_z_sen_id
Definition at line 23 of file mfield_z_sensor.c.