uv_sensor.c File Reference
Module responsible for uv sensor element supervision.
#include `..\..\includes\allheaders.h`
*
#include `..\..\includes_prv\aq0X\uv_sensor_prv.h`
*
Functions
void uv_sen_taskx (x_event *event)
uv sensor module task function.
void uv_sen_notifyx (x_notify *notify)
uv module notification function.
Int8 uv_compare (Float32 num1, Float32 num2, Float32 tolerance)
Float32 uv_sen_first_order_derivative (Uint16 final_val, Uint16 init_val)
Claculate first order derivative.
Float32 uv_sen_calc_probablity (Uint16 event, Uint16 obs)
Claculates the event probablity.
event_report_t uv_sen_get_status (Uint16 adc_value, Bool save_event)
Supervise the status of the uv sensor.
Uint8 uv_sen_hif_check (void)
Variables
uv_sen_data_t uv_sen_data
Internal uv_sen module data.
x_task_id uv_sen_id
mfield_x_sen module handle
Uint32 uv_event_trigger_timestamp
Detailed Description
Module responsible for uv sensor element supervision.
Definition in file uv_sensor.c.
Function Documentation
Int8 uv_compare (Float32 num1, Float32 num2, Float32 tolerance)
Parameters
Definition at line 215 of file uv_sensor.c.
                                                               {
    Float32 difference = num1 - num2;
   if(abs(difference) <= tolerance)
    return 0;
   if(difference > 0/*num1 > num2*/)
    return 1;
   if(difference < 0/*num1 < num2*/)
    return -1;
   return -2;
}
Float32 uv_sen_calc_probablity (Uint16 event, Uint16 obs)
Claculates the event probablity.
Parameters
in event,positive event count value
in obs,total number of observation
Definition at line 251 of file uv_sensor.c.
                                                       {
    return (100L*((Float32)event/(Float32)obs));
}
Float32 uv_sen_first_order_derivative (Uint16 final_val, Uint16 init_val)
Claculate first order derivative.
Definition at line 238 of file uv_sensor.c.
                                                                        {
    return ((Float32)final_val-(Float32)init_val);
}
event_report_t uv_sen_get_status (Uint16 adc_value, Bool save_event)
Supervise the status of the uv sensor.
REQ-1b: "A valid trip is issued, for few handres of microseconds after trip data will be saved at provided location.
Definition at line 302 of file uv_sensor.c.
References __1ST_ORDER_DERIVATIVE, __COMPARE_ZERO, __PROBABLITY, configured_t::amp_treshold, ASSERT, pre_act_record_buffer_t::buffer, state_data_light_t::change_per_time, uv_sen_data_t::configured, module_status_t::current, data_non_volatile, logv_t::data_tx_on_progress, configured_t::dfdt_treshold_impulse, configured_t::dfdt_treshold_max, configured_t::dfdt_treshold_min, uv_sen_data_t::disturbance_record, logv_t::disturbance_record, pre_act_record_buffer_t::elapsed, EMU_MODE_DATA_LENGTH, module_disturbance_record_t::event_data, module_disturbance_record_t::event_positive_cnt, FALSE, event_report_t::fields, pre_act_record_buffer_t::head, HOT, logv, configured_t::min_number_of_observation, uv_sen_data_t::module_status, module_disturbance_record_t::observation_cnt, module_disturbance_record_t::post_act_data, POST_ACT_RECORD_BUFF_SIZE, module_disturbance_record_t::pre_act_data, PRE_ACT_RECORD_BUFF_SIZE, module_status_t::previous, configured_t::probablity_treshold_max, configured_t::probablity_treshold_min, module_status_t::projected, state_data_light_t::signal_level, state_data_light_t::slop_polarity, state_data_light_t::state, STATE_0, STATE_1, STATE_2, STATE_3, pre_act_record_buffer_t::tail, logv_t::tick, TRUE, UV_SEN_NOISE_DENSITY_LEVEL, and logv_t::wr.
Referenced by __attribute__().
Uint8 uv_sen_hif_check (void)
Definition at line 871 of file uv_sensor.c.
References __COMPARE_U, uv_sen_data_t::configured, uv_sen_data_t::diagonesis_records, configured_t::hif_diagonesis_records, PRE_ACT_RECORD_BUFF_SIZE, and diagonesis_records_light_t::signal_history.
                            {
    Uint8 result = 0;
return result;
    if(uv_sen_data.configured.hif_diagonesis_records->head <
      PRE_ACT_RECORD_BUFF_SIZE)
        return result;
    uv_sen_data.configured.hif_diagonesis_records->mean_value/=
      PRE_ACT_RECORD_BUFF_SIZE;
    if(uv_sen_data.diagonesis_records.
      signal_history.time.itoi_counter.total_observation > 0)
    if(__COMPARE_U(
            (
            uv_sen_data.diagonesis_records.
      signal_history.time.itoi_counter.total_observation
            -
            uv_sen_data.diagonesis_records.
      signal_history.time.itoi_counter.positive_event
            )
            ,2
            )==0
           )
        result++;
    if(uv_sen_data.diagonesis_records.
      signal_history.time.ptop_counter.total_observation > 0)
    if(__COMPARE_U(
          (
           uv_sen_data.diagonesis_records.
      signal_history.time.ptop_counter.total_observation
          -
           uv_sen_data.diagonesis_records.
      signal_history.time.ptop_counter.positive_event
          )
         ,0
          )==0
       )
        result++;
    uv_sen_data.diagonesis_records.signal_history.time.
      itoi_counter.positive_event = 0;
    uv_sen_data.diagonesis_records.signal_history.time.
      itoi_counter.total_observation = 0;
    uv_sen_data.diagonesis_records.signal_history.time.
      ptop_counter.positive_event = 0;
    uv_sen_data.diagonesis_records.signal_history.time.
      ptop_counter.total_observation = 0;
    return result;
}
void uv_sen_notifyx (x_notify * notify)
uv module notification function.
Parameters
in notify - system distributed notification
Definition at line 141 of file uv_sensor.c.
References ASSERT, uv_sen_data_t::configured, uv_sen_data_t::disturbance_record, configured_t::element_status_sv_en, sv_error_flags_ut::flags_all, x_notify_uv_sen_configure::message, x_notify::message, uv_sen_data_t::module_status, module_status_t::projected, SCAN_FREQ, uv_sen_data_t::sv_errors_flags, uv_sen_data_t::sv_task_event, uv_sen_data_t::sv_timer_ntf, SV_TIMER_PERIOD, configured_t::sys_freq, x_delete_timer(), X_MS2TICK, X_NTF_CLR_ALARM_UV_SEN, X_NTF_INIT, X_NTF_UV_SENSOR_CONFIG, X_NTF_UV_SENSOR_SV_TIMER, x_schedule_timer(), and x_send_event().
Referenced by main().
{
    switch(notify->message)
    {
        case X_NTF_INIT:
        {
            uv_sen_init();
        }break;
        case X_NTF_UV_SENSOR_CONFIG:
        {
            // configuration details from algorithm module
            x_notify_uv_sen_configure * notify_configure = (
      x_notify_uv_sen_configure *)notify;
            uv_sen_data.configured = notify_configure->
      message.configured;
            uv_sen_data.disturbance_record = notify_configure->
      message.disturbance_record;
           uv_sen_data.module_status.projected.angular_freq =
      2*PI*uv_sen_data.configured.sys_freq;
           uv_sen_data.module_status.projected.samples_per_period =
      (Uint16)(SCAN_FREQ/(Float32)(uv_sen_data.
      configured.sys_freq));
           uv_sen_data.module_status.projected.samples_per_period_1_2 =
      uv_sen_data.module_status.projected.samples_per_period/2;
           uv_sen_data.module_status.projected.samples_per_period_1_4 =
      uv_sen_data.module_status.projected.samples_per_period/4;
           uv_sen_data.module_status.projected.samples_per_period_1_8 =
      uv_sen_data.module_status.projected.samples_per_period/8;
            // Clear supervison state (so errors will be reported if module have internal error)
          uv_sen_data.sv_errors_flags.flags_all = 0;
          x_delete_timer(&uv_sen_data.sv_timer_ntf);
          if(uv_sen_data.configured.element_status_sv_en)
          x_schedule_timer(&uv_sen_data.sv_timer_ntf,
      X_MS2TICK(SV_TIMER_PERIOD));
        }break;
        case X_NTF_CLR_ALARM_UV_SEN:
        {
           // Algorithm module alarm reset request
             //uv_sen_data.module_status.current.state = STATE_0;
             uv_sen_mark_false_postives();
             uv_sen_mark_false_postives();
             uv_sen_mark_false_postives();
        }break;
        case X_NTF_UV_SENSOR_SV_TIMER:
        {
           x_send_event(&uv_sen_data.sv_task_event);
        }break;
        default:
        {
            ASSERT(0);
        }
    }
}
void uv_sen_taskx (x_event * event)
uv sensor module task function.
Parameters
in event - system distributed event
Definition at line 69 of file uv_sensor.c.
References configured_t::amp_treshold, ASSERT, uv_sen_data_t::configured, uv_sen_data_t::diagonesis_records, sv_error_flags_ut::flags_all, x_event::message, x_notify_module_sv_status_report_t::message, x_notify_module_sv_status_report_t::notify, diagonesis_records_light_t::signal_history, srv_wdg_kick, uv_sen_data_t::sv_errors_flags, uv_sen_data_t::sv_status_ntf, X_MSG_UV_SENSOR_SV, and x_send_notify().
Referenced by main().
{
    switch(event->message)
    {
        case X_MSG_UV_SENSOR_SV:
        {
            srv_wdg_kick();
            uv_sen_sensor_element_sv_task();
            if(uv_sen_data.diagonesis_records.
      signal_history.amp.total_observation >0)
                uv_sen_data.diagonesis_records.
      signal_history.amp.avg =
                        (uv_sen_data.diagonesis_records.
      signal_history.amp.accumulated/
                        uv_sen_data.diagonesis_records.
      signal_history.amp.total_observation);
            if(uv_sen_data.diagonesis_records.
      signal_history.amp_exceded.total_observation >0){
                uv_sen_data.diagonesis_records.
      signal_history.amp_exceded.avg =
                        (uv_sen_data.diagonesis_records.
      signal_history.amp_exceded.accumulated/
                        uv_sen_data.diagonesis_records.
      signal_history.amp_exceded.total_observation);
                uv_sen_data.diagonesis_records.
      signal_history.th_gap.avg
                    = (uv_sen_data.diagonesis_records.
      signal_history.amp_exceded.avg - uv_sen_data.configured.
      amp_treshold.set_value);
            }
            else
            uv_sen_data.diagonesis_records.
      signal_history.th_gap.avg
                    = (uv_sen_data.diagonesis_records.
      signal_history.amp.avg - uv_sen_data.configured.
      amp_treshold.set_value);
              uv_sen_data.diagonesis_records.
      signal_history.amp.accumulated = 0;
              uv_sen_data.diagonesis_records.
      signal_history.amp.total_observation = 0;
              uv_sen_data.diagonesis_records.
      signal_history.amp_exceded.accumulated = 0;
              uv_sen_data.diagonesis_records.
      signal_history.amp_exceded.total_observation = 0;
             uv_sen_threshold_adjustment_task();
            if((uv_sen_data.sv_errors_flags.flags_all!=0) || (
      uv_sen_data.configured.amp_treshold.adjusted == 1)){
             uv_sen_data.sv_status_ntf.message.error_flags =
      uv_sen_data.sv_errors_flags;
             uv_sen_data.sv_status_ntf.message.config =
      uv_sen_data.configured;
             // Send notification to Algorithm module about detected error
             x_send_notify(&uv_sen_data.sv_status_ntf.
      notify);
             uv_sen_data.sv_errors_flags.flags_all =0;
             uv_sen_data.configured.amp_treshold.adjusted = 0;
            }
        }break;
        default:
        {
            ASSERT(0);
        }
    }
}
Variable Documentation
Uint32 uv_event_trigger_timestamp
Definition at line 26 of file uv_sensor.c.
uv_sen_data_t uv_sen_data
Internal uv_sen module data.
Definition at line 22 of file uv_sensor.c.
x_task_id uv_sen_id
mfield_x_sen module handle
Definition at line 23 of file uv_sensor.c.
Referenced by main().