mfield_x_sensor.c File Reference
Module responsible for mfield x axis sensor element supervision.
#include `..\..\includes\allheaders.h`
*
#include `..\..\includes_prv\aq0X\mfield_x_sensor_prv.h`
*
Functions
void mfield_x_sen_taskx (x_event *event)
module task function.
void mfield_x_sen_notifyx (x_notify *notify)
module notification function.
Float32 mfield_x_sen_first_order_derivative (Int16 final_val, Int16 init_val)
Claculate first order derivative.
Float32 mfield_x_sen_calc_probablity (Uint16 event, Uint16 obs)
Claculates the event probablity.
Int8 mfield_x_compare (Float32 num1, Float32 num2, Float32 tolerance)
event_report_t mfield_x_sen_get_status (Uint16 adc_value, Bool save_event)
function used to identify the measured signal waveform
Variables
mfield_x_sen_data_t mfield_x_sen_data
Internal mfield_x_sen module data.
x_task_id mfield_x_sen_id
mfield_x_sen module handle
Detailed Description
Module responsible for mfield x axis sensor element supervision.
Module responsible for mfield_x sensor element supervision.
Definition in file mfield_x_sensor.c.
Function Documentation
Int8 mfield_x_compare (Float32 num1, Float32 num2, Float32 tolerance)
Parameters
Definition at line 221 of file mfield_x_sensor.c.
References __COMPARE.
                                                                    {
     return __COMPARE((num1 - num2),tolerance);
   Float32 difference = num1 - num2;
   if(abs(difference) <= tolerance)
    return 0;
   if(difference > 0/*num1 > num2*/)
    return 1;
   if(difference < 0/*num1 < num2*/)
    return -1;
   return -2;
}
Float32 mfield_x_sen_calc_probablity (Uint16 event, Uint16 obs)
Claculates the event probablity.
Parameters
in event,positive event count value
in obs,total number of observation
Definition at line 191 of file mfield_x_sensor.c.
                                                             {
    return (100L*((Float32)event/(Float32)obs));
}
Float32 mfield_x_sen_first_order_derivative (Int16 final_val, Int16 init_val)
Claculate first order derivative.
Parameters
ad_value
Definition at line 178 of file mfield_x_sensor.c.
                                                                           {
     return ((Float32)final_val-(Float32)init_val);
}
event_report_t mfield_x_sen_get_status (Uint16 adc_value, Bool save_event)
function used to identify the measured signal waveform
function supervise the status of the mfield sensor req REQ-1b: "when a valid trip is issued,for few handres of microseconds after trip data will be to the provided location.
Definition at line 276 of file mfield_x_sensor.c.
References __1ST_ORDER_DERIVATIVE, __COMPARE_ZERO, __PROBABLITY, configured_t::amp_treshold, ASSERT, pre_act_record_buffer_t::buffer, state_data_mfield_t::change_per_time, mfield_x_sen_data_t::configured, module_status_mfield_t::current, data_non_volatile, logv_t::data_tx_on_progress, configured_t::dfdt_treshold_impulse, configured_t::dfdt_treshold_max, configured_t::dfdt_treshold_min, mfield_x_sen_data_t::disturbance_record, logv_t::disturbance_record, pre_act_record_buffer_t::elapsed, EMU_MODE_DATA_LENGTH, module_disturbance_record_t::event_data, module_disturbance_record_t::event_positive_cnt, FALSE, event_report_t::fields, pre_act_record_buffer_t::head, HOT, logv, MFIELD_ADC_QUIESCENT_LEVEL, MFIELD_SEN_NOISE_DENSITY_LEVEL, configured_t::min_number_of_observation, mfield_x_sen_data_t::module_status, module_disturbance_record_t::observation_cnt, state_data_mfield_t::polarity, module_disturbance_record_t::post_act_data, POST_ACT_RECORD_BUFF_SIZE, module_disturbance_record_t::pre_act_data, PRE_ACT_RECORD_BUFF_SIZE, module_status_mfield_t::previous, configured_t::probablity_treshold_max, configured_t::probablity_treshold_min, module_status_mfield_t::projected, state_data_mfield_t::signal_level, state_data_mfield_t::state, STATE_0, STATE_1, STATE_2, STATE_3, pre_act_record_buffer_t::tail, logv_t::tick, TRUE, and logv_t::wr.
void mfield_x_sen_notifyx (x_notify * notify)
module notification function.
Parameters
in notify - system distributed notification
Definition at line 107 of file mfield_x_sensor.c.
References ASSERT, mfield_x_sen_data_t::configured, mfield_x_sen_data_t::disturbance_record, configured_t::element_status_sv_en, sv_error_flags_ut::flags_all, x_notify::message, x_notify_mfield_sen_configure::message, mfield_x_sen_data_t::module_status, module_status_mfield_t::projected, SCAN_FREQ, mfield_x_sen_data_t::sv_errors_flags, mfield_x_sen_data_t::sv_task_event, mfield_x_sen_data_t::sv_timer_ntf, SV_TIMER_PERIOD, configured_t::sys_freq, x_delete_timer(), X_MS2TICK, X_NTF_CLR_ALARM_MFIELD_SEN, X_NTF_INIT, X_NTF_MFIELD_SENSOR_SV_TIMER, X_NTF_MFIELD_X_SENSOR_CONFIG, x_schedule_timer(), and x_send_event().
{
    switch(notify->message)
    {
        case X_NTF_INIT:
        {
            mfield_x_sen_init();
        }break;
        case X_NTF_MFIELD_X_SENSOR_CONFIG:
        {
              // Algorithm module configuration reading
              x_notify_mfield_sen_configure * notify_configure = (
      x_notify_mfield_sen_configure *)notify;
              // Module configuration
              mfield_x_sen_data.configured = notify_configure->
      message.configured;
              mfield_x_sen_data.disturbance_record = notify_configure->
      message.disturbance_record;
              mfield_x_sen_data.module_status.
      projected.angular_freq = 2*PI*mfield_x_sen_data.
      configured.sys_freq;
              mfield_x_sen_data.module_status.
      projected.samples_per_period = (Uint16)(SCAN_FREQ/(
      Float32)(mfield_x_sen_data.configured.sys_freq));
              mfield_x_sen_data.module_status.
      projected.samples_per_period_1_2 = mfield_x_sen_data.
      module_status.projected.samples_per_period/2;
              mfield_x_sen_data.module_status.
      projected.samples_per_period_1_4 = mfield_x_sen_data.
      module_status.projected.samples_per_period/4;
              mfield_x_sen_data.module_status.
      projected.samples_per_period_1_8 = mfield_x_sen_data.
      module_status.projected.samples_per_period/8;
              // Clear supervison state (so errors will be reported if module have internal error)
              mfield_x_sen_data.sv_errors_flags.
      flags_all = 0;
              x_delete_timer(&mfield_x_sen_data.
      sv_timer_ntf);
              if(mfield_x_sen_data.configured.
      element_status_sv_en)
              x_schedule_timer(&mfield_x_sen_data.
      sv_timer_ntf,X_MS2TICK(SV_TIMER_PERIOD));
        }break;
         case X_NTF_CLR_ALARM_MFIELD_SEN:
        {
           // Algorithm module alarm reset request
           // mfield_x_sen_data.module_status.current.state = STATE_0;
             mfield_x_sen_mark_false_postives();
        }break;
        case X_NTF_MFIELD_SENSOR_SV_TIMER:
        {
           x_send_event(&mfield_x_sen_data.
      sv_task_event);
        }break;
        default:
        {
            ASSERT(0);
        }
    }
}
void mfield_x_sen_taskx (x_event * event)
module task function.
Parameters
in event - system distributed event
Definition at line 71 of file mfield_x_sensor.c.
References ASSERT, sv_error_flags_ut::flags_all, x_event::message, x_notify_mfield_sen_sv_report::message, x_notify_mfield_sen_sv_report::notify, srv_wdg_kick, mfield_x_sen_data_t::sv_errors_flags, mfield_x_sen_data_t::sv_status_ntf, X_MSG_MFIELD_SENSOR_SV, and x_send_notify().
{
    switch(event->message)
    {
        case X_MSG_MFIELD_SENSOR_SV:
        {
            srv_wdg_kick();
            mfield_x_sen_sensor_element_sv_task();
            if(mfield_x_sen_data.sv_errors_flags.
      flags_all!=0){
             mfield_x_sen_data.sv_status_ntf.
      message.error_status_flags = mfield_x_sen_data.
      sv_errors_flags;
             // Send notification to Algorithm module about error
             x_send_notify(&mfield_x_sen_data.
      sv_status_ntf.notify);
             mfield_x_sen_data.sv_errors_flags.
      flags_all =0;
            }
        }break;
        default:
        {
            ASSERT(0);
        }
    }
}
Variable Documentation
mfield_x_sen_data_t mfield_x_sen_data
Internal mfield_x_sen module data.
Definition at line 23 of file mfield_x_sensor.c.
x_task_id mfield_x_sen_id
mfield_x_sen module handle
Definition at line 24 of file mfield_x_sensor.c.