main.c File Reference
Low-level startup , calls OS initalization.
#include `..\includes\allheaders.h`
*
Functions
int main (void)
System startup function.
Variables
sqtp_t sqtp_info
Oscilator setting Run this project using an internal FRC.
Detailed Description
Low-level startup , calls OS initalization.
Definition in file main.c.
Function Documentation
int main (void)
System startup function.
Configures operating system and basic system independent services Configure Oscillator to operate the device at 60MIPS Fpll_out= Fin*M/(N1*N2)=Fin*(PLLDIV+2)/((PLLPRE+2)+(PLLPOST+1)), Fcy=Fosc/2 Fvco = Fin*M/N1 = Fin*(PLLDIV+2)/(PLLPRE+2) Fpll_out = 7.37M*65/(2*3) = 80Mhz for 7.37MHz FRC input clock
Init watchdog. Initial kick.
Watchdog kick - before OS starts
Definition at line 80 of file main.c.
References algorithm_id, algorithm_notifyx(), algorithm_taskx(), data_non_volatile, hwio_configure_init(), hwio_execute_gpio_task(), hwio_get_analog(), HWIO_SV_LED_OFF, HWIO_SV_LED_ON, ir_sen_id, ir_sen_notifyx(), ir_sen_taskx(), light_sen_id, light_sen_notifyx(), light_sen_taskx(), mfield_x_sen_id, mfield_x_sen_notifyx(), mfield_x_sen_taskx(), mfield_y_sen_id, mfield_y_sen_notifyx(), mfield_y_sen_taskx(), nov_get_serial_number(), RANGE_MAX_8BIT, serial_init(), sqtp_t::serial_number, spi_init(), srv_wdg_init, srv_wdg_kick, SV_CURREN_OUTPUT_LEVEL, uv_sen_id, uv_sen_notifyx(), uv_sen_taskx(), x_init(), x_init_task(), x_loop(), and x_start().
{
// Configure PLL prescaler, PLL postscaler, PLL divisor
PLLFBD=63; // M=65
CLKDIVbits.PLLPOST=0; // N2=2
CLKDIVbits.PLLPRE =0; // N1=3 //TODO: other option set to N1 = 2
// Initiate Clock Switch to FRC oscillator with PLL (NOSC=0b001)
__builtin_write_OSCCONH(0x01);
__builtin_write_OSCCONL(OSCCON | 0x01);
// Wait for Clock switch to occur
while (OSCCONbits.COSC!= 0b001);
// Wait for PLL to lock
while (OSCCONbits.LOCK!= 1);
#if !defined(__DEBUG)
   // _SWDTEN = 1;
#endif
    srv_wdg_init();
    srv_wdg_kick();
        
  
    // Init hwio
    hwio_configure_init();
    
    {
    hwio_execute_gpio_task(HWIO_SV_LED_ON);
    if(RCONbits.WDTO)
        while(1);
     #if (DEVICE == AQ0X_V1)
    Uint16 sv_current_level = hwio_get_analog(ANA_INDEX_SV_CURRENT);
    Uint8 cc = 1;
    Uint16 single_sensor_output = SV_CURREN_OUTPUT_LEVEL;
   
            while(1){
                 if(cc++ < RANGE_MAX_8BIT){
                     if(sv_current_level <= single_sensor_output){
                         data_non_volatile.device_data.installation.device_address = cc;
                         break;
                     }else
                        single_sensor_output +=SV_CURREN_OUTPUT_LEVEL;
                 }
              srv_wdg_kick();
        
            }
    #endif
    hwio_execute_gpio_task(HWIO_SV_LED_OFF);
    }
       
 
    // Init serial port communication
    serial_init();
   
    spi_init();
  
    sqtp_info.serial_number = 0;
    // Initialize SQPT production info
    sqtp_info.serial_number = nov_get_serial_number();
    //TODO:what to do if empty
 
    // Init operating system internal structures
    x_init();
    
    
    // Init modules
    x_init_task(algorithm_taskx,algorithm_notifyx,&
      algorithm_id,"algorithm");
    x_init_task(ir_sen_taskx,ir_sen_notifyx,&
      ir_sen_id,"ir");
    x_init_task(uv_sen_taskx,uv_sen_notifyx,&
      uv_sen_id,"uv");
    #if(DEVICE == AQ0X_V1)
    x_init_task(light_sen_taskx,light_sen_notifyx,&
      light_sen_id,"light");
    #endif
    x_init_task(mfield_x_sen_taskx,
      mfield_x_sen_notifyx,&mfield_x_sen_id,"mfield_x");
     
#ifdef MFIELD_Y
    x_init_task(mfield_y_sen_taskx,
      mfield_y_sen_notifyx,&mfield_y_sen_id,"mfield_y");
#endif
   
   
    // Send startup notifications to modules
    x_start();
     
    srv_wdg_kick();
    while (1)
    {
         
        // Execute operating system loop
        // The operating system takes care over watchdog bites
        x_loop();
    }
    return 0;
}
Variable Documentation
sqtp_t sqtp_info
Oscilator setting Run this project using an internal FRC.
Disable Code Protection Select PGD/PGC as debugging channel Communicate on PGEC2 and PGED2 Enable MCLR reset pin and turn off the power-up timers. Disable memory security
Definition at line 68 of file main.c.