ir_sensor.h File Reference
Data Structures
struct analog_sample_ir_t
struct x_notify_ir_sen_configure
Notification containing module operation configuration details (from Algorithm module) More...
struct x_notify_ir_sen_sv_report
Notification structure from ir_sen module to Algorithm module about supervision result. More...
struct diagonesis_records_light_t
struct state_data_light_t
struct module_status_t
struct x_notify_ir_sen_configure.message
struct x_notify_ir_sen_sv_report.message
struct diagonesis_records_light_t.signal_history
struct diagonesis_records_light_t.signal_history.amp
struct diagonesis_records_light_t.signal_history.amp_exceded
struct diagonesis_records_light_t.signal_history.th_gap
struct diagonesis_records_light_t.signal_history.time
struct diagonesis_records_light_t.signal_history.time.change_counter
struct diagonesis_records_light_t.signal_history.time.change_counter.projected_slop
struct diagonesis_records_light_t.signal_history.time.ptop_counter
struct diagonesis_records_light_t.signal_history.time.itoi_counter
struct diagonesis_records_light_t.false_alarm
Counts and stores false positive details, the module uses the information to adjust the threshold values in order to reduce false positive occurrence (i.e. More...
struct diagonesis_records_light_t.false_alarm.dfdt_exceded
struct diagonesis_records_light_t.false_alarm.amp_exceded
struct module_status_t.projected
Macros
#define X_NTF_IR_SENSOR_CONFIG (X_NTF_FREE + 11)
Notification from Algorithm module to load data from nov.
#define IR_SEN_GAIN 1
#define IR_SEN_NOISE_DENSITY_LEVEL 0.05
#define DC 0
#define HIF 1
#define FP_TOLERANCE 10
#define MAX_STOT_GAP 100
Functions
event_report_t ir_sen_get_status (Uint16 adc_value, Bool save_event)
Supervise the status of the ir sensor.
void ir_sen_taskx (x_event *event)
ir sensor module task function.
void ir_sen_notifyx (x_notify *notify)
ir module notification function.
Uint8 ir_sen_hif_check (void)
void ir_record_reset (Uint8 type)
Variables
Uint32 ir_event_trigger_timestamp
x_task_id ir_sen_id
ir_sen module handle
Data Structure Documentation
struct analog_sample_ir_t
Definition at line 29 of file ir_sensor.h.
Data Fields
Uint16
adc_val
Float32
ana_val
struct x_notify_ir_sen_configure
Notification containing module operation configuration details (from Algorithm module)
Definition at line 37 of file ir_sensor.h.
Data Fields
struct x_notify_ir_sen_configure
message
x_notify
notify
struct x_notify_ir_sen_sv_report
Notification structure from ir_sen module to Algorithm module about supervision result.
Definition at line 54 of file ir_sensor.h.
Data Fields
struct x_notify_ir_sen_sv_report
message
x_notify
notify
struct diagonesis_records_light_t
Definition at line 66 of file ir_sensor.h.
Data Fields
struct diagonesis_records_light_t
false_alarm
Counts and stores false positive details, the module uses the information to adjust the threshold values in order to reduce false positive occurrence (i.e. if the module is running in automatic adjust mode)
struct diagonesis_records_light_t
signal_history
struct state_data_light_t
Definition at line 145 of file ir_sensor.h.
Data Fields
Int16
change_per_time
Uint16
signal_level
Int8
slop_polarity
Uint8
state
struct module_status_t
Definition at line 154 of file ir_sensor.h.
Data Fields
state_data_light_t
current
state_data_light_t
previous
struct module_status_t
projected
Uint16
time
struct x_notify_ir_sen_configure.message
Definition at line 41 of file ir_sensor.h.
Data Fields
configured_t
configured
module_disturbance_record_t *
disturbance_record
struct x_notify_ir_sen_sv_report.message
Definition at line 58 of file ir_sensor.h.
Data Fields
configured_t
config
sv_error_flags_ut
error_status_flags
struct diagonesis_records_light_t.signal_history
Definition at line 68 of file ir_sensor.h.
Data Fields
signal_history
amp
signal_history
amp_exceded
signal_history
th_gap
signal_history
time
struct diagonesis_records_light_t.signal_history.amp
Definition at line 70 of file ir_sensor.h.
Data Fields
Float32
accumulated
Float32
avg
Uint16
max
Uint16
min
Uint16
total_observation
struct diagonesis_records_light_t.signal_history.amp_exceded
Definition at line 82 of file ir_sensor.h.
Data Fields
Float32
accumulated
Float32
avg
Uint16
total_observation
struct diagonesis_records_light_t.signal_history.th_gap
Definition at line 88 of file ir_sensor.h.
Data Fields
Float32
avg
struct diagonesis_records_light_t.signal_history.time
Definition at line 94 of file ir_sensor.h.
Data Fields
time
change_counter
time
itoi_counter
time
ptop_counter
struct diagonesis_records_light_t.signal_history.time.change_counter
Definition at line 95 of file ir_sensor.h.
Data Fields
Uint16
falling
change_counter
projected_slop
Uint16
rising
Uint16
total_observation
Uint16
zero
struct diagonesis_records_light_t.signal_history.time.change_counter.projected_slop
Definition at line 96 of file ir_sensor.h.
Data Fields
Int8
current
Int8
previous
struct diagonesis_records_light_t.signal_history.time.ptop_counter
Definition at line 108 of file ir_sensor.h.
Data Fields
Bool
armed
Uint16
positive_event
Uint16
total_observation
Uint16
value
struct diagonesis_records_light_t.signal_history.time.itoi_counter
Definition at line 115 of file ir_sensor.h.
Data Fields
Bool
armed
Uint16
positive_event
Uint16
total_observation
Uint16
value
struct diagonesis_records_light_t.false_alarm
Counts and stores false positive details, the module uses the information to adjust the threshold values in order to reduce false positive occurrence (i.e.
if the module is running in automatic adjust mode)
Definition at line 131 of file ir_sensor.h.
Data Fields
false_alarm
amp_exceded
false_alarm
dfdt_exceded
struct diagonesis_records_light_t.false_alarm.dfdt_exceded
Definition at line 132 of file ir_sensor.h.
Data Fields
Float32
avg
Uint16
cnt
struct diagonesis_records_light_t.false_alarm.amp_exceded
Definition at line 137 of file ir_sensor.h.
Data Fields
Uint16
avg
Uint16
cnt
struct module_status_t.projected
Definition at line 159 of file ir_sensor.h.
Data Fields
Float32
amplitude
Float32
angular_freq
Uint16
samples_per_period
Uint16
samples_per_period_1_2
Uint16
samples_per_period_1_4
Uint16
samples_per_period_1_8
Bool
waveform
Macro Definition Documentation
#define DC 0
Definition at line 21 of file ir_sensor.h.
#define FP_TOLERANCE 10
Definition at line 25 of file ir_sensor.h.
Referenced by algorithm_taskx().
#define HIF 1
Definition at line 22 of file ir_sensor.h.
Referenced by algorithm_wake(), and ir_record_reset().
#define IR_SEN_GAIN 1
Definition at line 16 of file ir_sensor.h.
#define IR_SEN_NOISE_DENSITY_LEVEL 0.05
Definition at line 18 of file ir_sensor.h.
Referenced by ir_sen_get_status().
#define MAX_STOT_GAP 100
Definition at line 26 of file ir_sensor.h.
#define X_NTF_IR_SENSOR_CONFIG (X_NTF_FREE + 11)
Notification from Algorithm module to load data from nov.
Definition at line 13 of file ir_sensor.h.
Referenced by ir_sen_notifyx().
Function Documentation
void ir_record_reset (Uint8 type)
Definition at line 1152 of file ir_sensor.c.
References ir_sen_data_t::configured, ir_sen_data_t::diagonesis_records, HIF, configured_t::hif_diagonesis_records, and diagonesis_records_light_t::signal_history.
Referenced by algorithm_wake().
                                {
    if(type == HIF){
            ir_sen_data.diagonesis_records.
      signal_history.time.itoi_counter.positive_event = 0;
            ir_sen_data.diagonesis_records.
      signal_history.time.itoi_counter.total_observation = 0;
            ir_sen_data.diagonesis_records.
      signal_history.time.ptop_counter.positive_event = 0;
            ir_sen_data.diagonesis_records.
      signal_history.time.ptop_counter.total_observation = 0;
            ir_sen_data.configured.hif_diagonesis_records->head
      = 0;
       }
}
event_report_t ir_sen_get_status (Uint16 adc_value, Bool save_event)
Supervise the status of the ir sensor.
REQ-1b: "A valid trip is issued, for few handres of microseconds, i.e. after trip data will be saved at provided location.
Definition at line 302 of file ir_sensor.c.
References __1ST_ORDER_DERIVATIVE, __COMPARE_ZERO, __PROBABLITY, event_report_t::all, configured_t::amp_treshold, ASSERT, pre_act_record_buffer_t::buffer, state_data_light_t::change_per_time, ir_sen_data_t::configured, module_status_t::current, data_non_volatile, logv_t::data_tx_on_progress, configured_t::dfdt_treshold_impulse, configured_t::dfdt_treshold_max, configured_t::dfdt_treshold_min, ir_sen_data_t::disturbance_record, logv_t::disturbance_record, pre_act_record_buffer_t::elapsed, EMU_MODE_DATA_LENGTH, module_disturbance_record_t::event_data, module_disturbance_record_t::event_positive_cnt, FALSE, event_report_t::fields, pre_act_record_buffer_t::head, HOT, IR_SEN_NOISE_DENSITY_LEVEL, logv, configured_t::min_number_of_observation, ir_sen_data_t::module_status, module_disturbance_record_t::observation_cnt, module_disturbance_record_t::post_act_data, POST_ACT_RECORD_BUFF_SIZE, module_disturbance_record_t::pre_act_data, PRE_ACT_RECORD_BUFF_SIZE, module_status_t::previous, configured_t::probablity_treshold_max, configured_t::probablity_treshold_min, module_status_t::projected, state_data_light_t::signal_level, state_data_light_t::slop_polarity, state_data_light_t::state, STATE_0, STATE_1, STATE_2, STATE_3, pre_act_record_buffer_t::tail, logv_t::tick, TRUE, and logv_t::wr.
Referenced by __attribute__().
Uint8 ir_sen_hif_check (void)
Definition at line 1100 of file ir_sensor.c.
References __COMPARE_U, hif_checklist_t::all, hif_checklist_t::bits, ir_sen_data_t::configured, ir_sen_data_t::diagonesis_records, configured_t::hif_diagonesis_records, PRE_ACT_RECORD_BUFF_SIZE, and diagonesis_records_light_t::signal_history.
Referenced by algorithm_wake().
                            {
    hif_checklist_t result;
    result.all = 0;
    if(ir_sen_data.configured.hif_diagonesis_records->head <
      PRE_ACT_RECORD_BUFF_SIZE)
        return result.all;
    ir_sen_data.configured.hif_diagonesis_records->mean_value /=
      PRE_ACT_RECORD_BUFF_SIZE;
    if(ir_sen_data.diagonesis_records.
      signal_history.time.itoi_counter.total_observation > 0)
    if(__COMPARE_U(
            (
            ir_sen_data.diagonesis_records.
      signal_history.time.itoi_counter.total_observation
            -
            ir_sen_data.diagonesis_records.
      signal_history.time.itoi_counter.positive_event
            )
            ,2
            )==0
           )
        result.bits.itoi = 1;
    if(ir_sen_data.diagonesis_records.
      signal_history.time.ptop_counter.total_observation > 0)
    if(__COMPARE_U(
          (
           ir_sen_data.diagonesis_records.
      signal_history.time.ptop_counter.total_observation
          -
           ir_sen_data.diagonesis_records.
      signal_history.time.ptop_counter.positive_event
          )
         ,0
          )==0
       )
        result.bits.ptop = 1;
    ir_sen_data.diagonesis_records.signal_history.time.
      itoi_counter.positive_event = 0;
    ir_sen_data.diagonesis_records.signal_history.time.
      itoi_counter.total_observation = 0;
    ir_sen_data.diagonesis_records.signal_history.time.
      ptop_counter.positive_event = 0;
    ir_sen_data.diagonesis_records.signal_history.time.
      ptop_counter.total_observation = 0;
    return result.all;
}
void ir_sen_notifyx (x_notify * notify)
ir module notification function.
Parameters
in notify - system distributed notification
Definition at line 141 of file ir_sensor.c.
References ASSERT, ir_sen_data_t::configured, ir_sen_data_t::disturbance_record, configured_t::element_status_sv_en, sv_error_flags_ut::flags_all, x_notify_ir_sen_configure::message, x_notify::message, ir_sen_data_t::module_status, module_status_t::projected, SCAN_FREQ, ir_sen_data_t::sv_errors_flags, ir_sen_data_t::sv_task_event, ir_sen_data_t::sv_timer_ntf, SV_TIMER_PERIOD, configured_t::sys_freq, x_delete_timer(), X_MS2TICK, X_NTF_CLR_ALARM_IR_SEN, X_NTF_INIT, X_NTF_IR_SENSOR_CONFIG, X_NTF_IR_SENSOR_SV_TIMER, x_schedule_timer(), and x_send_event().
Referenced by main().
{
    switch(notify->message)
    {
        case X_NTF_INIT:
        {
            ir_sen_init();
        }break;
        case X_NTF_IR_SENSOR_CONFIG:
        {
            // configuration details from algorithm module
            x_notify_ir_sen_configure * notify_configure = (
      x_notify_ir_sen_configure *)notify;
            ir_sen_data.configured = notify_configure->
      message.configured;
            ir_sen_data.disturbance_record = notify_configure->
      message.disturbance_record;
           ir_sen_data.module_status.projected.angular_freq =
      2*PI*ir_sen_data.configured.sys_freq;
           ir_sen_data.module_status.projected.samples_per_period =
      (Uint16)(SCAN_FREQ/(Float32)(ir_sen_data.
      configured.sys_freq));
           ir_sen_data.module_status.projected.samples_per_period_1_2 =
      ir_sen_data.module_status.projected.samples_per_period/2;
           ir_sen_data.module_status.projected.samples_per_period_1_4 =
      ir_sen_data.module_status.projected.samples_per_period/4;
           ir_sen_data.module_status.projected.samples_per_period_1_8 =
      ir_sen_data.module_status.projected.samples_per_period/8;
            // Clear supervison state (so errors will be reported if module have internal error)
          ir_sen_data.sv_errors_flags.flags_all = 0;
          x_delete_timer(&ir_sen_data.sv_timer_ntf);
          if(ir_sen_data.configured.element_status_sv_en)
          x_schedule_timer(&ir_sen_data.sv_timer_ntf,
      X_MS2TICK(SV_TIMER_PERIOD));
        }break;
         case X_NTF_CLR_ALARM_IR_SEN:
        {
           // Algorithm module alarm reset request
            // ir_sen_data.module_status.current.state = STATE_0;
             ir_sen_mark_false_postives();
             ir_sen_mark_false_postives();
             ir_sen_mark_false_postives();
        }break;
        case X_NTF_IR_SENSOR_SV_TIMER:
        {
           x_send_event(&ir_sen_data.sv_task_event);
        }break;
        default:
        {
            ASSERT(0);
        }
    }
}
void ir_sen_taskx (x_event * event)
ir sensor module task function.
Parameters
in event - system distributed event
Definition at line 69 of file ir_sensor.c.
References configured_t::amp_treshold, ASSERT, ir_sen_data_t::configured, ir_sen_data_t::diagonesis_records, sv_error_flags_ut::flags_all, x_event::message, x_notify_module_sv_status_report_t::message, x_notify_module_sv_status_report_t::notify, diagonesis_records_light_t::signal_history, srv_wdg_kick, ir_sen_data_t::sv_errors_flags, ir_sen_data_t::sv_status_ntf, X_MSG_IR_SENSOR_SV, and x_send_notify().
Referenced by main().
{
    switch(event->message)
    {
        case X_MSG_IR_SENSOR_SV:
        {
            srv_wdg_kick();
            ir_sen_sensor_element_sv_task();
            if(ir_sen_data.diagonesis_records.
      signal_history.amp.total_observation >0)
                ir_sen_data.diagonesis_records.
      signal_history.amp.avg =
                        (ir_sen_data.diagonesis_records.
      signal_history.amp.accumulated/
                        ir_sen_data.diagonesis_records.
      signal_history.amp.total_observation);
            if(ir_sen_data.diagonesis_records.
      signal_history.amp_exceded.total_observation >0){
                ir_sen_data.diagonesis_records.
      signal_history.amp_exceded.avg =
                        (ir_sen_data.diagonesis_records.
      signal_history.amp_exceded.accumulated/
                        ir_sen_data.diagonesis_records.
      signal_history.amp_exceded.total_observation);
                 
                ir_sen_data.diagonesis_records.
      signal_history.th_gap.avg
                    = (ir_sen_data.diagonesis_records.
      signal_history.amp_exceded.avg - ir_sen_data.configured.
      amp_treshold.set_value);
            }
            else
            ir_sen_data.diagonesis_records.
      signal_history.th_gap.avg
                    = (ir_sen_data.diagonesis_records.
      signal_history.amp.avg - ir_sen_data.configured.
      amp_treshold.set_value);
              ir_sen_data.diagonesis_records.
      signal_history.amp.accumulated = 0;
              ir_sen_data.diagonesis_records.
      signal_history.amp.total_observation = 0;
              ir_sen_data.diagonesis_records.
      signal_history.amp_exceded.accumulated = 0;
              ir_sen_data.diagonesis_records.
      signal_history.amp_exceded.total_observation = 0;
           
             ir_sen_threshold_adjustment_task();
            if((ir_sen_data.sv_errors_flags.flags_all!=0) || (
      ir_sen_data.configured.amp_treshold.adjusted == 1)){
             ir_sen_data.sv_status_ntf.message.error_flags =
      ir_sen_data.sv_errors_flags;
             ir_sen_data.sv_status_ntf.message.config =
      ir_sen_data.configured;
             // Send notification to Algorithm module about detected error or about change in threshold
       values
             x_send_notify(&ir_sen_data.sv_status_ntf.
      notify);
             ir_sen_data.sv_errors_flags.flags_all =0;
             ir_sen_data.configured.amp_treshold.adjusted = 0;
            }
        }break;
        default:
        {
            ASSERT(0);
        }
    }
}
Variable Documentation
Uint32 ir_event_trigger_timestamp
Definition at line 26 of file ir_sensor.c.
x_task_id ir_sen_id
ir_sen module handle
Definition at line 23 of file ir_sensor.c.
Referenced by main().