light_sensor.c File Reference
Module responsible for light sensor element supervision.
#include `..\..\includes\allheaders.h`
*
#include `..\..\includes_prv\aq0X\light_sensor_prv.h`
*
Functions
void light_sen_taskx (x_event *event)
light sensor module task function.
void light_sen_notifyx (x_notify *notify)
light module notification function.
Float32 light_sen_first_order_derivative (Uint16 final_val, Uint16 init_val, Float32 period)
Claculate first order derivative.
Float32 light_sen_calc_probablity (void)
Claculate the probablity that the event is true.
event_report_t light_sen_get_status (Uint16 adc_value, Bool save_event)
Supervise the status of the light sensor.
void light_sen_sensor_element_sv_task (void)
Supervises light sensors element by measuring sensor respond for different illumination level.
void light_sen_false_positive_adjustment_task (void)
checks the number of false positives within supervision (100ms | 5 cycle) time window
void light_sen_mark_false_postives (void)
checks the number of false positives within supervision (100ms | 5 cycle) time window
Variables
light_sen_data_t light_sen_data
Internal light_sen module data.
x_task_id light_sen_id
ir_sen module handle
Detailed Description
Module responsible for light sensor element supervision.
Definition in file light_sensor.c.
Function Documentation
Float32 light_sen_calc_probablity (void)
Claculate the probablity that the event is true.
Parameters
ad_value
Definition at line 184 of file light_sensor.c.
References light_sen_data_t::disturbance_record, module_disturbance_record_t::event_positive_cnt, and module_disturbance_record_t::observation_cnt.
Referenced by light_sen_get_status().
                                       {
    return (Float32)light_sen_data.disturbance_record->
      event_positive_cnt
            /
           (Float32)light_sen_data.disturbance_record->
      observation_cnt;
}
void light_sen_false_positive_adjustment_task (void)
checks the number of false positives within supervision (100ms | 5 cycle) time window
TODO: if level also is lower than the min gap from the current signal level adjust down to the level
Definition at line 441 of file light_sensor.c.
References sv_error_flags_ut::bits, light_sen_data_t::configured, configured_t::dfdt_treshold_max, light_sen_data_t::diagonesis_records, diagonesis_records_light_t::false_alarm, FALSE_POSITIVE_TOLERANCE_LIMIT, light_sen_data_t::sv_errors_flags, and configured_t::threshold_adjust_manual.
Referenced by light_sen_taskx().
                                                   {
    if(
     (light_sen_data.diagonesis_records.
      false_alarm.dfdt_max_exceded.cnt < FALSE_POSITIVE_TOLERANCE_LIMIT)
          &&
     (light_sen_data.diagonesis_records.
      false_alarm.amp_max_exceded.cnt < FALSE_POSITIVE_TOLERANCE_LIMIT)
     ){
      light_sen_data.sv_errors_flags.bits.FALSE_POSITIVE_AMP_TH = 0;
      light_sen_data.sv_errors_flags.bits.FALSE_POSITIVE_DFDT_TH = 0;
      memset(&light_sen_data.diagonesis_records.
      false_alarm,0,sizeof(light_sen_data.diagonesis_records.
      false_alarm));
      return;
    }
      if(light_sen_data.diagonesis_records.
      false_alarm.dfdt_max_exceded.cnt > FALSE_POSITIVE_TOLERANCE_LIMIT)
      {
          light_sen_data.sv_errors_flags.bits.FALSE_POSITIVE_DFDT_TH = 1;
         if(!light_sen_data.configured.
      threshold_adjust_manual)
          //TODO: varifiy this will correct the problem
          light_sen_data.configured.dfdt_treshold_max +=
          light_sen_data.diagonesis_records.
      false_alarm.dfdt_max_exceded.recorded_avg +
          light_sen_data.diagonesis_records.
      false_alarm.dfdt_max_exceded.recorded_avg*0.01;
      }
      if(light_sen_data.diagonesis_records.
      false_alarm.amp_max_exceded.cnt > FALSE_POSITIVE_TOLERANCE_LIMIT){
          light_sen_data.sv_errors_flags.bits.FALSE_POSITIVE_AMP_TH = 1;
          light_sen_data.configured.amp_treshold_max +=
          light_sen_data.diagonesis_records.
      false_alarm.amp_max_exceded.recorded_avg +
          light_sen_data.diagonesis_records.
      false_alarm.amp_max_exceded.recorded_avg*0.001;
           memset(&light_sen_data.diagonesis_records.
      false_alarm,0,sizeof(light_sen_data.diagonesis_records.
      false_alarm));
      }
}
Float32 light_sen_first_order_derivative (Uint16 final_val, Uint16 init_val, Float32 period)
Claculate first order derivative.
Parameters
ad_value
Definition at line 172 of file light_sensor.c.
Referenced by light_sen_get_status().
                                                                                         {
    return (Float32)(final_val-init_val)/period;
}
event_report_t light_sen_get_status (Uint16 adc_value, Bool save_event)
Supervise the status of the light sensor.
Parameters
ad_value
For every sample, pre activation data is saved in a circular buffer at the provided storage location
because both events are expected after fast rise in signal, we mark as positive event
Definition at line 204 of file light_sensor.c.
References ASSERT, pre_act_record_buffer_t::buffer, state_data_light_t::change_per_time, light_sen_data_t::configured, module_status_t::current, data_non_volatile, configured_t::dfdt_treshold_max, light_sen_data_t::disturbance_record, pre_act_record_buffer_t::elapsed, EMU_MODE_DATA_LENGTH, module_disturbance_record_t::event_data, module_disturbance_record_t::event_positive_cnt, FALSE, FAST_TIMER_SAMPLING_RATE, event_report_t::fields, pre_act_record_buffer_t::head, HOT, light_sen_calc_probablity(), light_sen_first_order_derivative(), light_sen_mark_false_postives(), logv, configured_t::min_number_of_observation, light_sen_data_t::module_status, module_disturbance_record_t::observation_cnt, module_disturbance_record_t::post_act_data, POST_ACT_RECORD_BUFF_SIZE, module_disturbance_record_t::pre_act_data, PRE_ACT_RECORD_BUFF_SIZE, module_status_t::previous, configured_t::probablity_treshold_max, configured_t::probablity_treshold_min, RANGE_MAX_16BIT, state_data_light_t::signal_level, state_data_light_t::state, STATE_0, STATE_1, STATE_2, pre_act_record_buffer_t::tail, logv_t::tick, logv_t::trip_active, and TRUE.
{
    event_report_t status;
    status.fields.active_signal= FALSE;
    light_sen_data.module_status.previous =
      light_sen_data.module_status.current;
    light_sen_data.module_status.current.
      signal_level = adc_value;
    light_sen_data.module_status.current.
      change_per_time = light_sen_first_order_derivative(
                                            light_sen_data.
      module_status.current.signal_level,
                                            light_sen_data.
      module_status.previous.signal_level,
                                            FAST_TIMER_SAMPLING_RATE
                                            );
    if(light_sen_data.module_status.current.
      change_per_time > 0)
        status.fields.active_signal = TRUE;
 
    if(logv.trip_active == TRUE){
    if(light_sen_data.disturbance_record->
      post_act_data.head <
        ((data_non_volatile.disturbance_record.light.emu_data_en==
      FALSE)?POST_ACT_RECORD_BUFF_SIZE:(
      POST_ACT_RECORD_BUFF_SIZE-EMU_MODE_DATA_LENGTH)))
      light_sen_data.disturbance_record->
      post_act_data.buffer.all[light_sen_data.
      disturbance_record->post_act_data.head++] = adc_value;
    }else{
    light_sen_data.disturbance_record->
      pre_act_data.buffer[light_sen_data.
      disturbance_record->pre_act_data.head] = adc_value;
    light_sen_data.disturbance_record->
      pre_act_data.head
            = (light_sen_data.disturbance_record->
      pre_act_data.head + 1)%PRE_ACT_RECORD_BUFF_SIZE;
    if(light_sen_data.disturbance_record->
      pre_act_data.elapsed == TRUE)
    light_sen_data.disturbance_record->
      pre_act_data.tail
            = (light_sen_data.disturbance_record->
      pre_act_data.head + 1)%PRE_ACT_RECORD_BUFF_SIZE;
    else
    if(light_sen_data.disturbance_record->
      pre_act_data.head == PRE_ACT_RECORD_BUFF_SIZE - 1)
    light_sen_data.disturbance_record->
      pre_act_data.elapsed = TRUE;
    }
    light_sen_data.disturbance_record->
      event_data.exceeded_threshold.all = 0;
    if(light_sen_data.module_status.current.
      change_per_time > light_sen_data.configured.
      dfdt_treshold_max)
        light_sen_data.disturbance_record->
      event_data.exceeded_threshold.bits.dfdt_max = 1;
    if(light_sen_data.module_status.current.
      signal_level > light_sen_data.configured.amp_treshold_max)
        light_sen_data.disturbance_record->
      event_data.exceeded_threshold.bits.amp_max = 1;
 
    switch(light_sen_data.module_status.current.
      state)
    {
        case STATE_0:
        {
            if(light_sen_data.disturbance_record->
      event_data.exceeded_threshold.all !=0){
              light_sen_data.disturbance_record->
      event_data.event_history = 0;
            light_sen_data.disturbance_record->
      observation_cnt = 1;
            light_sen_data.disturbance_record->
      event_positive_cnt = 1;
            light_sen_data.disturbance_record->
      event_data.buffer.signal_level[0] = light_sen_data.
      module_status.current.signal_level;
            light_sen_data.disturbance_record->
      event_data.buffer.change_per_time[0] = light_sen_data.
      module_status.current.change_per_time;
            light_sen_data.disturbance_record->
      event_data.buffer.head_ptr++;
            light_sen_data.disturbance_record->
      event_data.timestamp = logv.tick;
            light_sen_data.disturbance_record->
      event_data.event_probability = light_sen_calc_probablity();
            if(light_sen_data.disturbance_record->
      event_data.exceeded_threshold.bits.amp_max){
                light_sen_data.module_status.current.
      state = STATE_2;
            }else{
              light_sen_data.module_status.current.
      state = STATE_1;
              light_sen_data.disturbance_record->
      event_data.event_history++;
            }
            }
        }break;
         case STATE_1:
        {
             light_sen_data.disturbance_record->
      observation_cnt++;
            if(light_sen_data.disturbance_record->
      event_data.buffer.head_ptr < EVENT_OBSERVATION_RECORD_LENGTH){
            light_sen_data.disturbance_record->
      event_data.buffer.signal_level[light_sen_data.
      disturbance_record->event_data.buffer.head_ptr]
                    = light_sen_data.module_status.
      current.signal_level;
            light_sen_data.disturbance_record->
      event_data.buffer.change_per_time[light_sen_data.
      disturbance_record->event_data.buffer.head_ptr]
                    = light_sen_data.module_status.
      current.change_per_time;
            light_sen_data.disturbance_record->
      event_data.buffer.head_ptr++;
            }
            if(light_sen_data.disturbance_record->
      event_data.exceeded_threshold.all!=0)
                 light_sen_data.disturbance_record->
      event_positive_cnt++;
            light_sen_data.disturbance_record->
      event_data.event_probability = light_sen_calc_probablity();
            if(light_sen_data.disturbance_record->
      event_data.exceeded_threshold.bits.amp_max){
                light_sen_data.module_status.current.
      state = STATE_2;
            }else
                 light_sen_data.disturbance_record->
      event_data.event_history++;
       
            if(light_sen_data.disturbance_record->
      observation_cnt
                >=
                light_sen_data.configured.
      min_number_of_observation
               ){
               
                   if(light_sen_data.disturbance_record->
      event_data.event_probability
                    >
                    light_sen_data.configured.
      probablity_treshold_max
                    ){
                         light_sen_data.module_status.
      current.state = HOT;
                         light_sen_data.disturbance_record->
      post_act_data.head=0;
                     }else{
                         light_sen_data.module_status.
      current.state = STATE_0;
                         light_sen_mark_false_postives();
                    }
             }
             
        }break;
          case STATE_2:
        {
            light_sen_data.disturbance_record->
      observation_cnt++;
            if(light_sen_data.disturbance_record->
      event_data.exceeded_threshold.bits.amp_max)
                light_sen_data.disturbance_record->
      event_positive_cnt++;
            if(light_sen_data.disturbance_record->
      event_data.buffer.head_ptr < EVENT_OBSERVATION_RECORD_LENGTH){
            light_sen_data.disturbance_record->
      event_data.buffer.signal_level[light_sen_data.
      disturbance_record->event_data.buffer.head_ptr]
                    = light_sen_data.module_status.
      current.signal_level;
            light_sen_data.disturbance_record->
      event_data.buffer.change_per_time[light_sen_data.
      disturbance_record->event_data.buffer.head_ptr]
                    = light_sen_data.module_status.
      current.change_per_time;
            light_sen_data.disturbance_record->
      event_data.buffer.head_ptr++;
            }
              if(light_sen_data.disturbance_record->
      observation_cnt
                >=
                light_sen_data.configured.
      min_number_of_observation
               ){
                   if(light_sen_data.disturbance_record->
      event_data.event_probability
                    >
                    light_sen_data.configured.
      probablity_treshold_max
                    ){
                         light_sen_data.module_status.
      current.state = HOT;
                         light_sen_data.disturbance_record->
      post_act_data.head=0;
                     }else{
                         light_sen_data.module_status.
      current.state = STATE_0;
                         light_sen_mark_false_postives();
                    }
             }
         }break;
         case HOT:
        {
             light_sen_data.disturbance_record->
      observation_cnt++;
            if(light_sen_data.disturbance_record->
      event_data.buffer.head_ptr < EVENT_OBSERVATION_RECORD_LENGTH){
            light_sen_data.disturbance_record->
      event_data.buffer.signal_level[light_sen_data.
      disturbance_record->event_data.buffer.head_ptr]
                    = light_sen_data.module_status.
      current.signal_level;
            light_sen_data.disturbance_record->
      event_data.buffer.change_per_time[light_sen_data.
      disturbance_record->event_data.buffer.head_ptr]
                    = light_sen_data.module_status.
      current.change_per_time;
            light_sen_data.disturbance_record->
      event_data.buffer.head_ptr++;
            }
            if(light_sen_data.disturbance_record->
      event_data.exceeded_threshold.all != 0)
                light_sen_data.disturbance_record->
      event_positive_cnt++;
            
             light_sen_data.disturbance_record->
      event_data.event_probability = light_sen_calc_probablity();
             if(light_sen_data.disturbance_record->
      event_data.event_probability < light_sen_data.configured.
      probablity_treshold_min){
                 light_sen_data.module_status.current.
      state = STATE_0;
                 light_sen_mark_false_postives();
             }
             if(light_sen_data.disturbance_record->
      observation_cnt > RANGE_MAX_16BIT - 1
                ||
                light_sen_data.disturbance_record->
      event_positive_cnt > RANGE_MAX_16BIT - 1
                ){
             //Prevents overflow
              light_sen_data.disturbance_record->
      observation_cnt /=10;
              light_sen_data.disturbance_record->
      event_positive_cnt /=10;
             }
        }break;
        default:
        {
            ASSERT(0);
        }
    }
  status.fields.state = light_sen_data.module_status.
      current.state;
  return status;
}
void light_sen_mark_false_postives (void)
checks the number of false positives within supervision (100ms | 5 cycle) time window
Definition at line 491 of file light_sensor.c.
References light_sen_data_t::configured, configured_t::dfdt_treshold_max, light_sen_data_t::diagonesis_records, light_sen_data_t::disturbance_record, module_disturbance_record_t::event_data, EXCEDED_AMP_TH, diagonesis_records_light_t::false_alarm, RANGE_MAX_32BIT, and RANGE_MAX_8BIT.
Referenced by light_sen_get_status(), and light_sen_notifyx().
                                        {
        if(light_sen_data.disturbance_record->
      event_data.event_history == EXCEDED_AMP_TH){
               if(
                (light_sen_data.diagonesis_records.
      false_alarm.amp_max_exceded.cnt < RANGE_MAX_8BIT)
                &
                (light_sen_data.diagonesis_records.
      false_alarm.amp_max_exceded.accumulated_value < RANGE_MAX_32BIT)
               )
               {
                     light_sen_data.diagonesis_records.
      false_alarm.amp_max_exceded.cnt++;
                     light_sen_data.diagonesis_records.
      false_alarm.amp_max_exceded.accumulated_value
                     +=(light_sen_data.disturbance_record->
      event_data.buffer.signal_level[0]-light_sen_data.
      configured.amp_treshold_max);
                     light_sen_data.diagonesis_records.
      false_alarm.amp_max_exceded.recorded_avg
                     = light_sen_data.diagonesis_records.
      false_alarm.amp_max_exceded.accumulated_value/
                             (Float32)light_sen_data.
      diagonesis_records.false_alarm.amp_max_exceded.cnt;
              }
             }else{
             if(
                (light_sen_data.diagonesis_records.
      false_alarm.dfdt_max_exceded.cnt < RANGE_MAX_8BIT)
                &
                (light_sen_data.diagonesis_records.
      false_alarm.dfdt_max_exceded.accumulated_value < RANGE_MAX_32BIT)
               )
             {
                 light_sen_data.diagonesis_records.
      false_alarm.dfdt_max_exceded.cnt++;
                 light_sen_data.diagonesis_records.
      false_alarm.dfdt_max_exceded.accumulated_value
                 +=(light_sen_data.disturbance_record->
      event_data.buffer.change_per_time[0]-light_sen_data.
      configured.dfdt_treshold_max);
                 light_sen_data.diagonesis_records.
      false_alarm.dfdt_max_exceded.recorded_avg
                 = light_sen_data.diagonesis_records.
      false_alarm.dfdt_max_exceded.accumulated_value/
                    (Float32)light_sen_data.
      diagonesis_records.false_alarm.dfdt_max_exceded.cnt;
             }
             }
}
void light_sen_notifyx (x_notify * notify)
light module notification function.
Parameters
in notify - system distributed notification
Definition at line 106 of file light_sensor.c.
References ASSERT, light_sen_data_t::configured, module_status_t::current, light_sen_data_t::disturbance_record, configured_t::element_status_sv_en, sv_error_flags_ut::flags_all, light_sen_mark_false_postives(), x_notify_light_sen_configure::message, x_notify::message, light_sen_data_t::module_status, state_data_light_t::state, STATE_0, light_sen_data_t::sv_errors_flags, light_sen_data_t::sv_task_event, light_sen_data_t::sv_timer_ntf, SV_TIMER_PERIOD, x_delete_timer(), X_MS2TICK, X_NTF_INIT, X_NTF_LIGHT_SENSOR_CONFIG, X_NTF_LIGHT_SENSOR_SV_TIMER, x_schedule_timer(), and x_send_event().
Referenced by main().
{
    
    switch(notify->message)
    {
        case X_NTF_INIT:
        {
            light_sen_init();
        }break;
        case X_NTF_LIGHT_SENSOR_CONFIG:
        {
            // configuration details from algorithm module
            x_notify_light_sen_configure * notify_configure = (
      x_notify_light_sen_configure *)notify;
           
            light_sen_data.configured = notify_configure->
      message.configured;
            light_sen_data.disturbance_record = notify_configure->
      message.disturbance_record;
            // Clear supervison state (so errors will be reported if module have internal error)
             light_sen_data.sv_errors_flags.
      flags_all = 0;
          x_delete_timer(&light_sen_data.
      sv_timer_ntf);
          if(light_sen_data.configured.
      element_status_sv_en)
          x_schedule_timer(&light_sen_data.
      sv_timer_ntf,X_MS2TICK(SV_TIMER_PERIOD));
        }break;
         case X_NTF_CLR_ALARM:
        {
           // Algorithm module alarm reset request
             light_sen_data.module_status.current.
      state = STATE_0;
             light_sen_mark_false_postives();
        }break;
        
        case X_NTF_LIGHT_SENSOR_SV_TIMER:
        {
           x_send_event(&light_sen_data.sv_task_event);
        }break;
        
       
        default:
        {
            ASSERT(0);
        }
    }
}
void light_sen_sensor_element_sv_task (void)
Supervises light sensors element by measuring sensor respond for different illumination level.
Definition at line 426 of file light_sensor.c.
Referenced by light_sen_taskx().
{
}
void light_sen_taskx (x_event * event)
light sensor module task function.
Parameters
in event - system distributed event
Definition at line 65 of file light_sensor.c.
References ASSERT, sv_error_flags_ut::flags_all, light_sen_false_positive_adjustment_task(), light_sen_sensor_element_sv_task(), x_notify_light_sen_sv_report::message, x_event::message, x_notify_light_sen_sv_report::notify, light_sen_data_t::sv_errors_flags, light_sen_data_t::sv_status_ntf, X_MSG_LIGHT_SENSOR_SV, and x_send_notify().
Referenced by main().
{
    switch(event->message)
    {
    
        case X_MSG_LIGHT_SENSOR_SV:
        {
            light_sen_sensor_element_sv_task();
            light_sen_false_positive_adjustment_task();
            if(light_sen_data.sv_errors_flags.
      flags_all!=0){
             light_sen_data.sv_status_ntf.message.error_status_flags.
      flags_all = light_sen_data.sv_errors_flags.flags_all;
             // Send notification to Algorithm module about detected error
             x_send_notify(&light_sen_data.
      sv_status_ntf.notify);
             light_sen_data.sv_errors_flags.
      flags_all =0;
            }
            
        }break;
      
        
        default:
        {
            ASSERT(0);
        }
    }
}
Variable Documentation
light_sen_data_t light_sen_data
Internal light_sen module data.
Definition at line 14 of file light_sensor.c.
x_task_id light_sen_id
ir_sen module handle
Definition at line 15 of file light_sensor.c.
Referenced by main().