algorithm.c File Reference
#include `..\..\includes\allheaders.h`
*
#include `..\..\includes_prv\aq0X\algorithm_prv.h`
*
#include `..\..\includes_prv\aq0X\srv_hwio_prv.h`
*
#include `dsp.h`
*
#include <string.h>
*
Macros
#define NETIVE_ARITHMETIC 1
Functions
Float32 algorithm_get_mean (Uint16 *vector, Uint16 SIZE)
calculates mean value
int meanVal __attribute__ ((space(ymemory), far()))
calculates the standard deviation of the vector
Float32 algorithm_get_std_deviation (Uint16 *vector, Float32 mean_val, Uint16 SIZE)
Bool algorithm_signal_proportionality (Uint16 *vector1, Uint16 *vector2, Uint16 SIZE)
The function calculate the relation between the given vectors and standard deviation of the resulting vector to determine the similarity between the two signals.
void algorithm_sv_scan_timer_init (void)
Low level analog.
void algorithm_wake (Uint8 event)
Main processing loop for algorithm module.
void msg_to_mem (void *dest, Uint8 *msg, Uint16 size, Uint8 base)
copy serially received data to given memory address
void algorithm_taskx (x_event *event)
Algorithm task function.
void algorithm_notifyx (x_notify *notify)
Algorithm module notification function.
void algorithm_message_arrived_ntf_isr (Uint16 id)
Causes that system will send notification to the module as this cannot be done directly because the function is called from interrupt.
Variables
algorithm_data_t algorithm_data
x_task_id algorithm_id
ALgorithm module handle.
logv_t logv
Macro Definition Documentation
#define NETIVE_ARITHMETIC 1
Definition at line 27 of file algorithm.c.
Function Documentation
int meanVal __attribute__ ((space(ymemory), far()))
calculates the standard deviation of the vector
Float32 algorithm_get_mean (Uint16 * vector, Uint16 SIZE)
calculates mean value
Definition at line 47 of file algorithm.c.
{
    
    
    register int result asm("A");
    result = __builtin_clr();
    Int16 cc;
    for(cc = 0;cc<SIZE;cc++)
        result = __builtin_add(result,*(vector+cc),0);
 
    cc = __builtin_sac(result,0);
    
    Float32 mean_val = (Float32)cc/(Float32)SIZE ;
    
    return (mean_val);
}
Float32 algorithm_get_std_deviation (Uint16 * vector, Float32 mean_val, Uint16 SIZE)
Definition at line 96 of file algorithm.c.
Referenced by nov_set_default().
{
    Uint16 cc;
    fractional *vect = (fractional *)vector;
    fractional uval = (fractional)(mean_val);
    Int16 tmp = 0;
    Int32 variance = 0;
  
    for(cc = 0;cc < SIZE ; cc++){
          tmp = ((*(vect+cc)) - uval);
          variance += __builtin_mulss(tmp,tmp);
    }
    Float32 result = sqrt(((Float32)variance)/((Float32)SIZE));
  
    return result;
}
void algorithm_message_arrived_ntf_isr (Uint16 id)
Causes that system will send notification to the module as this cannot be done directly because the function is called from interrupt.
Definition at line 2104 of file algorithm.c.
References algorithm_id, algorithm_data_t::irq_src, and x_task_send_irq_sync().
Referenced by __attribute__(), and algorithm_wake().
{
    if(id==0)
        return;
    if((0x00FF&id)!=0)
    algorithm_data.irq_src.fields.external = (0x00FF&id);
    else if(((0xFF00&id)>>8)!=0)
    algorithm_data.irq_src.fields.internal = ((0xFF00&id)>>8);
    x_task_send_irq_sync(algorithm_id);
}
void algorithm_notifyx (x_notify * notify)
Algorithm module notification function.
Parameters
in notify - system distributed notification
Services initialization notifications. Collects notifications from all other modules and internal OS timers (data is copied to internal data structures). Such operation triggers sending wake event to main task to process notification data.
Definition at line 2006 of file algorithm.c.
References algorithm_wake(), ASSERT, data_non_volatile, x_notify::message, x_notify_module_sv_status_report_t::message, algorithm_data_t::wake_event, X_NTF_ALG_ANALOG_SUPPLY_ALERT, X_NTF_INIT, X_NTF_IR_SENSOR_SV_ALART, X_NTF_LIGHT_SENSOR_SV_ALART, X_NTF_MFIELD_X_SENSOR_SV_ALART, X_NTF_MFIELD_Y_SENSOR_SV_ALART, X_NTF_SUPERVISION_TIMER, X_NTF_UV_SENSOR_SV_ALART, and x_send_event().
Referenced by main().
{
    switch(notify->message)
    {
        // System standrd messages
        case X_NTF_INIT:
        {
            // Module intialization
            algorithm_init();
        }break;
        case X_NTF_SUPERVISION_TIMER:
        {
           x_send_event(&algorithm_data.wake_event);
        }break;
        case X_NTF_ALG_ANALOG_SUPPLY_ALERT:
        {
            data_non_volatile.device_data.sv_record.system_error_flags.bits.power_supply =
       1;
            algorithm_wake(0);
        }break;
#if(DEVICE == AQ0X_V1)
         case X_NTF_LIGHT_SENSOR_SV_ALART:
        {
            // supervission report indicating persistent error or when change is made on configured data
            x_notify_module_sv_status_report_t *alarm = (
      x_notify_module_sv_status_report_t *)notify;
            data_non_volatile.device_data.sv_record.error_flags.light = alarm->
      message.error_flags;
             x_send_event(&algorithm_data.wake_event);
        }break;
#endif
         case X_NTF_IR_SENSOR_SV_ALART:
        {
            // supervission report indicating persistent error or when change is made on configured data
            x_notify_module_sv_status_report_t *alarm = (
      x_notify_module_sv_status_report_t *)notify;
            data_non_volatile.device_data.sv_record.error_flags.ir = alarm->
      message.error_flags;
            if(alarm->message.config.amp_treshold.adjusted == 1)
                data_non_volatile.device_data.installation.thresholds.ir_level_max
                 = alarm->message.config.amp_treshold.set_value;
        }break;
         case X_NTF_UV_SENSOR_SV_ALART:
        {
            // supervission report indicating persistent error or when change is made on configured data
            x_notify_module_sv_status_report_t * alarm = (
      x_notify_module_sv_status_report_t *)notify;
            data_non_volatile.device_data.sv_record.error_flags.uv = alarm->
      message.error_flags;
             if(alarm->message.config.amp_treshold.adjusted == 1)
                data_non_volatile.device_data.installation.thresholds.uv_level_max
                 =alarm->message.config.amp_treshold.set_value;
        }break;
        case X_NTF_MFIELD_X_SENSOR_SV_ALART:
        {
            // supervission report indicating persistent error
            x_notify_module_sv_status_report_t * alarm = (
      x_notify_module_sv_status_report_t *)notify;
            data_non_volatile.device_data.sv_record.error_flags.mfield_x = alarm->
      message.error_flags;
      
        }break;
#ifdef MFIELD_Y
        case X_NTF_MFIELD_Y_SENSOR_SV_ALART:
        {
            // supervission report indicating persistent error
            x_notify_module_sv_status_report_t * alarm = (
      x_notify_module_sv_status_report_t *)notify;
            data_non_volatile.device_data.sv_record.error_flags.mfield_y = alarm->
      message.error_flags;
            
        }break;
#endif
        default:
        {
            ASSERT(0);
        }
        
    }
}
Bool algorithm_signal_proportionality (Uint16 * vector1, Uint16 * vector2, Uint16 SIZE)
The function calculate the relation between the given vectors and standard deviation of the resulting vector to determine the similarity between the two signals.
Definition at line 242 of file algorithm.c.
References FALSE, MAX_EVENT_OBSERVATION_LENGTH, and TRUE.
{
    Float32 vector[MAX_EVENT_OBSERVATION_LENGTH];
    long double sum=0;
    Uint8 cc = 0;
  
    for(cc = 0;cc < SIZE;cc++){
        vector[cc] = (Float32)*(vector1 + cc)/(Float32)*(vector2 + cc);
        sum += vector[cc];
    }
    Float32 mean = sum/SIZE;
    sum = 0;
    for(cc = 0;cc<SIZE;cc++)
        sum += pow((vector[cc]-mean),2);
    Float32 deviation = sum/SIZE;
    if(deviation < 0.1 /*less than 10% deviation*/)
        return TRUE;
    else
        return FALSE;
}
void algorithm_sv_scan_timer_init (void)
Low level analog.
Definition at line 543 of file algorithm.c.
References FOSC_CPU, and SCAN_FREQ.
{
    // Setup fast timer for analog level polling
    T1CONbits.TON = 0; // Disable Timer
    T1CON = 0; // Clear the register
    T1CONbits.TCS = 0; // Internal clock Fosc/4
    T1CONbits.TGATE = 0; // Disable Gated Timer mode
    T1CONbits.TCKPS = 0; // 1:1 prescaling
    TMR1 = 0x00; // Clear timer register
    PR1 = (FOSC_CPU/2)/SCAN_FREQ;
    IPC0bits.T1IP = 0x06; // Set Timer1 Interrupt Priority Level
    IFS0bits.T1IF = 0; // Clear the Timer1 Interrupt Flag
    IEC0bits.T1IE = 1; // Enable Timer1 Interrupt Service Routine
    T1CONbits.TON = 1; //Start Timer 1
}
void algorithm_taskx (x_event * event)
Algorithm task function.
Processes incoming events. more than 80% correlation is considered as strong similarity
Definition at line 1905 of file algorithm.c.
References ASSERT, algorithm_data_t::clear_alarm_ir, algorithm_data_t::clear_alarm_mfield_x, algorithm_data_t::clear_alarm_uv, data_non_volatile, algorithm_data_t::diagnosis, logv_t::disturbance_record, FP_TOLERANCE, IRQ_DR_READY, IRQ_SOURCE_HIF_EVENT, IRQ_SOURCE_SERIAL, algorithm_data_t::irq_src, x_event::message, nov_store(), srv_wdg_kick, algorithm_data_t::supervision_timer, SV_TIMER_PERIOD, TRUE, x_delete_timer(), X_MS2TICK, X_MSG_CONFIGURE_EVENT, X_MSG_IRQ_SYNC, X_MSG_WAKE_EVENT, x_schedule_timer(), and x_send_notify().
Referenced by main().
{
    switch(event->message)
    {
        case X_MSG_IRQ_SYNC:
        {
             srv_wdg_kick();
            if(algorithm_data.irq_src.fields.external != 0){
                    if(algorithm_data.irq_src.all ==
      IRQ_SOURCE_SERIAL)
                    algorithm_cmd_handler();
                  algorithm_data.irq_src.fields.external = 0;
            }
            if(algorithm_data.irq_src.fields.internal != 0){
                    if(algorithm_data.irq_src.all ==
      IRQ_SOURCE_HIF_EVENT){
                        Float32 result = algorithm_liner_correlation(&
      data_non_volatile.disturbance_record.hif_diagonesis_records,
      MAX_EVENT_OBSERVATION_LENGTH);
                       //
      if(algorithm_liner_correlation(&data_non_volatile.disturbance_record.hif_diagonesis_records,MAX_EVENT_OBSERVATION_LENGTH) > 80){
                         if(result >= 80){
                            algorithm_data.diagnosis.hif.flags.result = 1;
                            algorithm_data.diagnosis.hif.flags.ready = 1;
                         }else{
                            algorithm_data.diagnosis.hif.flags.result = 0;
                            algorithm_data.diagnosis.hif.flags.ready = 1;
                            memset(&data_non_volatile.disturbance_record.
      hif_diagonesis_records,0,sizeof(data_non_volatile.disturbance_record.hif_diagonesis_records));
                         }
                    }
                    else
                    if(algorithm_data.irq_src.all ==
      IRQ_DR_READY)
                    {
                        
                        nov_store();
                        logv.disturbance_record.bits.ready = 1;
                    }
                    algorithm_data.irq_src.fields.internal = 0;
         }
        }break;
        case X_MSG_WAKE_EVENT:
        {
              if(algorithm_data.diagnosis.false_alarm.ir.cnt++ >
      FP_TOLERANCE)
              x_send_notify(&algorithm_data.
      clear_alarm_ir);
              if(algorithm_data.diagnosis.false_alarm.uv.cnt++ >
      FP_TOLERANCE)
              x_send_notify(&algorithm_data.
      clear_alarm_uv);
              if(algorithm_data.diagnosis.false_alarm.mfield_x.cnt++ >
      FP_TOLERANCE)
              x_send_notify(&algorithm_data.
      clear_alarm_mfield_x);
        }break;
        case X_MSG_CONFIGURE_EVENT:
        {
            algorithm_configure();
            data_non_volatile.device_data.installation.is_valid =
      TRUE;
#if(0)
          x_delete_timer(&algorithm_data.
      supervision_timer);
          x_schedule_timer(&algorithm_data.
      supervision_timer,X_MS2TICK(SV_TIMER_PERIOD));
#endif
        }break;
    
        default:
        {
            ASSERT(0);
        }break;
    
    };
}
void algorithm_wake (Uint8 event)
Main processing loop for algorithm module.
Processes events by examining bitfields for various notification reasons. more than 80% correlation is considered as strong similarity
After a valid trip, disturbance recorder data will be will be saved to the memory address allocated for this purpose. The process will take some time depending on the size of the data. Hence, delay counter will be armed so as to transfer the data to non volatile memory when ready.
disturbance record data ready, low priority function will be used, to transfer the data to non volatile memory.
reset emulation trip for comunication purpose
Definition at line 670 of file algorithm.c.
References algorithm_message_arrived_ntf_isr(), ASSERT, data_non_volatile, algorithm_data_t::diagnosis, logv_t::disturbance_record, DR_RECHECK, DR_RECHECK_TIME, srv_hwio_data_t::emulation_mode, EVENT_CLEARED, EVENT_SV_ALARM, FALSE, HIF, HOT, HWIO_ALARM_OFF, HWIO_ALARM_ON, hwio_execute_gpio_task(), ir_record_reset(), ir_sen_hif_check(), IRQ_CTX_T, IRQ_DISABLE, IRQ_DR_READY, IRQ_ENABLE, IRQ_SOURCE_HIF_EVENT, algorithm_data_t::modules_state_sv, nov_store(), srv_hwio_data, STATE_0, logv_t::sv_delay, logv_t::tick, logv_t::trip_active, TRUE, TYPE_IR_MF, TYPE_IR_MF_UV, and logv_t::wr.
Referenced by __attribute__(), and algorithm_notifyx().
{
    Bool result = FALSE;
    if((event == EVENT_SV_ALARM)&&(logv.trip_active ==
      FALSE)){
        if(algorithm_data.modules_state_sv.ir_sen.fields.state ==
      HOT){
        switch(data_non_volatile.device_data.installation.trip_criteria.criterion.all)
        {
                 case TYPE_IR_MF:
                {
                      if(
                          
                           (algorithm_data.modules_state_sv.mfield_x_sen.
      fields.state == HOT)
                            &&
                           (algorithm_data.modules_state_sv.uv_sen.fields.
      state > STATE_0)
                           )
                                result = TRUE;
                       else
                       if(ir_sen_hif_check() > 2)
                        result = TRUE;
                }break;
                 case TYPE_IR_MF_UV:
                {
                   if(
                        (algorithm_data.modules_state_sv.mfield_x_sen.fields.
      state == HOT)
                        &&
                        (algorithm_data.modules_state_sv.uv_sen.fields.state
      == HOT)
                        )
                            result = TRUE;
                       else if((algorithm_data.modules_state_sv.uv_sen.fields
      .state == HOT))
                       {
                                       if(algorithm_data.diagnosis.hif.flags.
      processing == 1){
                                           if(algorithm_data.
      diagnosis.hif.flags.ready == TRUE){
                                                if(algorithm_data.
      diagnosis.hif.flags.result == TRUE)
                                                {
                                                        algorithm_data.
      diagnosis.hif.flags.processing = 0;
                                                        ir_record_reset(
      HIF);
                                                        if((algorithm_data.
      modules_state_sv.uv_sen.fields.state == HOT))
                                                        result = TRUE;
                                                }
                                              else
                                                {
                                                    algorithm_data.
      diagnosis.hif.flags.processing = 0;
                                                    ir_record_reset(
      HIF);
                                                    algorithm_data_mark_false_postives();
                                                }
                                          }
                                     }
                                     else
                                     {
                                               if((ir_sen_hif_check() > 0))
                                               {
                                                   algorithm_data.
      diagnosis.hif.all = 0;
                                                   algorithm_data.
      diagnosis.hif.flags.processing = 1;
                                                       //linear correlation function requires about 200us
       to return,
                                                       //therefore,low priority function will be used to
       execute this procedure
                                                        
      algorithm_message_arrived_ntf_isr(
      IRQ_SOURCE_HIF_EVENT);
                                                        //TODO:clear all timers
                                               }
                                    }
                      }else
                          algorithm_data_mark_false_postives();
                }break;
                 default:
                {
                      if(
                        (algorithm_data.modules_state_sv.mfield_x_sen.fields.
      state == HOT)
                        &&
                        (algorithm_data.modules_state_sv.uv_sen.fields.state
      == HOT)
                        )
                            result = TRUE;
                       else if((algorithm_data.modules_state_sv.uv_sen.fields
      .state == HOT))
                       {
                           algorithm_data.diagnosis.hif_checklist.all =
      ir_sen_hif_check();
                           if((algorithm_data.diagnosis.hif_checklist.all > 0))
                           {
                               IRQ_CTX_T irq_ctx;
                               IRQ_DISABLE(irq_ctx);
                                 Float32 correlation_result = algorithm_liner_correlation(&
      data_non_volatile.disturbance_record.hif_diagonesis_records,
      MAX_EVENT_OBSERVATION_LENGTH);
                               IRQ_ENABLE(irq_ctx);
                               
                               //linear correlation function requires about 236us to return,with 60MIP
                               //therefore,we update global tick by 2 sample time
                               logv.tick +=2;
                                 if(correlation_result >= 80){
                                     result = TRUE;
                                 }
                                 else
                                 if
                                 (
                                 (correlation_result > 50)
                                 &&
                                 algorithm_data.diagnosis.hif_checklist.bits.itoi
                                 &&
                                 algorithm_data.diagnosis.hif_checklist.bits.ptop
                                 )
                                {
                                  result = TRUE;
                                }
                                 else
                                algorithm_data_mark_false_postives();
                               data_non_volatile.disturbance_record.hif_diagonesis_records
      .head = 0;
                               data_non_volatile.disturbance_record.hif_diagonesis_records
      .mean_value = 0;
                           }
                                    
                      }else if(algorithm_data.modules_state_sv.mfield_x_sen.
      fields.state == STATE_0){
                            algorithm_data_mark_false_postives();
                      }
                       
                }break;
        }
        }else if(algorithm_data.modules_state_sv.mfield_x_sen.fields.state ==
       STATE_0){
            if(algorithm_data.modules_state_sv.uv_sen.fields.state ==
      HOT)
            algorithm_data_mark_false_postives();
        }
        
        
        
        if(result == TRUE){
            hwio_execute_gpio_task(HWIO_ALARM_ON);
            logv.trip_active = TRUE;
             logv.disturbance_record.bits.wr = TRUE;
            memset(&algorithm_data.diagnosis.false_alarm,0,sizeof(
      algorithm_data.diagnosis.false_alarm));
            logv.sv_delay.set = TRUE;
            logv.sv_delay.cnt = DR_RECHECK_TIME;
            logv.sv_delay.type = DR_RECHECK;
        }
        
    }else if(event == EVENT_CLEARED){
          hwio_execute_gpio_task(HWIO_ALARM_OFF);
          logv.trip_active = FALSE;
          
    }else if(event == DR_RECHECK){
                    
            if(
              (algorithm_data.modules_state_sv.ir_sen.fields.
      post_act_data_ready == TRUE)
             ){
           data_non_volatile.disturbance_record.new_dr = TRUE;
           logv.disturbance_record.bits.wr = FALSE;
       algorithm_message_arrived_ntf_isr(
      IRQ_DR_READY);
           if(srv_hwio_data.emulation_mode.enabled.all != 0)
               srv_hwio_data.emulation_mode.enabled.all = 0;
       }
       else
          ASSERT(0);
            logv.sv_delay.set = FALSE;
            logv.sv_delay.cnt = 0;
            logv.sv_delay.type = 0;
       
    }else if(event == 0/*internal event*/){
#if(DEVICE == AQ0X_V1)
    if(data_non_volatile.device_data.sv_record.system_error_flags.bits.power_supply ==
      TRUE)
       nov_store();
#endif
      
    }
}
void msg_to_mem (void * dest, Uint8 * msg, Uint16 size, Uint8 base)
copy serially received data to given memory address
Definition at line 950 of file algorithm.c.
References serial_make16(), and serial_make8().
                                                             {
 
        Uint16 cc = 0;
        Uint16 var = 0;
        if(base == 8){
        Uint8* dst8 = (Uint8*)dest;
        for (var = 0; var < size; ++var) {
            *(dst8+var)= serial_make8(msg,cc);
            cc +=2;
        }
        }
        else if(base == 16){
        Uint16* dst8 = (Uint16*)dest;
            
        for (var = 0; var < size; ++var) {
            *(dst8+var)= serial_make16(msg,cc);
            cc +=4;
        }
        }
}
Variable Documentation
algorithm_data_t algorithm_data
Definition at line 33 of file algorithm.c.
Referenced by __attribute__(), and nov_set_default().
x_task_id algorithm_id
ALgorithm module handle.
Definition at line 34 of file algorithm.c.
Referenced by algorithm_message_arrived_ntf_isr(), and main().
logv_t logv
Definition at line 36 of file algorithm.c.
Referenced by __attribute__(), ir_sen_get_status(), light_sen_get_status(), mfield_x_sen_get_status(), and uv_sen_get_status().