mfield_z_sensor_prv.h File Reference
Data Structures
struct mfield_z_sen_data_t
Macros
#define X_MSG_MFIELD_SENSOR_SV (X_MSG_FREE)
Internal event message, initiates periodic supervision.
#define X_NTF_MFIELD_SENSOR_SV_TIMER (X_NTF_FREE + 2)
Internal supervison timer.
#define SV_TIMER_PERIOD 1000
Timeout.
Functions
Float32 mfield_z_sen_first_order_derivative (Int16 final_val, Int16 init_val, Float32 period)
Claculate first order derivative.
Float32 mfield_z_sen_calc_probablity (Uint16 event, Uint16 obs)
Claculates the event probablity.
void mfield_z_sen_sensor_element_sv_task (void)
Supervise the status of the mfield sensor.
void mfield_z_sen_false_positive_correction_task (void)
checks the number of false positives within supervision time window
void mfield_z_sen_mark_false_postives (void)
checks the number of false positives within supervision (100ms | 5 cycle) time window
Float32 mfield_z_input_signal (void)
Claculate.
Bool mfield_z_zero_cross (void)
Claculate.
Bool mfield_z_observation_time_window_expired (void)
Claculate.
Variables
mfield_z_sen_data_t mfield_z_sen_data
Internal mfield_z_sen module data.
Data Structure Documentation
struct mfield_z_sen_data_t
Definition at line 25 of file mfield_z_sensor_prv.h.
Data Fields
configured_t
configured
stores user configuration details
diagonesis_records_mfield_t
diagonesis_records
holds diagonesis data on the module operation
module_disturbance_record_t *
disturbance_record
disturbance record storage , details starting form the first event detection to the duration of observation record length
module_status_mfield_t
module_status
holds details about the module current state
sv_error_flags_ut
sv_errors_flags
supervission error flags
x_notify_mfield_sen_sv_report
sv_status_ntf
x_event
sv_task_event
Internal event for processing mfield module suppervission task.
x_notify
sv_timer_ntf
Timer notification to initiate mfield module suppervission task.
Macro Definition Documentation
#define SV_TIMER_PERIOD 1000
Timeout.
Definition at line 19 of file mfield_z_sensor_prv.h.
#define X_MSG_MFIELD_SENSOR_SV (X_MSG_FREE)
Internal event message, initiates periodic supervision.
Definition at line 12 of file mfield_z_sensor_prv.h.
#define X_NTF_MFIELD_SENSOR_SV_TIMER (X_NTF_FREE + 2)
Internal supervison timer.
Definition at line 15 of file mfield_z_sensor_prv.h.
Function Documentation
Float32 mfield_z_input_signal (void)
Claculate.
Parameters
ad_value
TODO: determine the frquency type and
Definition at line 255 of file mfield_z_sensor.c.
References state_data_mfield_t::change_per_time, module_status_mfield_t::current, mfield_z_compare(), mfield_z_sen_data_t::module_status, module_status_mfield_t::projected, and state_data_mfield_t::signal_level.
                                   {
    Float32 result;
    Float32 current_signal_level = 0;
              mfield_z_sen_data.module_status.
      projected.amplitude
              = mfield_z_sen_data.module_status.
      current.change_per_time/
                     (mfield_z_sen_data.module_status.
      projected.angular_freq
                      *cos(mfield_z_sen_data.module_status.
      projected.angular_freq*mfield_z_sen_data.module_status.
      current.time)
                      );
             current_signal_level = mfield_z_sen_data.
      module_status.projected.amplitude
               *sin(mfield_z_sen_data.module_status.
      projected.angular_freq*mfield_z_sen_data.module_status.
      current.time);
          result = mfield_z_compare((Float32)(
      mfield_z_sen_data.module_status.current.
      signal_level)
                  ,current_signal_level,0.05/*TODO: user configurable*/);
          if(result == 0)
              mfield_z_sen_data.module_status.
      projected.positive_cnt++;
          return result;
}
Bool mfield_z_observation_time_window_expired (void)
Claculate.
Parameters
ad_value
Definition at line 241 of file mfield_z_sensor.c.
References module_status_mfield_t::current, FALSE, mfield_z_sen_data_t::module_status, OBSERVATION_TIME_WINDOW, and TRUE.
                                                   {
    return (mfield_z_sen_data.module_status.
      current.time <= OBSERVATION_TIME_WINDOW)?FALSE:
      TRUE;
}
Float32 mfield_z_sen_calc_probablity (Uint16 event, Uint16 obs)
Claculates the event probablity.
Parameters
ad_value
Definition at line 191 of file mfield_z_sensor.c.
                                                             {
    return (Float32)event/(Float32)obs;
}
void mfield_z_sen_false_positive_correction_task (void)
checks the number of false positives within supervision time window
Definition at line 733 of file mfield_z_sensor.c.
Referenced by mfield_z_sen_taskx().
                                                      {
}
Float32 mfield_z_sen_first_order_derivative (Int16 final_val, Int16 init_val, Float32 period)
Claculate first order derivative.
Parameters
ad_value
Definition at line 179 of file mfield_z_sensor.c.
                                                                                          {
    return (Float32)(final_val-init_val)/period;
}
void mfield_z_sen_mark_false_postives (void)
checks the number of false positives within supervision (100ms | 5 cycle) time window
Definition at line 747 of file mfield_z_sensor.c.
References mfield_z_sen_data_t::configured, configured_t::dfdt_treshold_max, mfield_z_sen_data_t::diagonesis_records, mfield_z_sen_data_t::disturbance_record, module_disturbance_record_t::event_data, EXCEDED_AMP_TH, diagonesis_records_mfield_t::false_alarm, RANGE_MAX_32BIT, and RANGE_MAX_8BIT.
Referenced by mfield_z_sen_notifyx().
                                           {
        if(mfield_z_sen_data.disturbance_record->
      event_data.event_history == EXCEDED_AMP_TH){
               if(
                (mfield_z_sen_data.diagonesis_records.
      false_alarm.amp_max_exceded.cnt < RANGE_MAX_8BIT)
                &
                (mfield_z_sen_data.diagonesis_records.
      false_alarm.amp_max_exceded.accumulated_value < RANGE_MAX_32BIT)
               )
               {
                     mfield_z_sen_data.diagonesis_records.
      false_alarm.amp_max_exceded.cnt++;
                     mfield_z_sen_data.diagonesis_records.
      false_alarm.amp_max_exceded.accumulated_value
                     +=(mfield_z_sen_data.disturbance_record->
      event_data.buffer.signal_level[0]-mfield_z_sen_data.
      configured.amp_treshold_max);
                     mfield_z_sen_data.diagonesis_records.
      false_alarm.amp_max_exceded.recorded_avg
                     = mfield_z_sen_data.diagonesis_records.
      false_alarm.amp_max_exceded.accumulated_value/
                             (Float32)mfield_z_sen_data.
      diagonesis_records.false_alarm.amp_max_exceded.cnt;
              }
             }else if(mfield_z_sen_data.disturbance_record->
      event_data.event_history > EXCEDED_AMP_TH){
             if(
                (mfield_z_sen_data.diagonesis_records.
      false_alarm.dfdt_max_exceded.cnt < RANGE_MAX_8BIT)
                &
                (mfield_z_sen_data.diagonesis_records.
      false_alarm.dfdt_max_exceded.accumulated_value < RANGE_MAX_32BIT)
               )
             {
                 mfield_z_sen_data.diagonesis_records.
      false_alarm.dfdt_max_exceded.cnt++;
                 mfield_z_sen_data.diagonesis_records.
      false_alarm.dfdt_max_exceded.accumulated_value
                 +=(mfield_z_sen_data.disturbance_record->
      event_data.buffer.change_per_time[0]-mfield_z_sen_data.
      configured.dfdt_treshold_max);
                 mfield_z_sen_data.diagonesis_records.
      false_alarm.dfdt_max_exceded.recorded_avg
                 = mfield_z_sen_data.diagonesis_records.
      false_alarm.dfdt_max_exceded.accumulated_value/
                    (Float32)mfield_z_sen_data.
      diagonesis_records.false_alarm.dfdt_max_exceded.cnt;
             }
             }
}
void mfield_z_sen_sensor_element_sv_task (void)
Supervise the status of the mfield sensor.
Parameters
ad_value
Supervises mfield sensors element by measuring sensor respond for different illumination level
Definition at line 721 of file mfield_z_sensor.c.
Referenced by mfield_z_sen_taskx().
{
}
Bool mfield_z_zero_cross (void)
Claculate.
Parameters
TODO: angular freq = 2*PI/(this_time - last_cross_time)
Definition at line 203 of file mfield_z_sensor.c.
References module_status_mfield_t::current, FALSE, mfield_z_sen_data_t::module_status, state_data_mfield_t::polarity, module_status_mfield_t::previous, and TRUE.
                              {
    if((mfield_z_sen_data.module_status.previous.
      polarity*mfield_z_sen_data.module_status.
      current.polarity)<=0)
    return TRUE;
    else
    return FALSE;
}
Variable Documentation
mfield_z_sen_data_t mfield_z_sen_data
Internal mfield_z_sen module data.
Definition at line 22 of file mfield_z_sensor.c.